### ISSUE TITLE
[Plasma 5] Notify prompt showing black box instead of octopi icons 

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#100]
![zrzut ekranu2](https://cloud.githubusercontent.com/assets/9846948/7083361/0c9a1ebe-df61-11e4-8abf-4166653c76e3.png)
Should using RED or YELLOW icon in prompt notify, but I see black box... 
After focus octopi tray icon prompt in default state is normal green.
![zaznaczenie_017](https://cloud.githubusercontent.com/assets/9846948/7083386/80d17f70-df61-11e4-9557-3ec3ccb87394.png)

Plasma  5.2.2
Qt 5.4.1

**Comment by aarnt** [comment]
This is a plasma issue.
