### ISSUE TITLE
Octopi doesn't recognize kdesudo and Archlinux

### ISSUE THREAD

**Issue by ZeroBit** [aarnt/octopi#103]
In Arch linux octopi doesn't recognize kdesudo. It says "There are no means to get administrator's credentials. You'll need to install a su frontend like gksu or kdesu."

I have kdesu installed and kdesudo installed. But kdesu package doesn't contain /usr/bin/kdesu

http://pastebin.com/Hwdc1xuC

Therefore, please, make it possible to use kdesudo along with kdesu 

![image](https://cloud.githubusercontent.com/assets/6258813/7270271/ad6c1d66-e8e3-11e4-9ee2-0e9ca6eab887.png)

**Comment by Dr-Shadow** [comment]
The command kdesu has moved in another package :

https://www.archlinux.org/packages/extra/x86_64/kde-cli-tools/
