### ISSUE TITLE
About search input box.

### ISSUE THREAD

**Issue by libook** [aarnt/octopi#104]
I can not input space into search box. Is it a bug?

Every time I input a letter, it do search, even though I haven't finished my inputting. Searching is slow. So my inputting became slow.
My proposal is:
Press a key -> Set a timeout for 2 seconds -> Another keyPress -> Destroy the timeout and start a new timeout -> Time out -> Do search
Or remove the automatic searching and add a button...

**Comment by aarnt** [comment]
The slowness is a bug fixed upstream:
BugFix: Filter connect chain bug decreased filter's performance over time.

**Comment by aarnt** [comment]
In 0.7 you can input space chars.
