### ISSUE TITLE
New GCC 5.1.0 = core dump memory leak in Octopi

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#105]
Arch devs commit new GCC version in testing repos. 
After compile octopi and launch it I have  core dump memory leak - app not working anymore.
Difference between  4.9.2 gcc build and new 5.1.0 build is in octopi package size: 0,02 MB too.

Regards.

https://www.archlinux.org/packages/?sort=-last_update&q=gcc&maintainer=&flagged=
additional info from dmesg:

    [ 6148.311383] octopi-notifier[11329]: segfault at 8 ip 00007fe36dc9cafc sp 00007ffe67224b60 error 4 in libQt5Core.so.5.4.1[7fe36d9de000+4c1000]
    [ 6159.954582] octopi-notifier[11346]: segfault at 8 ip 00007fdc42e07afc sp 00007ffeb0036a20 error 4 in libQt5Core.so.5.4.1[7fdc42b49000+4c1000]
    [ 6174.850778] octopi-notifier[11374]: segfault at 8 ip 00007f27da589afc sp 00007fffbf7ccb60 error 4 in libQt5Core.so.5.4.1[7f27da2cb000+4c1000]
    [ 6188.058997] octopi[11394]: segfault at 8 ip 00007fc788d23afc sp 00007ffd6ae71950 error 4 in libQt5Core.so.5.4.1[7fc788a65000+4c1000]

**Comment by aarnt** [comment]
Well, GCC 5.1 is a bleeding edge compiler that just got out. I'm quite shocked Arch guys are already testing it. I think there's a limit to be on the edge of things as that thing in special is needed to almost every piece of software in a Linux distro.
Unfortunately, I won't be able to help you with that issue as it clearly a GCC one.

**Comment by demmm** [comment]
Just to confirm, I've seen a ton of bug reports for anything Qt5/frameworks build with gcc 5.1
Not at all confined to just octopi.

**Comment by sl1pkn07** [comment]
https://bugs.archlinux.org/task/44910
