### ISSUE TITLE
Encoding error?

### ISSUE THREAD

**Issue by s8321414** [aarnt/octopi#107]
<a href="http://imgur.com/KKYfIh8"><img src="http://i.imgur.com/KKYfIh8.png" title="source: imgur.com" /></a>
You can see here,toolbar has some unknown text.
My system is Chakra,using octopi 0.7.0 qt4 version.
My locale is zh_TW.UTF-8

**Comment by aarnt** [comment]
This is a Qt5 Designer issue that is crippling Qt4. Later I'll see if I could fix it. Thanks!

**Comment by s8321414** [comment]
And it only affect octopi toolbar, if you click into it, all options are fine there :smiley:

**Comment by aarnt** [comment]
I think I got it fixes at upstream.

**Comment by s8321414** [comment]
\o/

**Comment by s8321414** [comment]
hmmm,it is not fixed when I use latest commit here,still the same on menubar,and all things in the menubar become English.

**Comment by s8321414** [comment]
Maybe you will want to drop Qt4 support in next stable release :3

**Comment by s8321414** [comment]
I think this issue can be closed because Qt5 version doesn't have this issue.

**Comment by aarnt** [comment]
Thanx!

**Comment by s8321414** [comment]
@aarnt Great!
