### ISSUE TITLE
Incomplete strings in intervall settings dialog

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#109]
![screenshot from 2015-05-10 10-19-49](https://cloud.githubusercontent.com/assets/735265/7553561/1b6de564-f6ff-11e4-9487-c970b389098c.png)

As you can see, ending of lines is not shown properly, because strings are little bit longer, but it cant be translated shorter.

**Comment by demmm** [comment]
What happens if you resize the window?  Same issue can be had if you reduce the size of the window with any language, and works correctly here, if enlarged properly to fit the language's needs.

**Comment by prescott66** [comment]
Same issue after resizing window.my lang: slovak

**Comment by aarnt** [comment]
Can u test with latest commit?

**Comment by prescott66** [comment]
yep is fixed now. thx
