### ISSUE TITLE
No diacritics/special characters in xterm window

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#110]
I dont see any special characters of my language(slovak) like "ľščťžýáíéúäň" in xterm window-while installing something from AUR.
I tried same command (yaourt "package_name") in xterm terminal manually, and i can see all characters, with no problems.

**Comment by aarnt** [comment]
Hi prescott,
Make this test: 
type "Ctrl+Shift+T" to change your terminal emulator to any diffrent from "xterm".

After that, try running a transaction inside it, to see if your language settings is honored.

**Comment by prescott66** [comment]
i get empty dialog windows after typing ctrl+shift+t
as you can see:

![snimka obrazovky z 2015-05-15 18-17-06](https://cloud.githubusercontent.com/assets/735265/7656996/af0bb8e0-fb2e-11e4-8061-7d9c0ca0bf05.png)

**Comment by aarnt** [comment]
Hi prescott,
This is probably because you do not have "qt5-quickcontrols" installed. Do you?

**Comment by prescott66** [comment]
1.qt5-quickcontrols was not installed - fixes issue with empty dialog window.(maybe it is needed to add qt5-quickcontrols as a octopi dependency)

2.i have in list: automatic,xterm,gnome-terminal. after selecting gnome-terminal, octopi is freezed and i can do nothing, octopi main window cant be closed too(only via system monitor). i am using gnome shell 3.16. installed gnome terminal version: 3.16.2

3.i want to say that it would be great, if octopi will have defaulty selected "automatic" option and will select terminal by desktop environment, and xterm will be fallback terminal, because xterm is not very well integrated(graphically, in one word: is ugly :smiley: )

**Comment by aarnt** [comment]
Hi Prescott,

1) If you take a look at https://github.com/aarnt/octopi/blob/master/PKGBUILD you'll see qt5-quickcontrols is already an octopi dependency (at least in the developed pkg, of course I cannot control what distros will package);

2) Weird behavior, did you test with other terminals? Or do you have only gnome and xterm in that list?

3) Octopi defaults to "automatic". Maybe it's not working in your system because of some bug. Take a look at that code: https://github.com/aarnt/octopi/blob/master/src/terminal.cpp#L63. There you can see Octopi tries to guess which terminal to open based on what desktop environment is running by user.

**Comment by prescott66** [comment]
i am not a programmer.sorry...i have only xterm and gnome-terminal in list...i am using antergos OS, maybe you can try it and debu by yourself, and take a look on latest gnome shell integration too.

**Comment by Oxalin** [comment]
I'll test it and see if I end up as Prescott66. I'm using Archlinux though.

**Comment by Oxalin** [comment]
@aarnt , with qt5-quickcontrols installed (was already installed), I was able to select gnome-terminal (it was on automatic) without any issue. With it, I saw the same behavior as usual (truncated sentences). I think gnome-terminal is the default terminal in my case. I'll have to test with the other terminals available (like xfce).

**Comment by aarnt** [comment]
Ok, Oxalin, I'd appreciate your tests!

**Comment by Oxalin** [comment]
@aarnt , I tried the 4 available options I had: automatic, gnome-terminal, xfce4-terminal and xterm. I closed Octopi between each change and test. All produced the same bug where sentences were truncated when encountering an accented character.

**Comment by Oxalin** [comment]
Long time this bug has been into sleep. Waking it up. I'm "thinking" loud here: after having a look at Octopi's code, locale variables are first unset and then forced to "C" (collate) when calling a terminal. I've been reading here and there and it could be the source of the problem: by forcing to "C", we may end up with an ASCII charmap, which may prevent any accented characters from appearing correctly... I'll need to try it though.

**Comment by Oxalin** [comment]
@prescott66 are you still able to reproduce this bug? I'm not, while all my settings are now  pointing to french locales instead of english. What I want to know is if the bug is gone or if this is a problematic combination that makes it happen.

**Comment by prescott66** [comment]
@Oxalin Tested on Octopi 0.8.3 and bug is not reproduced anymore...

**Comment by Oxalin** [comment]
I'll have another try on a different system, the one I use at work just to be sure.

**Comment by Oxalin** [comment]
Still using Arch. Tested at work and everything seems fine. There is, however, a small bug that appears with any languages that I'll have to investigate at some point.

This bug can be closed.

**Comment by aarnt** [comment]
Thank you all for the testing.
