### ISSUE TITLE
Too many notifications in Gnome Shell 3.16

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#111]
I get too many notifications  with the same updates.
Screenshot:
![snimka obrazovky z 2015-05-14 14-32-14](https://cloud.githubusercontent.com/assets/735265/7631723/2ca6d2ba-fa46-11e4-9d2f-d9af21394401.png)

**Comment by prescott66** [comment]
aarnt is this fixed? because i still encounter this bug in gnome 3.18 with octopi 0.8

**Comment by aarnt** [comment]
Hi, I removed 'notify-send' call in notifier's upstream code. This will probably fix this.

**Comment by prescott66** [comment]
Hi. cool. thanks.
