### ISSUE TITLE
Problem with accented character in the output pane

### ISSUE THREAD

**Issue by Oxalin** [aarnt/octopi#112]
In french, the text shown in the output pane is incomplete / truncated. As an example, "Mise à jour de " + packageName results in a truncated sentence of a single word "Mise". It seems to be truncated when it encounters accented characters (à, â, ê, è, é, î, û, ù...).

I could add a screenshot next time I'll have an update available.

**Comment by prescott66** [comment]
same bug as #110

**Comment by Oxalin** [comment]
Yes, missed it.
