### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by kikadf** [aarnt/octopi#116]
Hi! 

First thanks your work, Octopi is a great pacman gui, I use it on Arch Linux and I love it. :)

If not problem, I would like to propose some features to Octopi:
1. Show the file lists by all package, I think it is possible, the website of arch knows this feature.
2. Search file in file lists of packages. For example if somebody need a *.so file, or a kernel module, but don't know which package contain this file.
3. Would be nice, if we can show the change logs of packages in octopi.
   (For instance: https://projects.archlinux.org/svntogit/packages.git/log/trunk?h=packages/linux)
4. I like an option to edit&compile an official package. Like an AUR package. For example, I would like to recompile virtualbox-modules-\* packages with the new kernel...
5. Option to add a flag to an official package, or add a vote, or comment to an AUR package.

Sorry, but I can't help for you, or myself to adopt this features, I am just a user, can't programming. :(

Best regards,

kikadf

**Comment by demmm** [comment]
Point 1 & 2 are already implemented & working, make sure you have pkgfile installed and updated.

**Comment by kikadf** [comment]
Hi!

I have Octopi - 0.7.0 (Qt 5.4.1).
I haven't got this feature, only I see the packagelist if the package is installed. The file search is not working for me, don't do anything.

![octopi1](https://cloud.githubusercontent.com/assets/1190081/8436739/daf65122-1f5a-11e5-9f49-f3af65b24af4.png)

What is your octopi version, and what is your settings? What is your distro?

Thanks.

**Comment by demmm** [comment]
Distro here is KaOS, but pkgfile is a build-in feature for both KaOS and Arch in Octopi, again make sure you have it installed and regularly run "sudo pkgfile --update".

**Comment by kikadf** [comment]
I installed pkgfile, and enabled, so the 1. point is working. Thanks :)

But the 2nd is not for me: for example systemd can't load the vboxguest kernel modules. I want to check the package, but I don't know what is its package. 

I thought just type vboxguest, or vboxguest.ko to the search box, and choose the find as file button. The result: packages what provides vboxguest* or vboxguest.ko* files.

**Comment by Oxalin** [comment]
@kikadf, I was looking at your feature requests. About the 3rd one (about adding a log tab), could you be more specific? You see, to have a log of the package shouldn't be too difficult but maybe not so useful (if I use the link you provided, the log is pretty boring). However, maybe what you are looking for in your request is a log of the source itself. It would be a lot more interesting, but a bit more complicated (but maybe not that much).

**Comment by Oxalin** [comment]
@kikadf, there is also another option that I have not proposed, which is using something similar to "pacman -Qc". But as you'll see, the package must contain a change.log file. Since it is not a requirement for any package maintainer, they are uncommon. Using the online change log from the git repository would be more useful most of the time.
