### ISSUE TITLE
Showing same version number for outdated and available version

### ISSUE THREAD

**Issue by Dineshrajaa** [aarnt/octopi#117]
I am using Octopi in my Manjaro linux and i found that for "AUR" packages the summary is shown wrongly for both the Available and Outdated same version number is being shown 
Here is the screenshot of it 
![octopi](https://cloud.githubusercontent.com/assets/7291567/8593235/845f8f7c-2653-11e5-9f99-88fab7889476.png)

**Comment by baelter** [comment]
You are not alone..

**Comment by Dineshrajaa** [comment]
Now it has been fixed by a commit made by @jdelmas  so I'm closing it. :)
