### ISSUE TITLE
Add sudo support for non-root accounts

### ISSUE THREAD

**Issue by ghost** [aarnt/octopi#118]
Hi all, my user account is added in wheel from /etc/group and /etc/gshadow but i can't use octopi with sudo support from kdesu, however, if i use another apps from the same way (kdesu), it works from KDE.

Note: the wheel group is enabled in /etc/sudoers

```
/etc/sudoers
------------------
%wheel ALL=(ALL) ALL
```

**Comment by Ryex** [comment]
yes please, giving the root passwords just doesn't fly for me.

**Comment by ThornedRose** [comment]
You may need to configure kdesu/gksu to use sudo instead of su.
Instructions here:
GKSU: https://wiki.archlinux.org/index.php/Sudo#gksu
KDESU: https://wiki.archlinux.org/index.php/Sudo#kdesu

**Comment by aarnt** [comment]
Sudo works in KDE with octopi. Problem is some output is missing, like download percentages.

**Comment by postadelmaga** [comment]
this problem is still present, at least on arch.
Other programs works fine ( unebootini, gparted ... ) but octopi call kdesu and kdesu uses su instead of sudo.
The proposed solution `kdesu/gksu to use sudo instead of su.` doesn't look good because kdesu is supposed to use su

**Comment by sebalis** [comment]
I have just tried configuring gksu to use sudo as suggested by @ThornedRose in a [previous comment](https://github.com/aarnt/octopi/issues/118#issuecomment-170294213). I am using Arch and the GNOME desktop. The password entry dialog changes after I change the gconf seting: the option to save the password (checkbox and radio group to select where/how long to save) are gone. The dialog still asks for “the administrator’s password”. But whether I enter the root password or my user’s password (the user is of course allowed to use sudo), after completing the entry an error message appears in the Octopi window (“Command finished with errors!”, no further details).

I probably don’t need to elaborate that it’s good practice to prevent root from having a user password. With this state of things, I can’t implement that practice. So I would like to see this improved.

**Comment by aarnt** [comment]
Wanna use Plasma with octopi without being asked for a password?
Just change the "/etc/pam.d/su" file to implicitly trust users from wheel group.

**Comment by sebalis** [comment]
I don’t think the solution offered in the previous comment is sufficient to close this bug. Not everyone is using Plasma (I am not), and not everyone wants to att trust to the whole of the “wheel” group.
