### ISSUE TITLE
Drop Qt4 support.

### ISSUE THREAD

**Issue by s8321414** [aarnt/octopi#121]
I think it is time to drop qt4 support now, qt4 will be EOL soon, and drop its support can decrease maintenance difficulty.

**Comment by aarnt** [comment]
From CHANGELOG: 

0.8.0 (dev)
  This is a Qt5 only version (with the exception of 'octopi-notifier').

**Comment by s8321414** [comment]
hmmm... why except octopi-notifier?

**Comment by aarnt** [comment]
Because some GTK DEs do not work very well with Qt5 system tray objects.

**Comment by s8321414** [comment]
:S
