### ISSUE TITLE
octopi-notfier: tooltip ?

### ISSUE THREAD

**Issue by ringo32** [aarnt/octopi#122]
hi,

got request for a bit ...irc user got a bit color blind user, it can see a bit of color...

but he said, it would be fine if the yellow icon of octopi-notifier got some text as Aur update.

got brainstorming about icon etc blinking is sometimes anoying :) but as tooltip in his LXQT-manjaro would be fine if its said aur.

because for him is dificult to say its pacman update or aur ..

gr ringo

**Comment by aarnt** [comment]
Commit 944...
