### ISSUE TITLE
3906d74 commit freak out aur updates...

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#124]
See: 
![zaznaczenie_003](https://cloud.githubusercontent.com/assets/9846948/8851857/2ced3d5c-3152-11e5-8885-7cc9fd365581.png)

I using always lastest commit build.

commit 3906d74

BUT in AUR4 it is available rev -7 of this package:
aur/lib32-a52dec 0.7.4-6 6 -> 7

I'm using an alias for updating from AUR4.

**Comment by aarnt** [comment]
Fademind, the latest commit only changes the tooltip in the notifier octopi icon.

**Comment by FadeMind** [comment]
OK, maybe just octopi freak out and in the meantime did not refresh status of packages...
