### ISSUE TITLE
Don’t trim package names/versions

### ISSUE THREAD

**Issue by flying-sheep** [aarnt/octopi#125]
My screen is big, I want to see that i’m upgrading `firefox-developer-edition (41.0a2+20150804+g91ebc3e-1 -> 41.0a2+20150805+g791c5d2-1)` instead of  `firefox-developer-e…`

trimming happens [here](https://github.com/aarnt/octopi/blob/6df0f8a03d9f8cb1a9b91f158f837ec3efe2ebbd/src/mainwindow_transaction.cpp#L2029)? or is that just for whitespace, and the ellipsis gets introduced elsewhere

**Comment by aarnt** [comment]
Hi flying-sheep,
The method "QString::trimmed()" only removes spaces.
This issue is being generated by "pacman" itself.

**Comment by flying-sheep** [comment]
i can’t remember it doing that in the console… might it be that it thinks it’s run in a slim terminal window? if so, can we simulate a infinite-width terminal window?

**Comment by aarnt** [comment]
Indeed, I made some tests here. It seems that issue only happens with slim terminals. The problem is I have no idea how to solve it.

**Comment by flying-sheep** [comment]
easy: [`getcols`](https://projects.archlinux.org/pacman.git/tree/src/pacman/util.c#n224) in pacman just uses the `COLUMNS` env variable.

so just call pacman in an environment with that set to a high value

**Comment by aarnt** [comment]
Changed to value 132. Thanks!

**Comment by flying-sheep** [comment]
then this should be fixed, right?

**Comment by aarnt** [comment]
Yeah.
