### ISSUE TITLE
Wrong Version Update detection

### ISSUE THREAD

**Issue by ShalokShalom** [aarnt/octopi#128]
Octopi recommend sometimes an old version as the new one and vice versa. Happens with the casual Repo and KCP. http://funkyimg.com/view/21mxE

**Comment by xgdgsc** [comment]
I often get same available version number as outdated version in the interface. But actually the new version exists and can be updated with octopi. Just the available version number is shown wrong.

**Comment by ShalokShalom** [comment]
[](http://funkyimg.com/i/29LV8.png)

**Comment by aarnt** [comment]
I think it's fixed in upstream.

**Comment by ShalokShalom** [comment]
![screenshot_20161028_002843](https://cloud.githubusercontent.com/assets/6344099/19788174/322b3e74-9ca7-11e6-80ea-8f6280f9d589.png)
