### ISSUE TITLE
Octopi doesn't load sometimes after update to kde 5

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [aarnt/octopi#131]
Sometimes it comes out 1 h after boot.
I sometimes start it from cli but still it doesn't come out.

**Comment by aarnt** [comment]
Could you run octopi with "octopi -d" and post your findings at a pastebin alike site?

**Comment by GreatBigWhiteWorld** [comment]
OK Now I may see the problem more clearly.
Octopi may load very slowly after boot, which is ok (I guess it's due to unstable network)
The real problem now is that it can't be launched from trayicon however you click it.

One way to load it with an interface up is that I kill all octopi process then run it manually.

**Comment by aarnt** [comment]
Closing by age.
