### ISSUE TITLE
octopopi-notifier can be quitted with a single mouse click *anoyance*

### ISSUE THREAD

**Issue by freed00m** [aarnt/octopi#132]
When I RIGHT mouse click on the tray icon, the menu is shown. Issue is, that the quit button can be activated also with a RIGHT mouse click and even via button release. 

TL:DR click hold on the icon shows the menu and the release will activate the quit function. Many accidental quits has been made.

---

Octopi Notifier - 0.7.1-1 (Qt 4.8.7) Manjaro I3wm

**Comment by aarnt** [comment]
There is no way to prevent this accidental issue inside Qt code.
