### ISSUE TITLE
Partial upgrades?

### ISSUE THREAD

**Issue by AladW** [aarnt/octopi#134]
I see a few references to pacman -Sy. So, does octopi do a partial upgrade [1] when checking for updates? Scripts like checkupdates sync to a temporary directory instead.

[1] https://wiki.archlinux.org/index.php/Pacman#Partial_upgrades_are_unsupported

**Comment by aarnt** [comment]
Yes, you can use Octopi to do partial upgrades. As long as you can do that with pacman too. So, it's up to the user to take this risk.

**Comment by AladW** [comment]
Except pacman doesn't run it without user intervention. 

https://github.com/aarnt/octopi/blob/3906d743967834dd77139db047ea7c07cae29fd4/notifier/octopi-notifier/mainwindow.cpp#L181

If you want to schedule/notify users of updates, use fakeroot to a separate directory like pacman does.

**Comment by rmarquis** [comment]
This is horrifying.

**Comment by Yoshi2889** [comment]
It's funny though, since if you refresh your package lists using the GUI and then try to install any other package without having upgraded first, Octopi blocks you in that "Partial upgrades are not supported."

**Comment by aarnt** [comment]
That's because Octopi NO LONGER support partial upgrades!

**Comment by aarnt** [comment]
Well... 
Suppose you have 5 packages available to upgrade: packages A, B, C, D and E.
Octopi will not let you update any of them alone. You'll have to do a system upgrade.
I call that a partial upgrade, when you try to upgrade one (or more than one) at a time, instead of all of them.

**Comment by AladW** [comment]
That assumes octopi is the only thing you'll ever use to manage your packages. To `pacman` or any other libalpm frontend you're still in a partial upgrade scenario.

**Comment by Aicaya** [comment]
Why not make the package ``pacman-contrib`` a regular dependency instead of just a "make" one and use the command ``checkupdates`` that comes with it instead of ``pacman -Sy``? It does the same thing without performing what Arch defines as "partial upgrade", and then the "System upgrade" command can be switched to ``pacman -Syu``. (Unless there are limitations with the ``checkupdates`` command that I'm not aware of.)

**Comment by Kran1x** [comment]
Isn't it only pacman -Sy <package> that's dangerous? Doesn't pacman -Sy by itself just check databases without modifying any packages, thus running no risk of breaking anything?

**Comment by AladW** [comment]
Running `pacman -S package` after `pacman -Sy` has the exact same problems as `pacman -Sy package`.

**Comment by aarnt** [comment]
No more "pacman -Sy[y]" code in upstream.
Octopi uses checkupdates now.
Thanks guys!
