### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by flying-sheep** [aarnt/octopi#139]
hi, 0.7 has been quite some time ago and there’s stuff in master that i’d like to have :smiley:

**Comment by aarnt** [comment]
Hi flying-sheep,

Indeed, 0.7 was out almost six months ago.
Yesterday I was trying to solve a bug I introduced due to a change (not yet commited). I hope to squash it soon (although it's pretty weird).

Thanx for your interest.

**Comment by pmattern** [comment]
After performing some tests on Arch Linux x86_64, thus Qt 5.5, I wonder whether it wouldn't make sense to enable KSNI by default in Octopi's next release.

With KSNI enabled by un-commenting `#DEFINES += KSTATUS` in `octopi-notifier.pro` Octopi notifier from c5f56cc was working flawlessly with "System Tray" of KDE Plasma 5 and plugin-statusnotifier of LXQt, both implementing KSNI, as well as with the panel plugins of LXDE, Xfce and plugin-tray of LXQt which all are implementing the old System Tray specification (the one from LXQt is maintained to provide compatibility for the time being only).
Qt 5.5 has made it into the repos of both KaOS and Chakra (don't know either of these well), so apparently the only obstacle could be those "GTK environments" you state [here](https://github.com/aarnt/octopi/issues/121#issuecomment-120932459).
Enabling KSNI by default would in particular allow for better testing against this rather new specification which is nevertheless likely to replace System Tray Specification in the not too distant future.
