### ISSUE TITLE
notifier zombie processes

### ISSUE THREAD

**Issue by rnd42** [aarnt/octopi#14]
Hello,

I am using an up to date version of octopi-notifier from the Arch Linux AUR.  I just noticed that I had literally hundreds of `[octopi-notifier] <defunct>` entries when I ran `ps -ef`.  I ended up exiting the notifier and relaunching it and after 20 minutes it's already created 9 zombie processes...  I straced octopi-notifier with the command `strace octopi-notifier 2>&1 | ts` and waited for it to create a zombie (besides the 1-2 it seems to create at the beginning every time it's launched) and extracted the portion of output that corresponded with the time `ps` shows the zombie processes were started which you can view at http://slexy.org/view/s2Vof9WEWo .  Sorry I'm not a C++ dev otherwise I might take a stab at this issue.

**Comment by aarnt** [comment]
Hi, 
Do you still have this behavior using latest versions?

**Comment by rnd42** [comment]
I haven't used it in a while but I just installed it on a new install and I don't seem to see that behaviour happening anymore.  Thank you.
