### ISSUE TITLE
repoeditor

### ISSUE THREAD

**Issue by miku84** [aarnt/octopi#141]
Not a big request, but I think it would be useful when Repoeditor could also control branches, like stable, testing and unstable. 

And maybe a button for sudo pacman-mirrors -g could be also helpful.

**Comment by s8321414** [comment]
pacman-mirrors and release branches are Manjaro's special features I think

**Comment by miku84** [comment]
Oh, I did not know that. If it is true, then the request is not relevant anymore.

**Comment by aarnt** [comment]
Yes, indeed it is. I'm closing the request.
