### ISSUE TITLE
Icon for octopi-notifier in Cinnamon

### ISSUE THREAD

**Issue by stovocor** [aarnt/octopi#146]
In Cinnamon the tray icon of octopi-notifier is not displayed, but I am able to click on the empty space.
![bildschirmfoto vom 2015-11-28 11-46-33](https://cloud.githubusercontent.com/assets/1096199/11451446/d10cd054-95c6-11e5-9e39-14e67bc2c30c.png)

**Comment by aarnt** [comment]
This is a Qt5 bug regarding GTK systems.
Try using the Qt4 version of octopi-notifier.

**Comment by stovocor** [comment]
Where can I get this? It seems the AUR package no longer exists.
