### ISSUE TITLE
Option to disable notification or set notification interval

### ISSUE THREAD

**Issue by xgdgsc** [aarnt/octopi#147]
Currently octopi shows the icon animation in KDE system tray when there is any update, which can be annoying. I hope an option to set notification interval (such as daily/weekly, or notify only on Saturday/Sunday) be added.

**Comment by aarnt** [comment]
There is no animation on color changes. And the option to set notification interval already exists since version 0.7. I could increase value maximum value in minutes to simulate "once a week".

**Comment by aarnt** [comment]
Value has been increased in upstream.

**Comment by xgdgsc** [comment]
What do you mean by upstream? I didn' t find value maximum change.

**Comment by aarnt** [comment]
Upstream is the development code that is hosted here. Version 0.8.1 will have it.

**Comment by xgdgsc** [comment]
How to disable the animation that changes the tray icon size?
