### ISSUE TITLE
SysInfo update for KaOS

### ISSUE THREAD

**Issue by aarnt** [aarnt/octopi#151]
Add
/var/log/installation.log
to "SysInfo" in KaOS.

**Comment by demmm** [comment]
Implemented with this patch:
https://github.com/KaOSx/apps/commit/b75d1f7c503e3c2dd318de82e52af134fe7a6772#diff-0b8667833e0381f3eb0b1646bd90258aL30

**Comment by aarnt** [comment]
Added. Thanx!
