### ISSUE TITLE
When click on octopi-notifier-qt5 "sync" it hijacks keyboard input for gtk3 apps

### ISSUE THREAD

**Issue by freed00m** [aarnt/octopi#152]
Hello, I have a problem with octopi-notifier-gtk3, when I click sync-database, it sync fine, but It selects some ghost input or I don't have a clue what's going on and I loose the ability to type (any keyboard input) into gtk3 apps. 

I use i3wm and the app I want to type into is gtk3 and is selected with i3. 
Usually I run into the problem when I manualy sync database and have only firefox open, after clicking sync I can't type into firefox and I have to switch workspace or to go fullscreen and out. It's not only firefox but all gtk3 apps. It might sound like a i3wm issue but when I use octopi-notifier gtk2 version, then it's fine.

i3 -v 4.11
octopi -v 0.8.0-4
gtk3 -v 3.18.6-2

**Comment by aarnt** [comment]
This is a collateral toolkit issue.
Try to install the Qt4 version of octopi-notifier, if it exists in your distro.

**Comment by freed00m** [comment]
I have mistaken the framework, it was qt5 that caused the problem with gtk3 apps, downgrading to qt4 helped but the issue was with qt5 notifier,

**Comment by aarnt** [comment]
Yes.
Most of GTK window managers and apps do not like Qt5 based code for the notification area.

**Comment by freed00m** [comment]
If it's wont fix due a GTK3 qt5 incompatibility then you may close this issue. It will probably fix itselft in future. :) thanks for your time.

**Comment by aarnt** [comment]
Ok.
