### ISSUE TITLE
Missing dependencies in Version 0.8.0-4

### ISSUE THREAD

**Issue by viking60** [aarnt/octopi#153]
After having removed orphans; Octopi did not fire because  xcb-util-cursor and  xcb-util-renderutil were removed.

A fresh Octopi install did not pull them back so I had to reinstall them manually.

https://forum.manjaro.org/index.php?topic=30773.msg253937#msg253937

**Comment by demmm** [comment]
Are you sure this is not a packaging issue with your distro?  Are you running without xorg-server?  Did you check with your distro if they are building with all the needed depends?

**Comment by aarnt** [comment]
Viking, this seems to be a package issue. I think Phil is the Octopi packager in Manjaro.

**Comment by viking60** [comment]
Yes sorry about this - bad day there.

Tha packager at Manjaro is artoo

Den 06. feb. 2016 19:41, skrev Alexandre Arnt:
