### ISSUE TITLE
Feature Request - Octopi

### ISSUE THREAD

**Issue by Jam3alay8** [aarnt/octopi#154]
Sometimes there is a db.lock in /var/lib/pacman.
Would it be possible to have Octopi check for the presence of this db.lock and let us know, perhaps showing a padlock icon.

I use Manjaro, I'm not sure if this path is valid in other distributions that use Octopi. If the path is different, It is pointless to request such a feature.
In that case, my apologies.

**Comment by aarnt** [comment]
In Octopi, whenever a user wants to commit a transaction and a "db.lock" is present, a dialog asking for its removal will pop up.

**Comment by Jam3alay8** [comment]
Hah! Did not notice that. I'll pay more attention next time.
Thanks.
