### ISSUE TITLE
No progress bar in Gnome

### ISSUE THREAD

**Issue by ljfa-ag** [aarnt/octopi#155]
In Gnome 3, during download or installation there is no progress bar or percentage being shown in the bottom. Unlike on my other machine running Plasma, where you can see the progress for each package.
[Screenshot](https://cloud.githubusercontent.com/assets/3437174/13284653/eeb0ceb6-daf5-11e5-887b-4eebeac5fda1.png)

Using Gnome 3.18.2 and Octopi 0.8.0-1

**Comment by aarnt** [comment]
Are you using Octopi with gksu in Gnome?

**Comment by ljfa-ag** [comment]
Yes

**Comment by Oxalin** [comment]
Strange, because I have the progress bar showing at the bottom on Gnome 3. @ljfa-ag is this still an issue?

**Comment by ljfa-ag** [comment]
Yes, the only time it is showing a progress bar for me is after synchronizing the database.

**Comment by aarnt** [comment]
Then it's because pacman process is not getting any output from the terminal in the update/install/removal tasks.

**Comment by Oxalin** [comment]
@ljfa-ag , could you:
- tell us the terminal you are using?
- test with different terminals?

Use Ctrl+Shift+T while you have Octopi displayed to open a window and select a different terminal.

**Comment by aarnt** [comment]
@Oxalin I don't think it's a terminal issue. It seems to be gksu related.

**Comment by ljfa-ag** [comment]
@Oxalin, the list of terminals is empty. Nothing to select.
