### ISSUE TITLE
theme system tray icon

### ISSUE THREAD

**Issue by DarkknightAK** [aarnt/octopi#156]
Hi,

would it be possible to theme the application icon in the system tray?

Octopi has a really interesting system to show the application icon. I add an octopi icon to kde/breeze icon set and in the app overview and the app panel the breeze icon was choose but I can't change the icon in the system tray in addition the system tray icon was used in the window decoration.

**Comment by varlesh** [comment]
+1

**Comment by Jacobtey** [comment]
+1

**Comment by aarnt** [comment]
Implemente in upstream.

**Comment by DarkknightAK** [comment]
how are the icon names for the system tray?

**Comment by aarnt** [comment]
Names do not matter. You have a dialog to choose your preferred icon.

**Comment by Jacobtey** [comment]
Dialog for tray icons choosing? Where?

**Comment by aarnt** [comment]
Upstream code for Octopi. I still have to put that in notifier.

**Comment by Jacobtey** [comment]
Great feature. Thanx!

**Comment by varlesh** [comment]
@aarnt custom **svg** icons not showing:
![image](https://user-images.githubusercontent.com/8083855/44301745-8ed54f00-a32d-11e8-83c4-dd6ff1cefbe1.png)

**Comment by aarnt** [comment]
Yes, this is a Qt bug.
