### ISSUE TITLE
[Feature request] GUI tweaks: Hotkey for install/remove, custom hotkeys & others

### ISSUE THREAD

**Issue by Zzooouhh** [aarnt/octopi#157]
I find it really annoying that there's no simple keyboard access to the install feature from Octopi; having to right click to select a package to install is very unintuitive and could be solved in a much more straightforward way. I'd propose (ideally context sensitive install/remove) having both the Enter key (while the package name is highlighted) and double clicking the package name do this, since right now neither action does anything and they seem like the most obvious choices.

Another hotkey that would be useful to have is to open/close the Groups list view; right now this seems impossible with keyboard only. Maybe a separate function key to control this, like F10/F12 for the other tabs?

A feature I'd welcome in general is being able to customize Octopi's hotkeys from within a GUI menu of some sort (Plasma hotkey integration maybe?).

There's a couple strange interface quirks that seem like design choices but act more distracting than helpful - upon selecting a group within the Groups list view, the focus is automatically switched into the package list; this can be annoying when trying to browse through multiple groups with the keyboard. Similar focus switching behavior happens within the Tab's view while Octopi is in the process of mirror-checking; it autoswitches to the Output tab with every new status update it lists. There might be similar behavior in other places too, but haven't come across it yet.

Lastly, maybe the Tab & Shift+Tab element switching behavior would be nice if streamlined a bit more; upon pressing one of the Alt+1/6 hotkeys, the amount of Tabs needed to return to the package or group list views seems to be inconsistent and as a heavy keyboard user I'd welcome a simple way to switch between the lists on the fly. I'm not sure whether this is something simply possible to adjust or a Qt limitation though.

**Comment by aarnt** [comment]
Most requests implemented in upstream.
Customization of hotkeys will not be implemented.
