### ISSUE TITLE
How ti use Octopi from behind a proxy

### ISSUE THREAD

**Issue by JoBilert** [aarnt/octopi#158]
Hi I try using octopi from behind a proxy. pacman works with the proxy-settings I added to my arch-linux. Octopi however doesn't seem to be able to get a connection to the repositories.

**Comment by neckrom** [comment]
I have a similar problem. I'm behind a proxy and all my systems are working, even the main window of octopi. I can sync, download, install remove packages (repos and AUR) with no problems. My issue is with octopi-notifier. It seems it can't sync databases behind a proxy. The icon remains transparent and never changes and the pacman db.lck file is never removed. I've to either remove it manually or open octopi and wait for the prompt to remove it.

I have to basically check updates manually.

**Comment by ArnaudDovi** [comment]
It is a shame this project doesn't even properly handle proxies. In all my softwares, octopi is the only one refusing proxy configurations and establishing direct connections.

When I see how fast @aarnt is to close tickets, I think it is not worth the effort to use this app anymore.

Get some coding skill.

**Comment by aarnt** [comment]
Lack of respect will not get us anywhere.
Let's be pragmatic here, please.
Reopening the issue.

**Comment by ArnaudDovi** [comment]
Great !

Apologize man, was in bad day and indeed my reply was stupid.

I confirm changes you made now brings working proxy support in Octopi Notifier but not in Octopi standalone (hitting refresh or new in Standalone still returns No internet available)

But better than before

Also I think you forgot a toString() 
--- src.orig/octopi/src/settingsmanager.cpp	2020-01-20 12:59:05.086171799 +0000
+++ src.new/octopi/src/settingsmanager.cpp	2020-01-20 13:00:43.142840999 +0000
@@ -463,7 +463,7 @@
 QString SettingsManager::getProxySettings()
 {
   SettingsManager p_instance;
-  return (p_instance.getSYSsettings()->value(ctn_KEY_PROXY_SETTINGS, ""));
+  return (p_instance.getSYSsettings()->value(ctn_KEY_PROXY_SETTINGS, "")).toString();
 }
`

**Comment by ArnaudDovi** [comment]
Great !

Apologize man, was in bad day and indeed my reply was stupid.

I confirm changes you made now brings working proxy support in Octopi Notifier but not in Octopi standalone (hitting refresh or new in Standalone still returns No internet available)

But better than before

Also I think you forgot a toString()

`
--- src.orig/octopi/src/settingsmanager.cpp	2020-01-20 12:59:05.086171799 +0000
+++ src.new/octopi/src/settingsmanager.cpp	2020-01-20 13:00:43.142840999 +0000
@@ -463,7 +463,7 @@
 QString SettingsManager::getProxySettings()
 {
   SettingsManager p_instance;
-  return (p_instance.getSYSsettings()->value(ctn_KEY_PROXY_SETTINGS, ""));
+  return (p_instance.getSYSsettings()->value(ctn_KEY_PROXY_SETTINGS, "")).toString();
 }
`

**Comment by ArnaudDovi** [comment]
Better after commit f67e3f27e8ba5221b51e1efae1564d737281ed2e

With internet checking disabled
Check for updates - Notifier - OK
Check for updates - Octopi - OK
Test of a real upgrade after notifier icon Red at startup - OK
Get latest distro news - Octopi - **KO** (Internet seem unavailable)

Have to test too if notifier receive update notification without application startup.

Thank you

**Comment by aarnt** [comment]
Ok, I'll take a look.

**Comment by aarnt** [comment]
@ArnaudDovi 
Any update on this issue?
