### ISSUE TITLE
Theme issue 

### ISSUE THREAD

**Issue by iAMsinister** [aarnt/octopi#160]
I'm having an odd issue with Octopi and my theme. I'm on Archbang using Menda-Dark theme. When i open octopi from the openbox menu or the application menu on xfce4-panel, Octopi is normal white/light themed. But when I open Octopi from the octopi-notifier in my systray it is correctly themed dark like the rest of my theme. Here is link to my forum post with screenshots..
http://bbs.archbang.org/viewtopic.php?id=5626

**Comment by aarnt** [comment]
Hi,
Indeed, this is a weird issue.
Maybe it could be generated by the notifier being compiled in Qt4. 
Which notifier are you using ? You can check it by clicking "About" in its popup menu.

**Comment by iAMsinister** [comment]
yes it is the QT5 compiled one. I edited the menu entry in my xfce4-panel Applications and added  "-style gtk" flag (without quotes) and it is called with the correct dark theme to match my DE. In the openbox right click menu its listed in a pipemenu, I'm learning pipemenus so i should be able to edit it adding that style flag. So i suppose this can be closed, thank you!
