### ISSUE TITLE
Octopi fails to update on Manjaro

### ISSUE THREAD

**Issue by TheAnalogKid** [aarnt/octopi#162]
I am using Manjaro 15.12 i686 with kernel version 4.1.15-1
This is a new installation.
The (red) Octopi icon says there are 532 updates available.
The updates download with error; however, the updates fail to install.
The following is the output that is generated:

:: Proceed with installation? [Y/n] Y 
(546/546) checking keys in keyring                   [############################] 100% downloading 
required keys... 
error: key "8DB9F8C18DF53602" could not be looked up remotely 
error: required key missing from keyring 
error: failed to commit transaction 
(unexpected error) Errors occurred, no packages were upgraded.  
Press any key to continue... 

_Note:  A copy of the complete text is attached.
[octopi update failure.pdf](https://github.com/aarnt/octopi/files/191282/octopi.update.failure.pdf)

_

**Comment by aarnt** [comment]
Hi,
This is not an octopi related bug. 
Try to do the following:

```
pacman -Sy archlinux-keyring manjaro-keyring
pacman -Syu
```

**Comment by TheAnalogKid** [comment]
Thank you!  This worked perfect.

**Comment by muhfaris** [comment]
thanks you
