### ISSUE TITLE
Octopi should notify user of failure to prepare transaction

### ISSUE THREAD

**Issue by polarathene** [aarnt/octopi#163]
I'm not entirely sure if this has anything to do with me switching from yaourt to pacaur. After the switch I thought I'd update my system(147 packages, Gnome 3.20), `System Upgrade` or clicking at the bottom dropdown `Install` option gives me a blank `Output` tab. Nothing happens.

In Pamac however, which I also switched to pacaur patched version, I get an error window when attempting the upgrade. `Failed to prepare transaction` Details:

```
could not satisfy dependencies:
light-locker-settings: requires python-gobject<3.20
lightdm-webkit2-greeter: requires webkit2gtk<2.12
lightdm-webkit2-greeter: requires gtk3<3.20
```

The actual packages aren't really an issue, the mirrors will be updated soon correcting that to allow the install. I just wanted to point out that Octopi did not provide the useful error information leaving me confused as to why it refused to update.

There is an issue [here](https://github.com/Antergos/antergos-packages/issues/94) if it helps provide more information.

**Comment by aarnt** [comment]
Fixed in upstream. Thanx.
