### ISSUE TITLE
Cannot view AUR in Octopi

### ISSUE THREAD

**Issue by zorbama** [aarnt/octopi#164]
When clicking the alien icon to view packages available in the AUR, the list is completely empty. Nothing comes up in a search. Installed AUR packages do not appear. No messages appear when running Octopi from the terminal. The AUR seems to be simply off-limits to Octopi for some reason, but I can't see what is wrong.

I am using Manjaro Linux 64-bit, KDE edition.

**Comment by aarnt** [comment]
Hi zorbama, you have to search and press ENTER.

**Comment by zorbama** [comment]
Oh, so that's how you do it? I guess since you don't have to press Enter to 
search in the repositories, I figured it just didn't find anything. I also 
didn't see anything about this anywhere.
At any rate, now I know. Thank you very much, and sorry about the non-issue. 
:)

**Comment by FadeMind** [comment]
@zorbama 
![screenshot_20160423_202132](https://cloud.githubusercontent.com/assets/9846948/14763270/0df32eda-0991-11e6-9e38-395b23f41f91.png)

![screenshot_20160423_202244](https://cloud.githubusercontent.com/assets/9846948/14763272/2a4278ca-0991-11e6-9a58-323c32c5495f.png)

and so on... 

just TYPE any word for searching and pres ENTER.
Minimum 2 mark.
