### ISSUE TITLE
[Feature request] Ability to show/modify 'Install Reason'

### ISSUE THREAD

**Issue by Grawp** [aarnt/octopi#165]
Show *Install Reason* (from pacman -Qii package) in Info tab.
Maybe also support for *pacman -D --asdep/--asexp* operations as well as *pacman -Qdtq* and *pacman -Qdttq* queries would be useful (for managing/removing unneeded / optionally unneeded packages).

**Comment by aarnt** [comment]
Added "Install Reason" field.

About those queries for unneeded packages, I find it safely to ignore.
