### ISSUE TITLE
Icon issue on dark plasma themes

### ISSUE THREAD

**Issue by ColinDuquesnoy** [aarnt/octopi#172]
Octopi doesn't look good when using a dark plasma theme (I am on KaOS with breeze dark):

![screenshot_20160622_083924](https://cloud.githubusercontent.com/assets/1681217/16256810/e87ff712-3854-11e6-899e-ada27a403d91.png)

What do you think about using icon from themes and the hardcoded ones as fallback? (http://doc.qt.io/qt-5/qicon.html#fromTheme, second overloaded method)

The icon theme probably won't have all the icons you need (especially the ones used int the package list view) but I think many could be "replaced".

I am willing to contribute and submit a PR if you think this is a good idea, just let me know ;)

**Comment by ColinDuquesnoy** [comment]
So I have been looking at your code and I see you're already using icon from theme but not on KaOS:

```c++
UnixCommand::getLinuxDistro() != ectn_KAOS
```

Any reason for forcing hardcoded icons on KaOS??

**Comment by aarnt** [comment]
Hi ColinDuquesnoy,
I opted to code that way because Anke (KaOS dev) created many icons for the project.

**Comment by ColinDuquesnoy** [comment]
> I opted to code that way because Anke (KaOS dev) created many icons for the project.

I see. But, since KaOS switched to [midna icons](https://github.com/KaOSx/midna), does it make sense to continue to use those hardcoded icons?

@demmm any thoughts on this?

To be clear the issue is not related to breeze dark, any dark theme will have the same issue (including kaos' midna dark theme).

**Comment by demmm** [comment]
There is a custom iconset created for KaOS (not in the Octopi git) and Midna (long before the 2 icon theme switches), this way it integrates perfectly with KaOS default theme settings.

Packaging it for dark themes will mean default look will degrade a ton.

**Comment by ColinDuquesnoy** [comment]
@demmm I don't agree. IMHO the custom icon set does not integrate perfectly with KaOS default theme settings. I find it a bit inconsistent with the new midna icons (e.g. some icons such as the terminal, folder, refresh are looking very different from the midna icons). 

So I made some tests: I replaced most of the hardcoded icons with icons from theme and IMHO it looks better for both the default theme and the dark themes. I haven't replaced ``commit.png``, ``fast_forward.png``, ``mirror-check.png``, ``toinstall.png`` and ``toremove.png`` because they are already looking great on dark themes and user are used to them.

Here are a few screenshots:

- Midna Light
  - **before**
![octopi-midna-light-before](https://cloud.githubusercontent.com/assets/1681217/16301908/71620c02-3948-11e6-8487-a1ff5468e589.png)
![octopi-midna-light-before2](https://cloud.githubusercontent.com/assets/1681217/16301909/7166ff00-3948-11e6-957f-a65d2755984b.png)
  - **after**
![octopi-midna-light-after](https://cloud.githubusercontent.com/assets/1681217/16302018/f61e3d44-3948-11e6-8641-3db89a389340.png)
![octopi-midna-light-after2](https://cloud.githubusercontent.com/assets/1681217/16302017/f61d75b2-3948-11e6-9b8d-cc3f9edfe1b9.png)
- midna dark
  - **before**
![octopi-midna-dark-before](https://cloud.githubusercontent.com/assets/1681217/16302027/0863c938-3949-11e6-8298-f3fe47f923a1.png)
![octopi-midna-dark-before2](https://cloud.githubusercontent.com/assets/1681217/16302026/08601b4e-3949-11e6-8b12-7435ea2d98ac.png)
  - **after**
![octopi-midna-dark-after](https://cloud.githubusercontent.com/assets/1681217/16302041/22e172ec-3949-11e6-8910-f1dfc3555cae.png)
![octopi-midna-dark-after2](https://cloud.githubusercontent.com/assets/1681217/16302040/22dc4088-3949-11e6-8428-cf830660e877.png)

@aarnt @demmm What do you think about those changes? I think they drastically improve the dark theme and don't degrade the light midna theme. If you like it, I'll submit a PR otherwise just let me know and I'll stop insisting...

**Comment by aarnt** [comment]
I liked it very much.

**Comment by ColinDuquesnoy** [comment]
@demmm Any feedback about the proposed changes?

**Comment by aarnt** [comment]
Skipping this one.
