### ISSUE TITLE
PKGs install/uninstall popup window unresizable

### ISSUE THREAD

**Issue by 0devnull0** [aarnt/octopi#175]
First I would  like to thank you guys for this fantastic tool.
When installing a pkg that has optional dependencies, a small window is opened to check/uncheck those pkgs. Problem here is the window size, it cannot be resized so you cannot read the whole description of the pkgs. The same occurs when uninstalling a pkg.
I would suggest to make that window resizable and remember its geometry like the main octopi window does. Many thanks in advance.

P.S Am not a native english speaker, so apologize for any mistakes and the like ;-)

![screenshot_20160805_211730](https://cloud.githubusercontent.com/assets/20864876/17448000/163979f6-5b52-11e6-98ff-c3faccfa8577.png)

**Comment by aarnt** [comment]
Implemented in upstream. Thanx for the suggestion!

**Comment by 0devnull0** [comment]
Wow thank you so much for the quick fix!
