### ISSUE TITLE
Synchronization intervall cannot be changed

### ISSUE THREAD

**Issue by DonHugo69** [aarnt/octopi#176]
The sync intervall in minutes cannot be changed to a different value than 1380.
![image](https://cloud.githubusercontent.com/assets/10484857/17458409/5ef09e50-5c0f-11e6-91de-5de030e4a26a.png)
After saving, the value simply jumps back to 1380.
![image](https://cloud.githubusercontent.com/assets/10484857/17458415/879e22e6-5c0f-11e6-89c4-ecb7f95ab935.png)

**Comment by aarnt** [comment]
Sorry about that! Fixed in upstream.
