### ISSUE TITLE
Make it clear for a user that a terminal is opened when octopi couldn't get closed

### ISSUE THREAD

**Issue by Pilzschaf** [aarnt/octopi#180]
When updating a package from pacman in the terminal and the user moves this terminal in the background and tries to close octopi  there is no feedback for the user that a terminal window is still opened and that octopi couldn't get closed in this state. Currently the close event in MainWindow::closeEvent at mainwindow_events.cpp just gets ignored when a terminal is opened in background. One possible solution would be to move the terminal window to the foreground when the user tries to close octopi. Another aproach would be to show the user a messagebox notifying him that a console windows is still opened in the background.

**Comment by Pilzschaf** [comment]
I already tested the second solution so it would be no problem for me to do a PR for this, but before I would like to know if you prefer the first solution more (but I am not sure how to get the terminal window into focus) and if I should do a PR for the second solution any suggestions on what exactly to tell the user in the message box?

**Comment by aarnt** [comment]
Hi Pilzschaf, You can PR a message box solution. Use StrConstants::getThereIsAPendingTransaction() for the message.
Thank you.
