### ISSUE TITLE
running konsole with normal user instead of root user

### ISSUE THREAD

**Issue by portaloffreedom** [aarnt/octopi#181]
I don't really enjoy running Xorg application with the root user, don't really trust Xorg in the first place.

Is it possible  to change the update on `konsole` from
`kdesudo konsole -e "pacman -Su"`
to
`konsole -e "kdesudo pacman -Su"`
since konsole doesn't really need root privileges in the first place

**Comment by devfull** [comment]
True, no need to run konsole/whatever GUI as privileged user.
> konsole -e "kdesudo pacman -Su"    
 
Or may be something like `konsole -e 'sh -c "sudo pacman -Su; echo Press Enter to quit; read" '`

**Comment by archderwelt** [comment]
One more problem here is apart from potential security issues, running konsole as root 'loads' the default theme for konsole. The window is small, font is very tiny/different, different color...it looks ugly.

**Comment by aarnt** [comment]
Upstream code uses just embeded qtermwidget. No more external tetminals supported!
