### ISSUE TITLE
FEATURE REQUEST: Showing AUR applications

### ISSUE THREAD

**Issue by jshand2015** [aarnt/octopi#183]
One feature i recently thought about is to actually have an entry within the view menu bar to display only the AUR applications you have installed on your system.

Please consider this as it would help searching for these applications easier

**Comment by Oxalin** [comment]
You can sort packages in octopi. You can sort them by their "state", which will bring installed AUR packages all together (up-to-date and outdated). You just need to click on the top of the first column in octopi (doing this on any column title will sort the listed values). Is it what you are looking for?

**Comment by jshand2015** [comment]
i tried to view only aur packages from the view menu under installed.  i used the name column to view aur packages, however it doesn't show them at all.  you still have to search for them right through the list.  in view there should be a new entry called AUR Packages

**Comment by Oxalin** [comment]
At the left of the "Name" column, you have another column showing the "state" of the packages. AUR packages are shown with an alien face (green means up-to-date, red are for outdated). At the top of that column, even if there is no column's name/title, you can still click there and sort packages by their "state". This should help you get all your AUR package at the top of the list.

Now, as you are suggesting, an option under "View" -> "Repository" could also be added (feature request). It would probably list all "outside" packages though (not provided by any repositories), which includes AUR, but could also include other manually installed packages.

**Comment by jshand2015** [comment]
oh i see what you're saying now.  i didnt realise that was a column.  all is working well.  no need to change it

**Comment by Oxalin** [comment]
Well, it's done. ;) I'm sending the pull request. If this is accepted, you'll find an AUR entry under View -> Repository.

**Comment by aarnt** [comment]
Thanks, Oxalin!
