### ISSUE TITLE
[KDE/Konsole] unable to install/upgrade AUR packages. 

### ISSUE THREAD

**Issue by 0devnull0** [aarnt/octopi#192]
On my plasma DE, installing/upgrading AUR packages not possible, because konsole doesn't open.
Steps to reproduce:
1- Open octopi window
2- Try to upgrade aur package if any are available.
3 Or search any package in aur and try to install.

Result: [Octopi output tab]
Runing command in terminal .... Command finished OK!

That was not OK! there was no terminal and nothing installed/upgraded.
I am not sure if this issue is related to octopi or to konsole. Can anyone reproduce?
Quote from #12 
["....Unfortunately konsole is not working fine with octopi in yaourt mode. So, I had to use xterm instead."]
is this still the case?
![screenshot_20160907_152744](https://cloud.githubusercontent.com/assets/20864876/18313608/d3752494-750f-11e6-9962-9227eb440295.png)

![screenshot_20160907_141049](https://cloud.githubusercontent.com/assets/20864876/18313452/2090b244-750f-11e6-9a78-4f92d81c3130.png)

**Comment by primesoftware** [comment]
Confirmed. I have the same issue.

**Comment by demmm** [comment]
This was a change in Konsole and is fixed in Octopi:
https://github.com/aarnt/octopi/commit/12c1295761170a2f089a853a6571a08f43b40c7c

**Comment by 0devnull0** [comment]
Ok thanks for the info. 
Up till now, the last version available in [AUR](https://aur.archlinux.org/packages/octopi) is 0.8.3-2 and
is not including (yet) that commit.
Feel free to close. Thanks

**Comment by romanlex** [comment]
How I make patch for current version in AUR?
