### ISSUE TITLE
Text in info tab is fixed size

### ISSUE THREAD

**Issue by olantrust** [aarnt/octopi#194]
In the 'info tab' the text is re-sizeable and follows the desktop sizing, except for the descriptive text below the title, and the URL (see attached image). Those two items are a fixed size.

This is problematic for users who have visual difficulties, or who are using hidpi / high resolution screens.

**Reproduction:**
Open Octopi
Select a package
Select 'Info' tab in the lower panel
Enlarge the text for that tab (using zoom or Ctrl+touchpad with two finger scroll up)

**Expected:**
All the text enlarges or reduces as one zooms.

**Actual:**
The text behaves as expected, except for the description and the URL.

**Example:**

![octopi-textsize-bug](https://cloud.githubusercontent.com/assets/627140/18542976/8a1aacee-7b25-11e6-8a33-bf7c3dfeb25b.png)

**Comment by aarnt** [comment]
Fixed on upstream.
