### ISSUE TITLE
Kde: Konsole dont start

### ISSUE THREAD

**Issue by ringo32** [aarnt/octopi#195]
hi,

also a mate complained about this.. only a downgrade works konsole again..
im using kde also now :) and yeah confirmed. dont know how to change the terminal in a gui so i changed  octopi.conf from automatic to xterm and it works from octopi and notifier ..

And yeah op root terminal works with xterm standard..
looks like bit seporate..

**Comment by imnofox** [comment]
I also have found Konsole doesn't work when installing packages from AUR.

Simply outputs
```
Running command in terminal...

Command finished OK!
```
without opening Konsole or doing anything. 

Works fine when I set it to use xterm or other terminals.

**Comment by demmm** [comment]
See https://github.com/aarnt/octopi/issues/192
https://github.com/aarnt/octopi/issues/192#issuecomment-245485081
