### ISSUE TITLE
Link all packages in the info tab

### ISSUE THREAD

**Issue by Larivact** [aarnt/octopi#196]
The information tab currently only links the `Depends On` packages.
`Required By`,  `Optional Deps`, `Optional For`, `Conflicts With` and `Replaces` packages currently aren't  linked. If all packages were linked it would allow you to easily browse through your packages.

**Comment by aarnt** [comment]
Implemented in upstream.

**Comment by Larivact** [comment]
I initially understood your comment as "Already implemented in upstream", I just noticed that you just fixed it ... wow that was fast! 👏
