### ISSUE TITLE
"QRegularExpression: No such file or directory" when trying to build octopi-notifier

### ISSUE THREAD

**Issue by Larivact** [aarnt/octopi#198]
I cloned the repo and tried to build the octopi package with `makepkg -f`.

```
../../src/package.cpp:36:30: fatal error: QRegularExpression: No such file or directory
 #include <QRegularExpression>
                              ^
compilation terminated.
make: *** [Makefile:526: ../build-octopi-notifier/package.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by aarnt** [comment]
You probably used qmake's qt4 version instead of qmake-qt5.

**Comment by Larivact** [comment]
@aarnt How come? I just used `makepkg -f` I didn't specify any qt version. The PKGBUILD file uses `qmake-qt4 octopi-notifier.pro`, I tried changing it to qmake-qt5 but that doesn't work either.
