### ISSUE TITLE
Notifications on startup missing

### ISSUE THREAD

**Issue by stovocor** [aarnt/octopi#200]
With earlier versions of octopi-notifier there was a notification upon startup. Now there is none and I sometimes miss updates because the tray is not always visible in Gnome Shell.

What do I have to do in order to reenable notifications? I am using octopi-notifier-qt5 0.8.3-2.

**Comment by aarnt** [comment]
If you set notifier to check daily, you should get your notifications as soon as you wait a few minutes after startup. The algorithm works.

**Comment by stovocor** [comment]
I did not change the algorithm, it is still set to daily. Perhaps the algorithm works, but displaying the notification is not.

**Comment by aarnt** [comment]
Manjaro has the bad habit of packaging dev versions as stable ones. So they created that 0.8.3 version which is not oficial as it hás never be released. Maybe You should try the upstream code. I'm sorry for your annoyance.

**Comment by stovocor** [comment]
I did not realize that because the AUR package is labeled as 0.8.3. Sorry for the confusion.
