### ISSUE TITLE
Wrong unit for download size in the upgrade confirmation window

### ISSUE THREAD

**Issue by Snudl** [aarnt/octopi#201]
Total download size on the first confirmation window seems to always pick the next smaller unit.

Example here: 414.74 KiB is actually 414.74 MiB
![screenshot_20161014_032802](https://cloud.githubusercontent.com/assets/1122131/19373161/3e4da83a-91c2-11e6-9b12-b3a9278b4379.png)
![screenshot_20161014_032912](https://cloud.githubusercontent.com/assets/1122131/19373163/4325e99e-91c2-11e6-8e5b-0d1131193ba7.png)

**Comment by aarnt** [comment]
This is from octopi-notifier, isn't it? It's fixed in upstream.

**Comment by Snudl** [comment]
Ah I see, thank you.
