### ISSUE TITLE
Systray icon does not turn red anymore

### ISSUE THREAD

**Issue by tsujan** [aarnt/octopi#203]
As the title says, it remains green when there are updates. I mean with the latest GitHub version.

**Comment by tsujan** [comment]
The problem is in https://github.com/aarnt/octopi/commit/13bb6b516a9607cc3aa08bd821dffa1981c6cc74. I reverted to the commit before it and the problem disappeared.

**Comment by demmm** [comment]
You can get the old behavior by using the old pacman backend.
Edit your ~/.config/octopi/octopi.conf and add (or edit the backend line):
```
backend=pacman
```

**Comment by tsujan** [comment]
It was already "Backend=pacman".

**Comment by aarnt** [comment]
It was an error, indeed. Try latest upstream.
