### ISSUE TITLE
Add option to disable animations in octopi-notifier

### ISSUE THREAD

**Issue by simgunz** [aarnt/octopi#206]
As you know KDE has a bug that causes high CPU when there are animation in the system tray, and even when the bug doesn't kick in it seems that there is a certain use of the CPU to keep the animation going.

https://bugs.kde.org/show_bug.cgi?id=356479

I wanted to ask if you can add an option to disable the animations in the notifier, in order to minimize the CPU usage under Plasma.

**Comment by aarnt** [comment]
I could disable animations, no doubt. But first I'd have to use them. Octopi does not use them.

**Comment by simgunz** [comment]
The octopi notifier icon in the system tray is pulsing when there is an
update available. That is the animation I'm referring to. Isn't
octopi-notifier part of your project?

**Comment by aarnt** [comment]
This is a Plasma issue. Build Octopi without plasma support (KSTATUS).

**Comment by demmm** [comment]
Just an FYI, your distro can fix this issue by applying this patch:
https://quickgit.kde.org/?p=plasma-workspace.git&a=commitdiff&h=749f60b89f4a166833fb64a5b593a801f63f9615
But again, not an Octopi issue, it is plasma-workspace that causes this

**Comment by aarnt** [comment]
Thanx demm.

**Comment by simgunz** [comment]
Thank you.
