### ISSUE TITLE
ALPM_BACKEND need to check for libalpm

### ISSUE THREAD

**Issue by abucodonosor** [aarnt/octopi#207]
we have no in octopi.pro : 

ALPM_BACKEND {
  QMAKE_CXXFLAGS += -std=c++11
  PKGCONFIG += glib-2.0
  LIBS += -lglib-2.0 -lalpm -lalpm_octopi_utils
} else {
  QMAKE_CXXFLAGS += -std=c++11
}

Libs are adding -lalpm without to check is even around.

Also not sure why the else exists since ALPM is now default. 

LIBS for glib2 and alpm should be pulled with pkgconfig so something like this may do it : 

http://ftp.frugalware.org/pub/other/people/crazy/octopi.pro.patch

**Comment by aarnt** [comment]
Thanx.
