### ISSUE TITLE
[Feature request] Show description and size in main list

### ISSUE THREAD

**Issue by herm** [aarnt/octopi#208]
It would be useful to have the package description shown in the main list. The description is usually short and would help when looking to a package to perform a certain task. 

Also it would be nice to have the package size in the list.

This information is already available to octopi so it should be easy to implement.

**Comment by aarnt** [comment]
Size column was added at upstream.
Description column will remain only at Info tab.

**Comment by herm** [comment]
Is there any reason not to show the description? If you don't like it to be always shown make it a configuration option.

**Comment by dufferzafar** [comment]
@aarnt You said "Size column was added at upstream."

But I can't find a way to get size column in the main list. Only have Name & Version.

My octopi version: 0.9.0-2 - Qt 5.11.1
