### ISSUE TITLE
[Feature Request] Cancelling/pausing updates

### ISSUE THREAD

**Issue by SuperQcid** [aarnt/octopi#209]
I was trying to quickly update my system while I was on a public WLAN. The download was going slower than expected so I figured I wanted to close Octopi and run the update later at home instead, however I was unable to cancel the download without killing Octopi. So I would like to request a feature that allows us to cancel update downloads or even pause them.

**Comment by aarnt** [comment]
Option to cancel is implemented in upstream. Pause, no way.
