### ISSUE TITLE
Tray icon isn't hided in auto mode when there aren't updates.

### ISSUE THREAD

**Issue by Jacobtey** [aarnt/octopi#211]
There was this feature in the past. Tray icon was visible in auto mode only if updates became.

**Comment by aarnt** [comment]
You have to check if your distro compiled it with plasma5 support (with KSTATUS define).

One thing I can assure you: Octopi code was not changed!

**Comment by Jacobtey** [comment]
It should be installed octopi-notifier-frameworks instead octopi-notifier-qt5 in Manjaro KDE.
