### ISSUE TITLE
[ALPM-BACKEND] - huge memory leak

### ISSUE THREAD

**Issue by scachemaille** [aarnt/octopi#213]
With octopi, octopi-notifier from master branch (I don't know about before as I never tried) on manjaro there is a huge memory leak on the notifier and also octopi. it doesn't happen when using pacman backend.
this happen each time i synchronize the database.
![screenshot_20161225_121010](https://cloud.githubusercontent.com/assets/16231972/21470863/31b2244a-ca9b-11e6-9487-991a6a400abb.png)

this with the last commit of octopi and alpm_octopi_utils

**Comment by aarnt** [comment]
Upstream code fixes that.
