### ISSUE TITLE
Octopi Auto Notifier

### ISSUE THREAD

**Issue by arthurflor** [aarnt/octopi#216]
Octopi works perfectly, but your notifications aren't automatically displayed on the KDE panel when there are updates.

![image](https://cloud.githubusercontent.com/assets/11759042/21890609/3b5ad0b2-d8ad-11e6-95d1-71281595036a.png)

I use Arch Linux
Kernel x86_64 Linux 4.8.13-1-ARCH
KDE 5.8.5
KDE Frameworks 5.29
Qt 5.7.1

**Comment by DrDoctor13** [comment]
What are your KDE Notification Area settings?

**Comment by arthurflor** [comment]
It is set "auto"

**Comment by aarnt** [comment]
Probably a Plasma issue.
