### ISSUE TITLE
Search bar characters messed up.

### ISSUE THREAD

**Issue by mbb78** [aarnt/octopi#222]
Hi!

Octopi's search bar displays squares instead of characters. There are two reports on the [Manjaro forum](https://forum.manjaro.org/t/octopi-search-box-font-display-is-messed-up-after-the-last-update/18100/2?u=mbb), both from users using KDE. This happened to me after updating from 0.8.6-1 to 0.8.7-1. Someone suggested changing the KDE font, but it had no effect. Downgrading the package to 0.8.6-1 solved it. I compiled and installed the git version myself, but the problem remains.

Any ideas of what might be causing this?

Thank you very much for taking the time to read this.

Cheers,

**Comment by philmmanjaro** [comment]
At Manjaro we use gitsnapshots we give a version. **v0.8.6** is actually c9cbafcf405b0add10f6953f8baa7ac664e75c93 and **v0.8.7** is e3576c31a3cc5e90311d3db29f28e858ab482554. So with in this range the regression got introduced.

**Comment by philmmanjaro** [comment]
Seems to be related to this https://github.com/aarnt/octopi/commit/53f06c03821e5f31cf545181e0153ef736a70924.

**Comment by mbb78** [comment]
Changing the term "sansserif" to "sans-serif" solves the issue. No Qt app can draw "sansserif" (GTK apps can). I don't know if this is a general issue or something particular about my system, as few users complained about this. I'm still trying to fully understand why "sansserif" is wrongly interpreted.

**Comment by philmmanjaro** [comment]
If you use for example **Calamares** it uses "Sans Serif" as font family. Maybe changing it is the way to go here.

**Comment by mbb78** [comment]
I confirm "Sans Serif" works.

**Comment by mbb78** [comment]
The culprit is the font "SansSerif" from Microsoft. Blacklisting it makes the original term "sansserif" work. I don't know why Qt is unable to draw it.
