### ISSUE TITLE
[Feature request] Batch updating AUR

### ISSUE THREAD

**Issue by PMunch** [aarnt/octopi#223]
Currently when updating from AUR it goes ahead and runs the entire thing as if I were to do it from a terminal window. However updating from AUR can be a quite manual task, you have to answer questions and authenticate yourself at various steps throughout the process. It would be nice if Octopi were able to take your answers before updating and then update the packages individually with your pre-determined answers. If you had some that would require manual intervention, for example to change a PKGBUILD, these should be updated first.

This would allow the user to batch update packages from AUR for packages they know are safe but still keep an eye on those that might not be.

**Comment by aarnt** [comment]
Adding the user to sudoers and using Octopi AUR parameters "--noedit" and "--noconfirm" can be used now (upstream code).

**Comment by PMunch** [comment]
I was more thinking of a graphical solution where you would be able to select the packages to automatically apply the noedit and noconfirm flag to, then run the others first with manual intervention before batch updating the rest.
