### ISSUE TITLE
Octopi cannot update, hangs at terminal

### ISSUE THREAD

**Issue by j00ch** [aarnt/octopi#226]
I'm having this problem for a few months now when i try to update the system with Octopi, it hangs at the terminal window:

![schermafdruk van 2017-03-16 19-17-17](https://cloud.githubusercontent.com/assets/16567658/24023967/1638570c-0ab0-11e7-8c1d-f8fb8952b8cd.png)

Nothing happens, running Manjaro with Openbox.

**Comment by j00ch** [comment]
I changed the terminal to xterm and then it works again so seems like lxterminal won't play with octopi, any ideas? How is the command parsed to the terminal?

**Comment by aarnt** [comment]
@j00ch Do you still have this problem?

**Comment by j00ch** [comment]
@aarnt Yup, just tried again today. Cleared all user data and tried on my other system too. Same result with the addition of extra instances of the terminal spawning every 30 seconds or so.

**Comment by aarnt** [comment]
Only qtermwidget is supported now in upstream code.
