### ISSUE TITLE
Icons in find box not visible in KDE with dark themes+light icons

### ISSUE THREAD

**Issue by pmargeti34** [aarnt/octopi#229]
In searchlineedit.cpp there are some hardcoded RGB color values for find bar. If octopi is used under KDE and user has set a dark color scheme with light icons (e.g. Breeze Dark), then the magnifier icon and delete text icon that appear under find are white/light gray and displayed on a white/light yellow background. This combination is low contrast and makes icons invisible.

Expected result: icons in find bar are visible when user has a dark color scheme in KDE

Proposal: read and use colors from active KDE color scheme instead of hardcoded RGB values

**Comment by aarnt** [comment]
Removed hardcoded while in kde in upstream code.
