### ISSUE TITLE
AUR: Show details  about not installed package(s)  under Info Tab

### ISSUE THREAD

**Issue by devwatchdog** [aarnt/octopi#230]
Currently, only package(s) description and version are shown for packages from AUR.  I  would like to see the details for AUR also, this would help to decide if am going to install a certain package or not depending on its dependencies/licence etc . [Pacaur](https://github.com/rmarquis/pacaur) for example can show the details `pacaur -i [--info] packageName`.

**Comment by aarnt** [comment]
Added a couple more important fields in the upstream code.
