### ISSUE TITLE
Octopi lets you update packages when /tmp is full, potentially bricking your system

### ISSUE THREAD

**Issue by Pointedstick** [aarnt/octopi#231]
I got a notification that there were some packages that needed updating, so I opened Octopi and let it update them. To my horror, the output tab started filling up with "out of space" messages, but the packages didn't stop trying to install or revert to a safe state. Out of morbid curiosity, I rebooted and was confronted with an unbootable system--apparently the postinstall processes that regenerate the initramfs had died. Bummer.

Octopi shouldn't let you update packages if /tmp is full or below some large safe threshold. Or better yet, it could even clear out some space itself.

**Comment by aarnt** [comment]
Octopi is only a pacman frontend. Period.

If pacman enables you to do that, Octopi should not prevent you.
