### ISSUE TITLE
Can't replace a package in a main repo with a package in AUR

### ISSUE THREAD

**Issue by Pointedstick** [aarnt/octopi#232]
I have the libinput package installed, from a main repo. I want to replace it with the package libinput-no-hysteresis, which lives in AUR.

If I try to install libinput-no-hysteresis from AUR first, it (rightly) complains that it conflicts with the vanilla libinput. If I try to remove libinput first, Octopi tries to remove 291 dependencies--many of them critical system packages--and if I de-select all of them, it won't let me remove libinput because the dependencies aren't satisfied.

**Comment by demmm** [comment]
That is an issue with the PKGBUILD, not Octopi.  If libinput-no-hysteresis is a drop in replacement, then it should be reflected in the PKGBUILD with proper conflicts, provides and replaces lines.

**Comment by Pointedstick** [comment]
Thanks for the tip! Looks like it just needs a "replaces" line. I commented in https://aur.archlinux.org/packages/libinput-no-hysteresis/ and I'll close this now.
