### ISSUE TITLE
Octopi claiming updates to AUR

### ISSUE THREAD

**Issue by afettouhi** [aarnt/octopi#233]
Ever since I updated to KDe Plasma 5.9.x octopi reports that are the samme amount updates in AUR as in the normal Arch Linux repos. Meaning that if there are 5 packages to be updated from the for example [core], [community] or [extra] repos octopi will show that there also 5 packes in the AUR that need to be updated. Once the normal packages have updated the claimed updated for AUR disappear. I have tried to rebuild octopi but that doesn't fix it.

**Comment by aarnt** [comment]
Seems fixed in upstream code.
