### ISSUE TITLE
No outdated AUR packages detected

### ISSUE THREAD

**Issue by flying-sheep** [aarnt/octopi#235]
Neither the notifier nor octopi show that/which AUR packages are outdated. (git master, just updated)

**Comment by aarnt** [comment]
Can you output the result of "yaourt -Qua" (or "pacaur -Qua") ?

**Comment by flying-sheep** [comment]
![grafik](https://cloud.githubusercontent.com/assets/291575/25754915/3f178a98-31c1-11e7-9a4d-70d9ff446738.png)

in text:

```console
$ pacaur -Qua
:: aur  gitkraken  2.4.0-3  ->  2.5.0-1
```

**Comment by aarnt** [comment]
Ok, thanx for the information.

**Comment by aarnt** [comment]
Can you try again with latest commit?

**Comment by flying-sheep** [comment]
works in octopi, but the notifier still has a green octopus.

**Comment by txe** [comment]
FYI, if you don't want to wait the fix, you can choose pacaur instead of yaourt in Octopi's options.
