### ISSUE TITLE
Octopti show outdated packages in KCP as newer one

### ISSUE THREAD

**Issue by ShalokShalom** [aarnt/octopi#239]
![screenshot_20170617_105956](https://user-images.githubusercontent.com/6344099/27251836-465c3258-5350-11e7-978d-1117fecd6053.png)

**Comment by demmm** [comment]
This is not a bug, but a design of kcp (not Octopi code).
kcp is not intended as a package manager.
The code shows you have a **different local** version from what is in KCP, no difference if local is older or newer, it is up to you to decide if you want to flag KCP as outdated, stay with version as is in KCP or ignore and stay with local version.

@aarnt please close, this is not an Octopi issue.
