### ISSUE TITLE
Add support for Netrunner Rolling distro news feed

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#241]
Link to website - http://www.netrunner.com/netrunner-rolling-2017-07-released/

References - https://github.com/netrunner-rolling/QA/issues/44

Needs discussion/collaboration.

**Comment by aarnt** [comment]
@notuxius, NetRunner Rolling would need an RSS news feed like this one: https://manjaro.org/feed/

Octopi does not use an HTML engine to display advanced Web content.
