### ISSUE TITLE
[Suggestion] Always launch Octopi after left click on tray icon

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#242]
Topic: right now left click on tray icon shows (and hides) Octopi window only if it was launched before - by right click on tray icon -> 'Octopi...' menu entry (or from any other place).

Suggestion: show (and hide) Octopi window after click on tray icon - either if it was launched before or not.

Version: Octopi Notifier - 0.8.8.5 (Qt 5.9.0)

**Comment by aarnt** [comment]
Done.
