### ISSUE TITLE
[Suggestion] Middle click on tray icon can either sync database or if updates are present - launch Octopi with update terminal window opened

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#243]
Or 'Confirmation' window could be launched if there are updates - or 'Output' tab with 'There are ... outdated packages in your system:' text could be opened

**Comment by notuxius** [comment]
Or update 'Confirmation' window could be launched, or 'Output' tab could be opened

**Comment by aarnt** [comment]
Skipping that one.
