### ISSUE TITLE
Strange output after refusing/canceling password prompt upon installing packages

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#244]
Installing selected packages...

Usage: /usr/bin/
Runs a program with elevated privileges.
Options:
-c Specifies the command to run as one string
-f Run command under target uid if is not
writable
-u Specifies the target uid
-n Do not keep password
-s Stop the daemon (forgets all passwords)
-t Enable terminal output (no password keeping)
-p Set priority value: 0 -r Use realtime scheduling
--noignorebutton Do not display ignore button
-i Specify icon to use in the password dialog
-d Do not show the command to be run in the dialog
--attach Makes the dialog transient for an X app specified
by winid
--embed Embed into a window
-h, --help Displays this help.
-v, --version Displays version information.
--author Show author information.
--license Show license information.
--desktopfile The base file name of the desktop entry for this
application.
Arguments:
command Specifies the command to run as separate arguments

Command finished with errors!

**Comment by aarnt** [comment]
Upstream code uses octopi-sudo for asking passwords.
