### ISSUE TITLE
[Suggestion] Create a button for toggling visability of frame with tabs

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#245]
Currently when frame with 'Info', 'Files', 'Transition'... tabs is pulled down to the bottom border - frame with tabs disappears. And it can be tricky especially for beginner users (significant part of target audience) to found it/pull it up. 

My slight UX suggestion is to create a button some near text with number of packages at the bottom status bar - for revealing/hiding frame with tabs - same as 'Groups (F9)' button for hiding/showing frame with groups.

**Comment by aarnt** [comment]
F10 and F11 do the trick.
