### ISSUE TITLE
[Suggestion] Automatically sync database after changing repotories settings in Repository Editor

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#246]
Start syncing database immediately after closing of repo editor - if something was changed and saved.

Without syncing - next output could confuse beginners - "warning: database file for 'newly-enabled-database-name' does not exist error: failed to prepare transaction (could not find database)" - assumed/predicted newcomer question - why it not exists if i just enabled it?

Or '(Close and) Sync database' button can be added into 'Success Repositories configuration successfully saved.' dialog - alongside with 'OK' button.

**Comment by notuxius** [comment]
Or 'Sync database' button can be added into 'Success Repositories configuration successfully saved.' dialog - alongside with 'OK' button.

**Comment by aarnt** [comment]
I'll skip that one.
