### ISSUE TITLE
[Suggestion] Don't clear existing text in 'Find' field after searching with regular search and enabling AUR search mode after that

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#252]
The case is - if you searched for some package in regular search mode and you enabled AUR search mode after that - then with high probability - you don't found it in binary repos and you will try to search for it in AUR - so it's UXtly (good for UX/UX friendly - just invented the word) better to prefill previously entered text in 'Find' field - so that you don't have to enter the same text again.

It also can be applied for changing of search type (by name, desc, file).

**Comment by dufferzafar** [comment]
This issue can be closed as this has been fixed.
