### ISSUE TITLE
'Command finished OK!' message in 'Output' tab even after termination of unfinished update process in terminal

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#254]
Possible solution - instead of 'Command finished OK!' text message display 'Terminal command was canceled'. 

Also if there is update and you select 'System upgrade' and then 'Run in terminal' in 'Confirmation' window and after entering password you cancel terminal command with Ctrl+C key combination and press any key for terminal to disappear - after some time you will see update 'Confirmation' window again - in infinite loop.

For infinite update 'Confirmation' window appearing you can also press 'Run it terminal' - enter password and just close terminal window.

Or - while in terminal - you can press Ctrl+C combination not once but twice - you will see 'Warning: Program 'bash' crashed.' error message in red color in terminal - but after closing this terminal - 'Command finished OK!' message in 'Output' tab and infinite 'Confirmation' window appearing.

**Comment by aarnt** [comment]
Upstream code support only embedded qtermwidget. No more external tetminal errors!
