### ISSUE TITLE
Slightly deceptive text upon rejecting of overwriting backup file in Repository Editor

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#259]
After rejecting of 'Backup file already exists. Do you want to overwrite it?' dialog - another window with text 'Backup error Can't create backup file...' pop-ups - which is partly misleading - program not unable to create the backup file - the user rejects creating of new one.

Instead text in message could be something like - 'Creation of new backup file canceled Do you want to proceed with old backup file?'

Or features from #255 issue could be applied for this one.

**Comment by aarnt** [comment]
backup files names use date/time now.
