### ISSUE TITLE
Empty popup error window in Cache Cleaner after rejecting of password input

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#260]
Prerequisite:
Cached installed or uninstalled packages.

Steps to reproduce:
1. Open Cache Cleaner.
2. Press (any) 'Clean' button.
3. Reject password input.

Expected result:
Focus gets back to Cache Cleaner, 'Refresh' and 'Clean' buttons become enabled.

Actual result:
Empty popup error window appears.

Screenshot with empty error message:
![empty-message-window-no-pass-entered-cache-cleaner-octopi](https://user-images.githubusercontent.com/2657014/28932934-e9153852-7883-11e7-8985-a2714af5676c.png)

**Comment by aarnt** [comment]
@bwendell  Still persist with upstream code? I cannot reproduce here in KaOS/plasma5.

**Comment by bwendell** [comment]
@aarnt Yes. I am still seeing it with antergos/plasma5 (version 0.8.1-2).

**Comment by aarnt** [comment]
@bwendell  
Ok, but I meant with latest git code.

**Comment by bwendell** [comment]
@aarnt I don't see it in upsteam code.

**Comment by aarnt** [comment]
@bwendell 
https://github.com/aarnt/octopi/tree/master/cachecleaner
Cache cleaner is a project inside octopi dir.
