### ISSUE TITLE
[Suggestion] Add feature for performing automatic upgrades

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#266]
At certain dates and time, with option for rebooting to apply upgrades. 

Similarly to 'Update Manager' in TrueOS:
![trueos-update-manager](https://user-images.githubusercontent.com/2657014/28934858-27e9d914-788b-11e7-818d-1290191156a9.png)

Or there can be an option for auto downloading updates and installing them with user confirmation. Octopi can download updates - change icon - and after click on it - display update 'Confirmation' window.

**Comment by aarnt** [comment]
Won't be done.

**Comment by claell** [comment]
Auto upgrade is the default way Windows does updates. To me this is pretty convenient.

Can you explain why this won't be integrated?
