### ISSUE TITLE
[Suggestion] Develop Firefox/Chromium/QupZilla addons

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#270]
Add 'Install with Octopi' button into AUR/KCP/CCR websites. After clicking on it - Octopi could start with ready to install terminal window (with 'Edit PKGBUILD ? [Y/n] ("A" to abort)') text. Or 'Search with Octopi' button for just searching in Octopi.

Discuss/collaborate with KaOS, Chakra, Manjaro devs.

I think it would be handy/popular. Addon could detect distro - Arch (Manjaro, Netrunner Rolling) or KaOS or Chakra - and display button on corresponding pages only - AUR or KCP or CCR:
![integrate-octopi-into-firefox](https://user-images.githubusercontent.com/2657014/29000877-5cc45f12-7a82-11e7-9548-fa15e5546ea1.png)
![integrate-octopi-into-firefox-ccr](https://user-images.githubusercontent.com/2657014/29000875-5cb7f790-7a82-11e7-9bcc-95603b6b7148.png)
![integrate-octopi-into-firefox-kcp](https://user-images.githubusercontent.com/2657014/29000876-5cbe9c4e-7a82-11e7-9d30-6c3876f61f5d.png)

**Comment by aarnt** [comment]
Won't be done.
