### ISSUE TITLE
[Suggestion] Modify 'Contents of "packagename"' row/line in 'Files' tab

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#274]
There is a lot of space in 'Files' tab in 'Contents of "packagename"' row/line. Some buttons can be added to this row/line - like 'Open directory' button (to the left side of contents text) and 'Find a file' button (to the right side of contents text). Or 'Find a file' widget could be directly integrated into 'Contents' row/line.

**Comment by aarnt** [comment]
This is how this specific widget is drawed in Qt.
