### ISSUE TITLE
Unclear messages in 'Output' tab if pacman.conf file is not reachable

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#282]
Error text upon first sync attempt:
"""
Synchronizing databases...

QXcbConnection: is up to date
Command finished with errors!
"""

Error text upon second syncing attempt:
"""
Synchronizing databases...

Command finished with errors!
"""

if there some issues with configuration file - error in 'Output' tab could something like - 'Pacman configuration (/etc/pacman.conf) file is unreachable'.

**Comment by bwendell** [comment]
@notuxius I'm not seeing what you're seeing. It seems this has been fixed.  Here's what I see:

Synchronizing databases...

error: config file /etc/pacman.conf could not be read: No such file or directory 
error: failed to open /etc/pacman.conf: No such file or directory 

Command finished with errors!

**Comment by notuxius** [comment]
@bwendell - currently i'm seeings the output mentioned by you in git version of the Octopi - 0.9.0 (dev) (Qt 5.10.0) - and the following output in Octopi 0.8.10-3 (Qt 5.10.0): 

Synchronizing databases...
error: config file /etc/pacman.conf could not be read: No such file or directory 
Command finished with errors!
