### ISSUE TITLE
[Suggestion] 'Groups' list can be expanded vertically and occupy part of bottom 'Tabs view' space

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#284]
For faster searching for groups with increased vertical field of view and with availability of additional info in 'Tabs view'. 
There is enough space for tabs in 'Tabs view' even in most narrower size of app window.
![expand-groups-vertically](https://user-images.githubusercontent.com/2657014/29001230-2468bafa-7a8c-11e7-9e83-90bae98f57ac.png)
![expand-groups-vertically-narrow](https://user-images.githubusercontent.com/2657014/29001231-280e4f80-7a8c-11e7-887e-6ec492755c0b.png)

**Comment by aarnt** [comment]
Implemented in upstream.
