### ISSUE TITLE
[Suggestion] UI tweaks for better UX

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#288]
Disable 'Files' tab is package is not installed or display info message about possibility of viewing files of installed packages only.

Disable 'Transaction' tab if there are no pending Transactions.

Show progress bar at the bottom status bar for all lengthy (> 0.5sec) operations immediately - not after delay. For example - switching AUR/non-AUR modes operation, etc.

On right click on installed package - display 'Reinstall' menu text instead of 'Install'.

On right click on outdated package - display 'Update' menu text instead of 'Install'.

**Comment by aarnt** [comment]
Partially implemented.
