### ISSUE TITLE
[Suggestion] Disable more UI parts upon database sync

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#293]
Disable search filed and all tabs upon database sync - it's hard to use interface when database is syncing - if you switch to 'Info' tab - Output tab gets focus on every update in that tab. Also previously entered text in search field resets after sync finishes.

There also can be other solutions - like remember previously enter text in search field after sync is finished and do not focus 'Output' tab upon syncing - for ease of reading info for selected package.

**Comment by aarnt** [comment]
Partial implemented: tab switching still possible.
