### ISSUE TITLE
[Suggestion ]'Enter' key and/or 'Tab' key enhancements for better UX when searching

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#294]
1. Press 'Ctrl+L' or click on 'Find (Ctrl+L)' field.
2. Enter some not installed package name - for example '0ad'.
3. Pressing 'Enter' can stage this package into 'Transition' tab - now it's doing nothing.

1. Press 'Ctrl+L' or click on 'Find (Ctrl+L)' field.
2. Enter some not installed package name - for example '0ad'.
3. Pressing 'Tab' can select '0ad' package in packages list - now pressing 'Tab' key selects clear field button.

**Comment by aarnt** [comment]
Partial implemented in upstream code.
You need to press ENTER on top of a selected package to send it to the Action list.
