### ISSUE TITLE
Options menu is missing

### ISSUE THREAD

**Issue by dimqua** [aarnt/octopi#299]
![](https://i.imgur.com/Ae7QJmS.png)

As you can see,  I don't have Options menu. Can you please tell me how can I fix this?

**Comment by aarnt** [comment]
Which Octopi version? Which distribution?
Options menu is an upstream feature. Not released as stable yet.

**Comment by dimqua** [comment]
Octopi 0.8.5, Arch Linux.

**Comment by aarnt** [comment]
Ok, I think this version does not use Options menu. So, no bug to fix.
