### ISSUE TITLE
[Octopi-notifier] Sync databse option stopped working for pacman repo updates

### ISSUE THREAD

**Issue by Vincent43** [aarnt/octopi#306]
For some reason octopi-notifier stopped syncing pacman repos database when I chose "Sync database" option from tray icon menu (one which doesn't need password) and automatically for chosen interval. I checked that it only invokes `/usr/bin/pacman -Qu` command which doesn't sync repos. Refreshing AUR through pacaur works ok.

Choosing "Sync database" from main octopi toolbar (which needs password) works correctly.

I'm using Archlinux and there were updates to Qt 5.10 and KDE Frameworks 5.41 recently. I rebuilded octopi against them so maybe that's the reason.

**Comment by aarnt** [comment]
Hi @Vincent43 ,
Can you run "octopi-notifier -d" in a terminal and post the results?

**Comment by Vincent43** [comment]
Below is output of `octopi-notifier -d` while I tried to sync repos twice (my system was updated but octopi didn't check this as it run `/usr/bin/pacman -Qu` command only.
```
$ octopi-notifier -d
"Octopi Notifier - 0.9.0 (dev) (Qt 5.10.0)"
org.kde.knotifications: service is "org.kde.StatusNotifierItem-2444-1"
org.kde.knotifications: Registering a client interface to the KStatusNotifierWatcher
At refreshAppIcon()...
Got a GREEN icon!
SyncDb is scheduled once every  60  minutes.
22:59 : At syncDatabase()...
At afterPacmanHelperSyncDatabase()...
At refreshAppIcon()...
Got a GREEN icon!
23:00 : At syncDatabase()...
At afterPacmanHelperSyncDatabase()...
At refreshAppIcon()...
Got a GREEN icon!

```

**Comment by Swipe650** [comment]
Same problem here

**Comment by losbehamos** [comment]
I have the same problem with octopi-notifier. I tried the octopi and the octopi-git package from the aur with the same result.

**Comment by aarnt** [comment]
All of you are Arch Linux users having trouble?

**Comment by Swipe650** [comment]
I have arch and another PC on Antergos and sync database executed from the octopi-notifier system tray icon is not working on either.

**Comment by aarnt** [comment]
Ok, let me test if it's an Arch related issue or if it happens in KaOS too.

**Comment by bits-fritz** [comment]
same Problem here,
and yes: Running Archlinux octopi-notifier-noknotify-0.8.1 with xfce4

**Comment by yumyumbluesun** [comment]
I am also having this problem on Manjaro with Plasma.

**Comment by demmm** [comment]
In case still needed, issue is also present on KaOS.  Output of `octopi-notifier -d` while there is an update available.  When the output shows `red icon`, a ` pacman -Syu` was run manually.
```
22:30 : At syncDatabase()...
Synchronizing kcp database...
At afterPacmanHelperSyncDatabase()...
At refreshAppIcon()...
Got a GREEN icon!
SyncDb is scheduled once every  30  minutes.
SyncDb is scheduled once every  30  minutes.
SyncDb is scheduled once every  30  minutes.
SyncDb is scheduled once every  30  minutes.
SyncDb is scheduled once every  30  minutes.
SyncDb is scheduled once every  30  minutes.
23:05 : At syncDatabase()...
Synchronizing kcp database...
At afterPacmanHelperSyncDatabase()...
At refreshAppIcon()...
Got a GREEN icon!
SyncDb is scheduled once every  30  minutes.
At refreshAppIcon()...
Got a RED icon!
At refreshAppIcon()...
Got a RED icon!
At refreshAppIcon()...
Got a GREEN icon!
```

**Comment by Jacobtey** [comment]
same problem here. manjaro.

**Comment by Kharag** [comment]
Just commenting to say I am affected by this as well.

**Comment by stovocor** [comment]
> Just commenting to say I am affected by this as well.

Why?

We have enough people already with the same problem (yes, me too). But all those "I am also affected" posts without any further information only result in spam for people who subscribed to this thread.

**Comment by Jacobtey** [comment]
> We have enough people already with the same problem (yes, me too). But all those "I am also affected" posts without any further information only result in spam for people who subscribed to this thread.

What further information is needed? What quantity of feedbacks is enough?

**Comment by aarnt** [comment]
Ok guys, thanks for the comments. I do not know why is it happening. It'll be fixed as soon as we figure It out.

**Comment by losbehamos** [comment]
I was able to get the Sync database working again by downgrading all qt 5.10 packages to 5.9.3. and rebuilt the whole octopi package again.

**Comment by mynever** [comment]
same here, manjaro stable with latest updates.

**Comment by aarnt** [comment]
Bug apparently fixed here. Will keep it opened until another positive result.
Commit with fix: https://github.com/aarnt/octopi/commit/52e111f5ab53b5b60ac06ca1cd47c70e0aced435

**Comment by losbehamos** [comment]
Thank you aarnt in my case it is fixed.
