### ISSUE TITLE
Link to a packages AUR page

### ISSUE THREAD

**Issue by eboracus** [aarnt/octopi#310]
For packages in the AUR, it would be really useful if there would be a link to the AUR page for that package (at https://aur.archlinux.org/packages/) in the `info` section. There is of course already the URL entry in that section often pointing to a packages own dedicated URL or similar, but it is often desirable/more important to see the AUR related information about a package (particularly if what a package actually does is already known). Could I suggest another link _in addition_ to as a universal entry in the `info` panel for all AUR packages linking to its associated page, possibly therefore the first entry or even the package name in the panel acting as this link?

**Comment by aarnt** [comment]
Added as the pkg name in upstream.
