### ISSUE TITLE
Pacaur not longer maintained

### ISSUE THREAD

**Issue by sueridgepipe** [aarnt/octopi#311]
Probably should remove this as an Octopi AUR helper in options.

Replace with yay?

**Comment by polarathene** [comment]
[Pikaur](https://github.com/actionless/pikaur) is apparently looking promising with active development.

Relevant reddit discussion on r/archlinux [here](https://www.reddit.com/r/archlinux/comments/81fcbp/thoughts_on_pikaur/).

**Comment by aarnt** [comment]
Added Trizen support upstream.
