### ISSUE TITLE
Alternative AUR helper: trizen

### ISSUE THREAD

**Issue by Skycoder42** [aarnt/octopi#312]
Yes, there are many requests for aur helpers to be added, but there is a reason I think [trizen](https://github.com/trizen/trizen) would be a good addition:

Trizen is an aur helper tool which is very similar to pacaur (Which is not maintained anymore, see #311 ). It has almost the same command syntax as pacaur, thus it would be easy to integrate into octopi as another aur helper. It seems to be rather popular with former pacaur users, too (Got that impression from https://www.reddit.com/r/archlinux/comments/7k5suz/pacaur_now_unmaintained/). 

As far as I understand, the only thing that could prevent this is the missing option to list updated aur packages only (See https://github.com/trizen/trizen/issues/103).

Any thoughts on this?

**Comment by aarnt** [comment]
"Qua" option should be no problem. Currently Octopi parses only AUR results.

**Comment by Vincent43** [comment]
yay has no dependencies: https://github.com/Jguer/yay

**Comment by mbloms** [comment]
I was just going to suggest this.

**Comment by polarathene** [comment]
[Pikaur](https://github.com/actionless/pikaur) is apparently looking promising with active development.

Relevant reddit discussion on r/archlinux [here](https://www.reddit.com/r/archlinux/comments/81fcbp/thoughts_on_pikaur/).

**Comment by michaldybczak** [comment]
Is there any info which AUR helpers are currently supported by octopi? I know that yaourt and pacaur are but what about others?
I installed aurman and saw that's not an option in octopi. I tried googling what are the supported ones but I found only this topic here.

**Comment by Vincent43** [comment]
> Or maybe yaourt and pacaur are the only ones so far?

That's true.

**Comment by polarathene** [comment]
Does it require much to support another? pacaur is no longer maintained, it has some nice benefits over yaourt, so supporting another helper with the same/similar benefits would be good.

**Comment by aarnt** [comment]
It'll be added! I just need to have time to code.

**Comment by aarnt** [comment]
Added Trizen support in upstream.
