### ISSUE TITLE
2 rows not translated in octopi-notifier-qt5's options

### ISSUE THREAD

**Issue by NerosTie** [aarnt/octopi#318]
In octopi-notifier-qt5's options there are 2 rows which are not translated in the first tab (everywhere it's ok)

![screenshot_20180224_103400](https://user-images.githubusercontent.com/4572452/36628833-47316134-194e-11e8-92a7-d675dc19521d.png)

**Comment by aarnt** [comment]
Translation issues are fixed at Transifex platform.
Probably your language is not 100% translated.

https://www.transifex.com/arnt/octopi/

**Comment by NerosTie** [comment]
It's French, it should be translated.

**Comment by aarnt** [comment]
Ok, will test then.

**Comment by aarnt** [comment]
The problem is Octopi has more than one french translation. The file "fr" is the most updated. Probably you are using fr_FR, which is not 100% done. 
So, when all transifex French languages get done, this issue will be fixed.
