### ISSUE TITLE
Add support for yay

### ISSUE THREAD

**Issue by notuxius** [aarnt/octopi#323]
It's actively developed, has batch interaction - just like pacuar and can import PGP keys
https://github.com/Jguer/yay

**Comment by aarnt** [comment]
Implemented in upstream.

**Comment by candrapersada** [comment]
Yay for Manjaro KDE

**Comment by aarnt** [comment]
Yay support is implemented in upstream. You can try testing 0.10.0 version.

**Comment by candrapersada** [comment]
yay for enable KDE Manjaro aur from octopi
![image](https://user-images.githubusercontent.com/36833664/60662946-0057b680-9e88-11e9-9a20-9d840e29ec05.png)

**Comment by aarnt** [comment]
@candrapersada ,
This is not 0.10.0 development version.
You can try to download PKGBUILD from this site and "makepkg -f" it.
