### ISSUE TITLE
Octopi Settings window does not show up at front desktop

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#325]
@aarnt  Hi. Octopi Settings window does not show up at front desktop, only task manager icon is visible **IF** GTK app is opened and visible (for ex. Chrome).

**Comment by aarnt** [comment]
Hi @FadeMind 
Are you still having issues with Octopi Settings window?

**Comment by FadeMind** [comment]
@aarnt Hi. Lastest release do not have this issue. Closing. Regards
