### ISSUE TITLE
[feature request] Do not empty search bar when switching to AUR and back

### ISSUE THREAD

**Issue by DevPre24** [aarnt/octopi#329]
It's very frustrating to type something in the search bar, switch to AUR and then realize that you have to type it again because the search bar was cleared during the switching process. Can you fix this annoying behavior, please? Thanks!

**Comment by mozo78** [comment]
+1

**Comment by Vincent43** [comment]
https://github.com/aarnt/octopi/commit/b9f0c6b73cee0aac68e9f90c4a92aff3c984e626
