### ISSUE TITLE
Add option to pass additional pacman / yaourt arguments

### ISSUE THREAD

**Issue by Ryex** [aarnt/octopi#33]
It is some times necessary to pass additional arguments like --force to a command

**Comment by berot3** [comment]
+1, also --noedit or even --noconfirm for yourt would be handy, at least for those who know what they are doing :). 
There is a .config/octopi/octopi.conf, would be great to be able to add it there!

**Comment by lucazade** [comment]
It would be nice.. I use `--devel` in order to update -git packages from aur

**Comment by aarnt** [comment]
Options dialog has some.
