### ISSUE TITLE
Octopi deletes other applications' files from /tmp on quit

### ISSUE THREAD

**Issue by vedgy** [aarnt/octopi#330]
Quitting Octopi deletes ALL *qtsingleapplication* files, including lock files, from /tmp. So quitting octopi allows launching a second instance of *goldendict*, *qbittorrent* and *qtcreator -client*, which also happen to use the *qtsingleapplication* library. The *qbittorrent* issue that is currently caused by this *octopi* bug: https://github.com/qbittorrent/qBittorrent/issues/4909.

[UnixCommand::removeTemporaryFiles()](https://github.com/aarnt/octopi/blob/c413caadd11883ffcebf13ce515fb17bc23ebd27/src/unixcommand.cpp#L651) deletes "unneeded" files far too aggressively. I recommend not only replacing the *"qtsingleapp\*"* filter with something more specific, like *"qtsingleapp-Octopi\*"*, but also doing something about the way too generic *"gpg\*"* and *".qt_temp_\*"* file filters.

**Comment by aarnt** [comment]
Thanks. It'll be fixed asap.

**Comment by aarnt** [comment]
Fixed at upstream.
