### ISSUE TITLE
Update to libalpm.so.11

### ISSUE THREAD

**Issue by palmenros** [aarnt/octopi#332]
I'm running Arch Linux.

Now, when running octopi, the following error occurs:
`octopi: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory`

That is because pacman has updated `libalpm.so.10` to `libalpm.so.11`. I don't recommend doing this, indeed I advise against it, but you can just symlink `libalpm.so.10` to `libalpm.so.11` and octopi will work just fine.

Please update libalpm to `libalpm.so.11`

**Comment by demmm** [comment]
Both need a rebuild, Octopi itself also links directly to libalpm.so, not just alpm_octopi_utils.  Not an Octopi issue at all though. Issue should be closed.

**Comment by palmenros** [comment]
When rebuilding octopi, the following error occurs: `src/transactiondialog.cpp:78:63: error: invalid use of incomplete type ‘class QRegularExpression’
   if (detailedtext.contains(QRegularExpression("pacman-[0-9]+")))
`.
It may be out of context, but I am kind of new to linux, why is a rebuild of the packages needed? 
Thanks

**Comment by demmm** [comment]
You need the latest commit, if you are building on Qt 5.11, see https://github.com/aarnt/octopi/issues/327
