### ISSUE TITLE
更新后无法链接网络。。。

### ISSUE THREAD

**Issue by lizo520** [aarnt/octopi#333]
![_ _20180602160111](https://user-images.githubusercontent.com/32296439/40872282-3b604438-667e-11e8-92f6-406ef5754a84.png)
![_ _20180602160217](https://user-images.githubusercontent.com/32296439/40872291-56c3c3bc-667e-11e8-8bf8-0f402adef0a6.png)
我也不清楚这个问题是由什么原因导致的。 之前还是好的。更新后就无法连接网络了。其他程序正常。
sudo pacman -S     可以通过命令模式安装程序。。

**Comment by OCNYang** [comment]
It's the same as mine。

和我的完全一样的错误，卸载重装还是报一样的错误。我也是系统升级以后才出现这种情况的。

Since I upgraded the system, when I use octopi, whether the installation or uninstallation of the software by it will appear "network seems to be unavailable" pop-up window.

**Comment by aarnt** [comment]
Can you both ping google.com in a terminal? 
Open a terminal and type:
ping -c 1 -W 3 www.google.com
What is the result?

**Comment by OCNYang** [comment]
```
[ocn@ocn-pc ~]$ ping -c 1 -W 3 www.google.com
PING www.google.com (67.228.235.91) 56(84) bytes of data.

--- www.google.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

[ocn@ocn-pc ~]$ ping -c 1 -W 3 www.baidu.com
PING www.a.shifen.com (58.217.200.13) 56(84) bytes of data.
64 bytes from 58.217.200.13: icmp_seq=1 ttl=54 time=14.7 ms

--- www.a.shifen.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 14.704/14.704/14.704/0.000 ms

```

There is a problem with my Google connection, but I don't know how it relates to my use of octopi.

Users in China are very unfortunate and most people are unable to access Google. Is octopi also rejecting Chinese users?

**Comment by aarnt** [comment]
No, octopi is not rejecting anyone. 
This issue Will bem fixed. Do not worry.

**Comment by aarnt** [comment]
Fixed at upstream.
