### ISSUE TITLE
"No Internet Available" error with internet working after upgrading to 0.8.12-2

### ISSUE THREAD

**Issue by arizonneto** [aarnt/octopi#334]
Qt version: 5.11.0
Pacman version: 5.1.0
OS: Manjaro Linux x86_64

Octopi was working as intended before i updated to the latest version, but now i can't update databases, install packages or acess the AUR packages. Didn't find any instance of the issue elsewhere, reinstalling doesn't fix the issue.

**Comment by aarnt** [comment]
Can you both ping google.com in a terminal?
Open a terminal and type:
ping -c 1 -W 3 www.google.com
What is the result?

**Comment by arizonneto** [comment]
[anon@anon-pc ~]$ ping -c 1 -W 3 www.google.com
PING www.google.com(2800:3f0:4001:805::2004 (2800:3f0:4001:805::2004)) 56 data bytes

--- www.google.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

**Comment by rmb122** [comment]
I got the same issue. `ping` google got no reply, so I add `127.0.0.1  www.google.com` to the `/etc/hosts` and everything be ok. I think the problem is the gfw in China.

**Comment by aarnt** [comment]
You're right. We can add another test to a well known chinese site. Which one would you suggest?

**Comment by rmb122** [comment]
You can use www.baidu.com. It' the most popular search engine in China because we can't directly access google.

**Comment by aarnt** [comment]
Ok, thank you!

**Comment by rmb122** [comment]
:)

**Comment by aarnt** [comment]
Fixed at upstream.
