### ISSUE TITLE
Sync database shows "internet seems unavailable!" whereas I'm connected with Internet

### ISSUE THREAD

**Issue by piomiq** [aarnt/octopi#335]
I didn't use octopi sometime and run it today. I was surprised when I saw message "internet seems unavailable!" after clicking into "Sync database". Of course I was connected with Internet  I double checked this by downloading file in web browser and running ping command like this: "sudo ping google.com". All was fine with access only octopi is can't see "internet access".

Additionally when I run "Cache cleaner" it just waiting for something - showing "waiting mouse cursor". Couple minutes passed and happened nothing. I rerun it couple time. I restarted my PC. Nothing helped.

I don't have running octopi-notifier

tested octopi version is: 0.8.5-4
Qt version is: 5.11
system Antergos (up-to-date on day 2018/06/06)

**Comment by aarnt** [comment]
sudo ping?
And what about just ping without sudo?

As for the Cache Cleaner to work, you'll need pacman-contrib package.

**Comment by piomiq** [comment]
I run sudo ping because my system doesn't allow to run ping as normal user. In this case I get following message:
> $ ping google.com
> $ ping: socket: Operation not permitted

But does it matter how I run ping? If for example Pamac works fine and command:
`sudo pacman -Syu`
shows message like:
> :: Synchronizing package databases...
>  core is up to date

so I see the issue in octopi itself.

I'm from Poland.

OK. Installation pacman-contrib helped. Thanks.

**Comment by aarnt** [comment]
So I'll have to disable ping testing. It causes lots of issues.

**Comment by aarnt** [comment]
Commit 3935abcd821650620828c44b424398ac363847a7 has another way to test connectivity.
Could you test it?

**Comment by aarnt** [comment]
Don't use this PKGBUILD.
After the clone you should do:

cd <PATH_OF_CLONE>
qmake-qt5
make

Binary will be located at <PATH_OF_CLONE/bin/octopi>

**Comment by piomiq** [comment]
OK. Seems that works :).
Databases were synchronized quite fast.

**Comment by aarnt** [comment]
No internet unavailable errors?

**Comment by piomiq** [comment]
No. Now works well.
