### ISSUE TITLE
[Suggestion] Automatically download updates

### ISSUE THREAD

**Issue by piomiq** [aarnt/octopi#336]
As in subject. In my opinion it would be significantly speed up updating the system.
Updates could be download in background and user notified about available updates could be just install them without waiting form downloading.
Of course it is necessary to check if on local drive is available free space for downloading packages and notify if not (maybe suggesting to clear cache of packages).

**Comment by nRoof** [comment]
If this ever to be implemented, please do not make this behavior default. At least there should be an option to disable this. There are people who use limited data plans sometimes, you know.

**Comment by piomiq** [comment]
I didn't expect that it will be default behavior. It's obvious that some like to have downloaded packages others not.

Yes, or course can happen extra download of package(s), because might happen change of version some package between last download and running upgrade by user, but for sure will be less then in case of downloading all of packages like now.
Anyway, in my opinion, it is optimization for upgrading the system.

**Comment by aarnt** [comment]
As @nRoof I don't like those automatisms too so skipping this one.
