### ISSUE TITLE
[Suggestion] Left click on notifier icon shows octopi main window

### ISSUE THREAD

**Issue by piomiq** [aarnt/octopi#337]
As in subject. It would be useful if someone want to quickly install some new package, or just search some package. One click and I have octopi window, when I do what I want.
Now I need to run octopi separately to be able to do above things.

**Comment by aarnt** [comment]
A Double click does what you want.

**Comment by piomiq** [comment]
Ahh yes, indeed. I got used to one click, recently using Pamac.
I compared both and I think that Pamac starts faster. I mean its main window shows quickly. Pamac shows immediately after click, whereas after double click in octopi I need wait ~1-2 seconds. Maybe Pamac is somehow cached, or before (when system starts) loaded into memory.
