### ISSUE TITLE
[Suggestion] Showing history of updates

### ISSUE THREAD

**Issue by piomiq** [aarnt/octopi#338]
Would be nice to be able to check history of updates using option in octopi (for example button on toolbar).
History could be shown in new window or in tab on bottom (for example next to "Usage" view).

**Comment by aarnt** [comment]
Octopi uses a Tool for that which is called pacmanlogviewer. When you have It installed It becomes accessible in the tools menu.

**Comment by piomiq** [comment]
Again thanks for helper package :). 
History looks quite pretty. Only I noticed one issue. When I double click on first column ("Date") it squeezes to width of name of day. For example I see only "Sunday, " . 
Would be nice to see here (in first column) also time (at least hour:minutes).

**Comment by aarnt** [comment]
This software is maintained by Chakra dev gcala. Do not open issues gere.

**Comment by piomiq** [comment]
OK. So I will report them this issue.

**Comment by aarnt** [comment]
Thank you!
