### ISSUE TITLE
Octopi deletes all qtsingleapplication files

### ISSUE THREAD

**Issue by mozo78** [aarnt/octopi#339]
Please, fix deleting all qtsingleapplication files for qbittorrent starts with multiple instances. See this post:
https://github.com/qbittorrent/qBittorrent/issues/4909#issuecomment-390614819
And the problem is here:
https://github.com/aarnt/octopi/blob/c413caadd11883ffcebf13ce515fb17bc23ebd27/src/unixcommand.cpp#L651
Thank you.

**Comment by Vincent43** [comment]
Wasn't this fixed with https://github.com/aarnt/octopi/commit/be5fa78234e230d81f485fe7a9fafcaa30eb2488 ? Do you use latest version (0.9.0)?

**Comment by mozo78** [comment]
Yes I installed it today and I don't know yet if the problem is fixed in the new version. Excuse me if the problem is already fixed.

**Comment by aarnt** [comment]
Test with release 0.9.0 please.

**Comment by dreamhunt** [comment]
It seems that it is fixed. I'll report if I have any trouble but for now it's all good. Thank you :)
