### ISSUE TITLE
use of aur helpers trizen, pacaur and pikaur slows down octopi

### ISSUE THREAD

**Issue by kinoegit** [aarnt/octopi#342]
Here on Arch Plasma the use of all aur helpers apart from yaourt slows down octopi, makes it nearly unreactive.
What i did so far: 
-building each one of the following with aurman:
  -octopi 9.0.1
  -octopi-git  1:0.8.1.r1166.144c3f2-1
  -octopi-kde-git  0.9.0.1408-1
-with and without rebuilding alpm_octopi_utils
-with and without enabling alpm_octopi_utils
-deleting cache of aurman before build
-deleting configs of octopi before running octopi

But everytime i enable the use of trizen, pacaur or pikaur octopi ends up nearly freezing, mostly not before a first search and installation of a package or a database sync. It then opens or closes only after minutes by clicking right or left on notifier. At the end of a command the window freezes for several minutes till the info "command finished" finally appears.
By only enabling yaourt both octopi and octopi notifier seem to run smoothly as it was till previous version of octopi. The latter (0.8.1 ?) ran without any issues no matter whether pacaur was enabled or yaourt.

**Comment by kinoegit** [comment]
Status quo: no difference even after pikaur and trizen been updated.
One could say **no use of other helpers possible** apart from yaourt!
Nobody else is experiencing this?

**Comment by DrDoctor13** [comment]
Is there any terminal output? Any spikes in CPU usage? What versions of the AUR tools are you running? What AUR settings do you have configured in Octopi?

**Comment by kinoegit** [comment]
@DrDoctor13 
-possible terminal outputs when i'm changing options in octopi or octopi notifier:
plasmashell[756]: Call to AboutToShow() failed: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."

octopi[7609]: QFileSystemWatcher::removePaths: list is empty

-No spikes in CPU usage
-AUR tools versions:
pacaur-git-4.7.90-1
trizen 1:1.51-1
pikaur 1.2.23-1

-octopi settings:
General: don't show number of packages / show button to stop...
AUR: trizen > confirm but no edit / search for AUR packages out of date
Backend: ALPM + pacman
Symbols: standard icons
SU tools: there is 'automatic', 'gksu' and 'kdesu' to choose BUT any choice i make is not being saved! strange! I'm on a Plasma KDE Desktop and kdesu is standard in general, gksu is a dependency of qtarchiver... maybe gksu is the culprit!?
Terminal: konsole
Thanks for your help

**Comment by kinoegit** [comment]
Unfortunately those dropouts of responsiveness reappeared immediately at the moment trizen, pacaur or picaur are chosen as AUR helper!
No peaks of CPU. Network is up. SU tool is automatic or kdesu (i still can't make a choice even though gksu is off the system).
Any ideas?

**Comment by kinoegit** [comment]
Is anybody experiencing this too?

**Comment by aarnt** [comment]
Hi @kinoegit,
Could you please test with upstream code? 
Just download the PKGFILE and "makepkg -f" it.

**Comment by kinoegit** [comment]
Hi @aarnt,
thank you for answering! Happily this issue is not the case anymore. I use pacaur since its development was continued and those dropouts didn't occur since then! Sorry for not sharing... forgot

**Comment by aarnt** [comment]
Thank you very much!
