### ISSUE TITLE
"use_pty" option for sudo breaks octopi usage

### ISSUE THREAD

**Issue by Maryse47** [aarnt/octopi#345]
`use_pty`option which can be enabled in `/etc/sudoers` by appending `Defaults  use_pty` line breaks installing and removing packages through octopi interface.

This option [enhances sudo security](http://www.openwall.com/lists/oss-security/2018/06/12/2) and will be [enabled by default](http://www.openwall.com/lists/oss-security/2018/06/12/4) at some point in future.

**Comment by demmm** [comment]
Just octopi?  Or pacman commands in general?

**Comment by Maryse47** [comment]
Just Octopi because of way it acquires root privileges for installing/removing software.
