### ISSUE TITLE
Allow AUR section be visible without AUR helpers + warning

### ISSUE THREAD

**Issue by michaldybczak** [aarnt/octopi#347]
FEATURE REQUEST

There is a problem on Manjaro KDE currently. It ships without AUR helper and Octopi doesn't even show AUR tab so new uses are clueless how to enable AUR.

Because of that some try to force solution to use pamac on Manjaro KDE, which has done it right: it has an AUR on/off switcher and some warning about AUR.

I'm afraid that Octopi will be given up by Manjaro if it won't implement these features. Besides, there is no perk of hiding AUR tab anyway.

So the request again would be:

1. Let AUR settings be visible all the time, even without any AUR helper installed
2. Add info: "To enable AUR support install one of the supported AUR helpers from the list above" or something alike.
3. Add warning when user tries to switch AUR on: "AUR is not officially supported by Manjaro or Arch. Some packages may be dangerous. Use AUR at your own risk." or something alike ;)

Here is the link to a thread where user is clueless because AUR section is not visible:

https://forum.manjaro.org/t/spotify-how-to-install/55290/4

There will be more of such topics with time.

Here is a link to a discussion about AUR helper on Manajaro KDE and Octopi's role in it.

https://forum.manjaro.org/t/lack-of-aur-helper-by-default/55457

Of course there were many other similar threads. Manjaro doesn't support officially AUR but wants to have reasonably easy access to it. Pamac currently solves that nicely, Octopi is not and that changes should fix it.

Thanks for listening and I hope you consider it positively. I don't want Octopi be given up by Manjaro KDE since it's the main distro where Octopi is used. I personally like it more then Pamac and would like to see it shipped by default on Manjaro KDE in the future as well.

**Comment by philmmanjaro** [comment]
Well, **pamac** support AUR automatically. **Octopi** on the other hand needs a helper. Actually we are focusing on **pamac-qt** for our KDE, to have one graphical package manager in all our editions. **Octopi** will be then optional, but still available, as not pre-installed on KDE edition anymore.

**Comment by aarnt** [comment]
Open Source power comes from the people who make it possible. Octopi received (and receives) a lot of help by many developers/translators around the globe. I'm pretty sure pacman-qt will be an amazing project and will possibly contribute code to make Octopi gets better!

**Comment by michaldybczak** [comment]
Given the facts that Octop developers are not so active here and some pull requests like Pikaur support are hanging for a long time and some issues in the past that needed months to be resolved, I start to feel that pacman-qt is the best solution for now.
