### ISSUE TITLE
Support for Flatpack (Snap)

### ISSUE THREAD

**Issue by lil5** [aarnt/octopi#349]
I really like the simplicity with installing from AUR as well as Manjaro repos.
Flatpack updates (, installs & uninstalls) would be a great addition to Octopi.

**Comment by aarnt** [comment]
@lil5 Octopi was designed to be a Pacman frontend.
I'd prefer to keep the code as simple as possible and honor the UNIX philosophy.
This is not a "It will never support Flatpack". But for now, I'd like to see other changes.

**Comment by edmundlaugasson** [comment]
The main reason, why we need Flatpak, Snap, why not also AppImage support - Octopi is Qt-based. Pamac has all it but it is GTK-based. People using Qt-based desktop environments would stick on apps based same library. As even KDE Plasma has done incredibly good job and it's desktop takes ca 720 MB of RAM and as we know - is very flexible, then lots of users are using already either KDE or any other Qt-based desktop environment.
So, we would very much appreciate to see fully usable Qt-based software manager for most used software formats.

**Comment by sh2ka** [comment]
> The main reason, why we need Flatpak, Snap, why not also AppImage support - Octopi is Qt-based. Pamac has all it but it is GTK-based. People using Qt-based desktop environments would stick on apps based same library. As even KDE Plasma has done incredibly good job and it's desktop takes ca 720 MB of RAM and as we know - is very flexible, then lots of users are using already either KDE or any other Qt-based desktop environment. So, we would very much appreciate to see fully usable Qt-based software manager for most used software formats.

It is sad, but now this is the only reason why I don't use octopi in Manjaro.
