### ISSUE TITLE
[Privacy] sysinfo -> ptpb.pw is only returning the url

### ISSUE THREAD

**Issue by sda2b** [aarnt/octopi#350]
Hello,

Could it be possible to use 

**https://ptpb.pw/** instead of **https://ptpb.pw/?u=1**

So that it returns full information, including upload UUID to be able to ask for paste removal.
Also, it would be a good idea to implement a confirmation "box" when clicking the SysInfo > ptpb.pw

Thanks

**Comment by megitu** [comment]
And how to remove the entry sent by Octopi to ptpb.pw without UUID?
It is a serious privacy violation issue!

**Comment by buhman** [comment]
You might also consider adding something like `-F s=86400` to make the pastes expire in 24 hours by default.

**Comment by aarnt** [comment]
Changed upstream.
