### ISSUE TITLE
Do not require admin password for every commited action

### ISSUE THREAD

**Issue by tysontan** [aarnt/octopi#352]
Octopi requires administrator password every time when an action is committed. I suggest we make it possible to keep the elevated privilege available for a while, like what we do in consoles. This will alleviate a lot of the inconvenience. You may know a similar GUI like Octopi called Pacmac, it is handling it that way.

**Comment by aarnt** [comment]
Upstream version now supports sudo with NOPASSWD option (only using lxqt-sudo). 
Your /etc/sudoers needs something like this:

```
Cmnd_Alias      OCTOPIHELPER = /usr/lib/octopi/octopi-helper
%wheel ALL=(ALL) NOPASSWD:SETENV: OCTOPIHELPER
```
