### ISSUE TITLE
Admin password field takes too long to appear after pressing the Commit button

### ISSUE THREAD

**Issue by tysontan** [aarnt/octopi#353]
In Octopi 0.9.0.5 (Manjaro 17.1.12 KDE), after pressing the Commit button, the Administrator password field takes a long time to appear, making the experience feels slow and unreliable. Other similar package manager GUI like Pacmac and Synaptic display password field immediately. I hope Octopi can do that too.

**Comment by aarnt** [comment]
Hi @tysontan 
Can you test with upstream code?

**Comment by tysontan** [comment]
Hi @aarnt I'm sorry, because of me being very busy with real life problems at the moment, I don't have much time testing things unless they were provided by my distro (Manjaro 18.0.4). Still, feel free to teach me the how-tos, if it is not a big hassle, I might be able to do it for you.

**Comment by aarnt** [comment]
Hi @tysontan , no problem.
It's kinda easy to test upstream code. You can download Octopi's PKGFILE and issue a "makepkg -f" at the folder you downloaded it. The build process will generate a pkg that you can install with pacman -U <name_of_pkg>.
Maybe it's a good idea to remove Manjaro's Octopi and its related tools before doing that.

**Comment by aarnt** [comment]
Closed by lack of feedback.
