### ISSUE TITLE
UX improvement suggestions on the checkboxes

### ISSUE THREAD

**Issue by tysontan** [aarnt/octopi#354]
I have a few suggestions for Octopi's UX around its checkboxes:
1) By checkbox, I mean the ones on the left of the software names 
2) When a user left-click over a checkbox, display the current right-click menu
3) If the software is installed, change the item "Install" to "Reinstall" from its right-click menu

**Comment by aarnt** [comment]
Implemented upstream.

**Comment by tysontan** [comment]
Does it mean the improvement has been implemented and it was by the upstream, or does it mean that Octopi will not improve and consider this to be an upstream issue? In either case can you tell me where this upstream is?

**Comment by tysontan** [comment]
Thank you! :)
