### ISSUE TITLE
Automatically clear Find field after clicking on Info tab's dependency links

### ISSUE THREAD

**Issue by tysontan** [aarnt/octopi#355]
In Octopi's "Info" tab, we can click-and-jump to the dependencies, and it will be highlighted on the list above. However, when there are keywords in "Find" field above the list (which we often have), they sometimes filter out the dependency we just clicked. This is very confusing and inconvenient for installing missing optional dependencies.

My suggestion is:
Automatically clear Find field after clicking on Info tab's dependency links

**Comment by aarnt** [comment]
Implemented in upstream.

**Comment by tysontan** [comment]
Does it mean the improvement has been implemented and it was by the upstream, or does it mean that Octopi will not improve and consider this to be an upstream issue? In either case can you tell me where this upstream is?

**Comment by tysontan** [comment]
Thank you! :)
