### ISSUE TITLE
octopi-cachecleaner is not removeing packages

### ISSUE THREAD

**Issue by rahmanshaber** [aarnt/octopi#357]
i tried to remove the uninstalled packages and copy downloaded packages ,but when i clik the clean button nothing happens .
here is a discussion in manjaro [forum](https://forum.manjaro.org/t/octopi-not-cleaning-the-packages/66886/7)

**Comment by aarnt** [comment]
Probably an error generated by the priviledge escalation tool you are using.
Please, try upstream code.
