### ISSUE TITLE
[Feature Request] Make update notification and icon clickable on KDE

### ISSUE THREAD

**Issue by claell** [aarnt/octopi#358]
While using octopi I noticed one thing: The available update notifications are not clickable on KDE. Also the icon in the tray is not clickable, although it pulsates. I have to right click it and then click on update.

I hope this can get implemented and is not due to the design of the Plasma desktop.

**Comment by piotrekkr** [comment]
There is also issue after right clicking on octopi icon and selecting update. Octopi update window starts in background. If I have firefox opened and then select update in Octopi icon menu it starts under Firefox window in KDE plasma. I have to double click it on task bar (first click minimize octopi window) to show it in foreground.

**Comment by aarnt** [comment]
Icon ia now clickable.
I presume it's the best octopi can do.

**Comment by claell** [comment]
@piotrekkr I strongly suggest to open a separate issue for your problem, as it is only a bit related to this topic, but the roots might be completely different and also it is probably solved independently from this suggestion.

@aarnt Thanks for implementing this! I assume the notification will remain unclickable due to Plasma limitations?

**Comment by aarnt** [comment]
@claell 
Well as I do not use plasma I think I'm not able to answer that  :-(

**Comment by claell** [comment]
Alright, I assumed you used Plasma. I guess then the clickable notification is probably out of scope, so this can be closed?

**Comment by aarnt** [comment]
Ok.
