### ISSUE TITLE
[Feature Request] Pop up window for updates

### ISSUE THREAD

**Issue by claell** [aarnt/octopi#359]
When writing #358 I remembered that Ubuntu just displays a pop up window when updates are available. Maybe this can get implemented as an option for octopi if considered useful.

**Comment by aarnt** [comment]
I'll pass that one. Too intrusive.

**Comment by claell** [comment]
Well if it was optional it would be up to the user (so not intrusive), but I understand. Also I am not a fan of too much options, so I am ok with that decision.
