### ISSUE TITLE
After synchronizing the database Octopi doesn't update the update information statusbar

### ISSUE THREAD

**Issue by dmoebius** [aarnt/octopi#36]
This used to work in previous releases:
after "synchronize database" (Ctrl-D), Octopi no longer updates the statusbar showing the number of updateable packages. The numbers for system and yaourt packages stay at the old count, although there are much more updateable packages available. Only when I restart Octopi the actual count is picked up and displayed correctly.

**Comment by magchuz** [comment]
I'am use manjaro KDE 17.0
Can you help me, I've some problem can't synchronizing databese
Synchronizing databases...

warning: is up to date

Command finished with errors!

That the problem, please
