### ISSUE TITLE
[Feature Request] Add Condres OS Gnu/Linux

### ISSUE THREAD

**Issue by specialworld83** [aarnt/octopi#360]
Good evening, we kindly ask you to insert the Condres OS distribution based on ArchLinux in the support section as we have entered it as the primary system manager.
[https://condresos.codelinsoft.it/](https://condresos.codelinsoft.it/)

**Comment by aarnt** [comment]
Hi @specialworld83,
Do you want Octopi to show ArchLinux distro news? Or do your site have an RSS news service?
I also need the contents of your "/etc/os-release" file.

**Comment by specialworld83** [comment]
> Hi @specialworld83,
> Do you want Octopi to show ArchLinux distro news? Or do your site have an RSS news service?
> I also need the contents of your "/etc/os-release" file.

thank you so much. here is the info you need:

/etc/os-release
```
NAME="Condres OS"
PRETTY_NAME="Condres OS"
ID=condres
ID_LIKE=condresos
ANSI_COLOR="0;36"
HOME_URL="https://condresos.codelinsoft.it/"
SUPPORT_URL="https://condresos.codelinsoft.it/new/index.php/community"
BUG_REPORT_URL="https://condresos.codelinsoft.it/new/index.php/pages/bug"
```
RSS feed news:

https://condresos.codelinsoft.it/index.php/blog?format=feed&amp;type=rss

**Comment by aarnt** [comment]
Implemented at upstream.
