### ISSUE TITLE
Tab "News": File not found

### ISSUE THREAD

**Issue by massadm** [aarnt/octopi#362]
Cannot `Get latest distro news` with Octopi.

`Searching for Manjaro Linux latest news...` appears for a short then `File not found.` as a result.

![screenshot](https://user-images.githubusercontent.com/38354121/51714944-ea77d700-2047-11e9-9dfb-658538d67db0.png)

Octopi
Version: 0.9.0-6 - Qt 5.12.0

Pacman
Version: 5.1.2

**Comment by massadm** [comment]
Read Update Announcements is really important.

**Comment by aarnt** [comment]
Manjaro news URL changed. Fixed at upstream.

**Comment by massadm** [comment]
Manjaro announcements about stable updates is here: https://forum.manjaro.org/c/announcements/stable-updates.rss
