### ISSUE TITLE
[ some features request ]

### ISSUE THREAD

**Issue by ringo32** [aarnt/octopi#364]
hi, is it helpfull if you can Refresh your database of octopi without using the Root password ?

like : first

fakeroot -- pacman --sync --refresh --dbpath '/tmp/octopi'

after the  resfresh : 

pacman --query --upgrades --dbpath '/tmp/octopi'

then you dont need a password to fill ?

Also for the second, 

under files you can see the path of installed files
but not under not installed files you cannot see the path..

To load things at onces will take some time but if you select a not installed package you put a query button in it, you can query the what maps and stuf is in that package with like : 
pkgfile -l (package)

**Comment by aarnt** [comment]
Upstream is using checkupdates.
