### ISSUE TITLE
error install octopi via yay

### ISSUE THREAD

**Issue by dandydon414** [aarnt/octopi#367]
error trying to install octopi "yay -S octopi". any help would be appreciated.....thanks

alpm_config.vala alpm_octopi_utils.vala
alpm_config.vala:149.3-149.30: error: Assignment: Cannot convert from `Alpm.List<string>' to `Alpm.List<weak string?>'
                handle.cachedirs = cachedirs;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpm_config.vala:157.3-157.36: error: Assignment: Cannot convert from `Alpm.List<string>' to `Alpm.List<weak string?>'
                handle.ignoregroups = ignoregroups;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpm_config.vala:158.3-158.32: error: Assignment: Cannot convert from `Alpm.List<string>' to `Alpm.List<weak string?>'
                handle.ignorepkgs = ignorepkgs;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpm_config.vala:159.3-159.32: error: Assignment: Cannot convert from `Alpm.List<string>' to `Alpm.List<weak string?>'
                handle.noextracts = noextracts;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpm_config.vala:160.3-160.32: error: Assignment: Cannot convert from `Alpm.List<string>' to `Alpm.List<weak string?>'
                handle.noupgrades = noupgrades;
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpm_octopi_utils.vala:69.73-69.79: error: Argument 1: Cannot convert from `unowned Alpm.List<weak string>?' to `unowned Alpm.List<string>'
                Alpm.List<unowned Alpm.Package> results = alpm_handle.localdb.search (needles);
                                                                                      ^^^^^^^
alpm_octopi_utils.vala:74.27-74.33: error: Argument 1: Cannot convert from `unowned Alpm.List<weak string>?' to `unowned Alpm.List<string>'
                                syncpkgs = db.search (needles);
                                                      ^^^^^^^
alpm_octopi_utils.vala:77.31-77.37: error: Argument 1: Cannot convert from `unowned Alpm.List<weak string>?' to `unowned Alpm.List<string>'
                                syncpkgs.join (db.search (needles));
                                                          ^^^^^^^
alpm_octopi_utils.vala:83.3-83.9: error: The name `results' does not exist in the context of `AlpmUtils.search_all_dbs'
                results.join (syncpkgs.copy());
                ^^^^^^^
alpm_octopi_utils.vala:85.10-85.16: error: The name `results' does not exist in the context of `AlpmUtils.search_all_dbs'
                return results;
                       ^^^^^^^
alpm_octopi_utils.vala:99.39-99.57: error: Argument 1: Cannot convert from `unowned Alpm.List<weak Alpm.DB?>' to `unowned Alpm.List<Alpm.DB>'
                results.join (Alpm.find_group_pkgs (alpm_handle.syncdbs, group_name).diff (results, (Alpm.List.CompareFunc) alpm_pkg_compare_name));
                                                    ^^^^^^^^^^^^^^^^^^^
alpm_octopi_utils.vala:208.54-208.81: error: Argument 1: Cannot convert from `unowned Alpm.List<weak Alpm.Package?>' to `unowned Alpm.List<Alpm.Package>'
                                unowned Alpm.Package? pkg = Alpm.find_satisfier (alpm_handle.localdb.pkgcache, name);
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpm_octopi_utils.vala:209.9-209.11: error: The name `pkg' does not exist in the context of `AlpmUtils.get_updates'
                                if (pkg != null) {
                                    ^^^
alpm_octopi_utils.vala:210.40-210.42: error: The name `pkg' does not exist in the context of `AlpmUtils.get_updates'
                                        unowned Alpm.Package? candidate = pkg.sync_newversion (alpm_handle.syncdbs);
                                                                          ^^^
alpm_octopi_utils.vala:211.10-211.18: error: The name `candidate' does not exist in the context of `AlpmUtils.get_updates'
                                        if (candidate != null) {
                                            ^^^^^^^^^
alpm_octopi_utils.vala:212.23-212.31: error: The name `candidate' does not exist in the context of `AlpmUtils.get_updates'
                                                results.append (candidate);
                                                                ^^^^^^^^^
alpm_octopi_utils.vala:225.72-225.90: error: Argument 1: Cannot convert from `unowned Alpm.List<weak Alpm.DB?>' to `unowned Alpm.List<Alpm.DB>'
                                                unowned Alpm.Package? candidate = installed_pkg.sync_newversion (alpm_handle.syncdbs);
                                                                                                                 ^^^^^^^^^^^^^^^^^^^
alpm_octopi_utils.vala:226.11-226.19: error: The name `candidate' does not exist in the context of `AlpmUtils.get_updates'
                                                if (candidate != null) {
                                                    ^^^^^^^^^
alpm_octopi_utils.vala:227.24-227.32: error: The name `candidate' does not exist in the context of `AlpmUtils.get_updates'
                                                        results.append (candidate);
                                                                        ^^^^^^^^^
Compilation failed: 19 error(s), 0 warning(s)
make[1]: *** [Makefile:18: libalpm_octopi_utils.so] Error 1
make[1]: Leaving directory '/home/don/.cache/yay/alpm_octopi_utils/src/alpm_octopi_utils-7f3a6c7e0e46bf9acb54af472f4fe45ab632d58c/src'
make: *** [Makefile:11: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: alpm_octopi_utils

**Comment by Maryse47** [comment]
This bug comes from [alpm_octopi_utils](https://github.com/aarnt/alpm_octopi_utils/issues/2) package.

**Comment by aarnt** [comment]
Fixed at upstream.
