### ISSUE TITLE
ptpw.pw no longer exists

### ISSUE THREAD

**Issue by demmm** [aarnt/octopi#370]
See https://github.com/ptpb/pb/issues/246
I will try and find another option for SysInfo.

**Comment by aarnt** [comment]
Thanks!

**Comment by demmm** [comment]
Looks like this one might work:
http://sprunge.us/
@aarnt anything you can do with this code example?
https://github.com/wopfel/archlinux-setup-vb/commit/a4583357a225ea03a88a6a7942982ed31ac03789

**Comment by aarnt** [comment]
Opted to abort remote paste services. Now SysInfo is generated locally.
