### ISSUE TITLE
Use pkexec instead kdesu / gksu

### ISSUE THREAD

**Issue by Cyraus** [aarnt/octopi#371]
(A Suggest for `octopi` and `octopkg` project)
[pkexec](https://www.freedesktop.org/software/polkit/docs/0.105/pkexec.1.html) is a part of [polkit](https://freedesktop.org/wiki/Software/polkit/), it's available on Linux / BSD. And it's default privileges authorize frontend.

**Comment by aarnt** [comment]
Upstream code is using its own "octopi-sudo" priviledge escalation tool.
