### ISSUE TITLE
Does the octopi-notifier lock the pacman database?

### ISSUE THREAD

**Issue by marco-parillo** [aarnt/octopi#372]
I have found that if I boot a VM, and immediately sudo pacman -Syyu sometimes it seems as if the Octopi Notifier is locking my package database. If I re-try a couple of minutes later, I can then upgrade. Is it possible that the Octopi Notifier is running pacman -Sy in the background? Could the Octopi Notifier use checkupdates instead?

**Comment by marco-parillo** [comment]
https://github.com/aarnt/octopi/blob/b7fa1be6504829dfba5f6acc5f13f537906314b2/notifier/pacmanhelper/pacmanhelper.cpp

```
  QStringList params;
  params << "-Sy"; //-Syy or -Sy - eternal doubt!
  QString command = "/usr/bin/pacman";
  /*int code = */pacman.execute(command, params);
```

**Comment by aarnt** [comment]
I'll fix that issue @marco-parillo.
Database synchronization is a very controversial feature. It can lead to partial updates and is unfriendly with another alpm tools use scenario (pacman itself).
Maybe the solution is remove all "pacman -Sy[y]" code from Octopi.

**Comment by marco-parillo** [comment]
As far as I am concerned, if the choice is between a momentary lock condition versus partial updates, I would favor preventing partial updates. A newbie-friendly tool like Octopi should not allow a user to perform a partial update. Only an experienced user, using command-line tools, should be able to perform a partial update, and knowingly take full responsibility for the results.

**Comment by aarnt** [comment]
Fixed at upstream.
