### ISSUE TITLE
Improvement: drop hardcoded date format

### ISSUE THREAD

**Issue by toxpal** [aarnt/octopi#373]
I posted a topic on Manjaro forums, and guys suggested me to create a bug report. I don't think it's really a bug, but just a need for improvement - https://forum.manjaro.org/t/octopi-date-format/83276

Date in my locale is set to Y-m-d format, so all the applications display date in this format. However, Octopi ignores system settings and displays package build dates in d/m/y format because it's hardcoded into Octopi:

`pid.buildDate.toString("ddd - dd/MM/yyyy hh:mm:ss")`

Maybe you could drop hardcoded format and use system format? Or at least add an option to overwrite date format in Octopi settings? It would make much more sense because if user configures system to use a specific date/time format, he surely wants this format on entire system.

For example, if build date is 01/10/2018, many users will have hard time figuring correct date...

Is it 10th of January?
Or is it 1st of October?

I believe it's the main reason why ISO 8601 is used for international data exchange - to avoid any possible confusions and misinterpretations.

**Comment by aarnt** [comment]
Fixed in upstream.
