### ISSUE TITLE
"Installed"/"not installed" icons unusable for colorblind people

### ISSUE THREAD

**Issue by porta2note** [aarnt/octopi#376]
Octopi shows a tiny graphic of an ethernet port beside each package, and differentiates installed from uninstalled packages by changing this graphic from "greenish" to "reddish." (Note: I'm running Manjaro 18.4 KDE with the default theme.)

I put those in quotes because for a long time I didn't realize it was changing the color AT ALL. I'm red/green colorblind, like roughly 10% of the male population, and have been having major issues with this. Here's an example (ignore the checkmark) :

![octopi_hard](https://user-images.githubusercontent.com/24555710/57973927-99308200-796d-11e9-9c33-8d34956f5240.png)

Due to the low saturation of the colors used, and the fact that these icons are _tiny_, I _literally_ can't tell the difference between the two without sticking my face about 10cm from the screen and squinting. If I do that, I can vaguely see there are two different colors there but couldn't tell you which is which. I had to use photoshop's eyedropper just to figure out if I had both colors represented!

This isn't pretty, but I had a go at making a "better" version:

![octopi_medium](https://user-images.githubusercontent.com/24555710/57973933-a2b9ea00-796d-11e9-95c2-31fd59e89c9f.png)

...if the red/green dichotomy must be kept, at least I could tell those apart.

On the other hand,

![octopi_easy](https://user-images.githubusercontent.com/24555710/57973936-acdbe880-796d-11e9-87a9-a75a633c410e.png)

Much, _much_ better.

Is there a way I could replace those icons myself without rebuilding the whole program or hex-editing some datafile? Are they just stored as png files somewhere?

Is this something that should be fixed for everyone? I'm interested to hear from other colorblind people on this - are you having the same problem, or is it "just me"? It seems like this is a pretty big usability issue that could be fixed, but maybe I'm just an edge case here.

Once again, roughly 10% of the male population are red/green blind, and 1% female, but it doesn't affect everyone in exactly the same way. Still, that's a lot of users potentially having trouble with this.

**Comment by aarnt** [comment]
Hi @porta2note,
I understand your color blindness issue and how much this affect your every day Octopi use.
The fact is application icons are very hard to choose/create so I'm afraid the best workaround for now is to clone this Github project and replace the following icons before issuing a "makepkg -f" command:

./resources/images/noninstalled.png
./resources/images/installed.png

Try that and tell me if you succeeded.

**Comment by aarnt** [comment]
Not installed icons now are white.
