### ISSUE TITLE
Add Deepin terminal support

### ISSUE THREAD

**Issue by Oxalin** [aarnt/octopi#377]
I'm using Deepin and it seems its terminal is not supported. Looking a the source code, I see that each terminal needs to be added to a potential list of available terminal.

I'll have a look at adding its support. You can tag this issue as Feature request and assign it to my name.

**Comment by aarnt** [comment]
Hi Oxalin, I'm planning to ditch terminal support in favor of the internal Octopi terminal.
The main reason for that is the new "octopi-helper" does not work with external terminals.

**Comment by aarnt** [comment]
From 0.10.0 version on, QTermWidget is the only terminal supported!
