### ISSUE TITLE
Error: icon path information is incomplete when changing AUR helpers

### ISSUE THREAD

**Issue by philmmanjaro** [aarnt/octopi#379]
With commit f94ee1a04b0ca623fb0cae921b5f880692f78608 we get the following error message when switching the AUR helpers.

![error-msg](https://user-images.githubusercontent.com/5050022/58744489-d1db5b80-8443-11e9-8d9c-1e196ad367c0.png)

**Comment by voryzen** [comment]
Click on the 'icon' tab and tick 'use default notification icons' seems to fix it

**Comment by aarnt** [comment]
Can you test if latest upstream code fixes it?
