### ISSUE TITLE
Terminal: gksu unknown switch -u

### ISSUE THREAD

**Issue by philmmanjaro** [aarnt/octopi#380]
With current commit f94ee1a we get the following error when trying to run a cmd in terminal:

```
phil@development ~ $ octopi
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no

(process:7367): Gtk-WARNING **: 07:51:12.226: Locale not supported by C library.
	Using the fallback 'C' locale.

** (gksu:7367): WARNING **: 07:51:12.343: Unknown option -u

Usage:
  gksu [OPTION?] - run programs as root

Help Options:
  -h, --help       Show help options
```

**Comment by philmmanjaro** [comment]
seems the issue is with **gksu-polkit** which is shipped with **manjaro**. @fhdk, can you take a look?

**Comment by philmmanjaro** [comment]
Seems we may need to add support for **gksu-polkit**. See also [here](https://github.com/aarnt/octopi/blob/master/src/wmhelper.cpp#L211).

**Comment by fhdk** [comment]
We could just remove the symlink `gksu` from the gksu-polkit package.

I have not coded it just repackaged a debian package.

**Comment by fhdk** [comment]
gksu-polkit on manjaro - where and when

https://github.com/manjaro/release-plan/issues/200

**Comment by aarnt** [comment]
Upstream code now has its own escalation tool based on "lxqt-sudo", called "octopi-sudo".
From now on it'll be the only supported.
