### ISSUE TITLE
A few issues with Octopi 0.9.0

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [aarnt/octopi#381]
**First issue:** When I install an application from AUR using Octopi, it doesn't update its database to include the new installed package from AUR, and I have to close it, and open it again to be able to remove it.

**Second issue:** The installed application from AUR can't be remove from Octopi, but I can remove them manually from the terminal.

When I search for the installed application from AUR **after pressing** the AUR green icon next to the search box:

![Screenshot_20190701_220054](https://user-images.githubusercontent.com/29783425/60463486-66f09080-9c4c-11e9-8949-56e4f47dda11.png)

When I search for the installed application from AUR **without pressing** the AUR green icon next to the search box:

![Screenshot_20190701_220639](https://user-images.githubusercontent.com/29783425/60463596-b9ca4800-9c4c-11e9-8520-0859cc0acf16.png)

I use pacaur to install and remove packages from AUR.

**Comment by aarnt** [comment]
Hi. 
Don't worry, this no longer happens in 0.10 development code.
