### ISSUE TITLE
"Internet Seems Unavailable", but the packages can be installed from cache

### ISSUE THREAD

**Issue by unfa** [aarnt/octopi#382]
I've just wanted to (re)install some packages, that I have in cache - however my connection was down at the moment.

Octopi complained about the lack of Internet connection, so I fixed that, but then it said the installation requires 0 Bytes of download (as I have the packages in cache).

Could in such cases Octopi allow to install packages from the cache, and continue without the Internet connection? That could save the day in a few cases.

**Comment by aarnt** [comment]
Hi @unfa 
I implemented an option for enabling/disabling internet checking in the options dialog.
Available at upstream.
