### ISSUE TITLE
[Feature request] Vote on AUR packages

### ISSUE THREAD

**Issue by Tasty213** [aarnt/octopi#383]
One of the most useful things about the aur is users abilities to vote on packages. octopi already allows users to sort by these votes but it would be even better if you could vote from within the manager itself, this would also help cultivate the voting system.

**Comment by aarnt** [comment]
Implemented at upstream without external tool dependencies.

**Comment by linuxergr** [comment]
Hi

Latest Octopi release 0.10.0, does not login to AUR for voting, although the credentials are correct.
