### ISSUE TITLE
Is a new release in preparation?

### ISSUE THREAD

**Issue by MatMoul** [aarnt/octopi#384]
After all these updates from june 2018, it would be nice to have a new release with all changes from 0.9.0 (https://github.com/aarnt/octopi/releases)

Thanks for your work...

**Comment by aarnt** [comment]
Hi @MatMoul,
Yes, don't worry a new version is in preparation!

**Comment by MatMoul** [comment]
@aarnt Thanks for your feedback, I'm now the new maintainer of octopi for Arch Linux and when I look at Manjaro, octopi is more recent...
Now, I will wait the new release for the octopi main package and make a new package octopi-dev that based on commit...
For me, you can close this issue or tag it to anything to prevent a new same question ;-)

See you

**Comment by vanbreukelingen** [comment]
now, as we are having pacman 5.2.0, there's to be an update for "the green ghost", too! pamac has the new version already, how long will itt take until the octopi project will get it's update as octopkg in freeBSD and of course now on Arch from scratch?

**Comment by aarnt** [comment]
Imminent release.
Just needing some bug feedback.
