### ISSUE TITLE
Not all strings are translated? 

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#386]
@aarnt hi, why not all strings are translated to polish language (even if on transifex looks like :100:  is translated?)

![Screenshot_20190811_183902](https://user-images.githubusercontent.com/9846948/62836801-5f6ad100-bc67-11e9-8775-62e9a7a98ea9.png)

![Screenshot_20190811_183646](https://user-images.githubusercontent.com/9846948/62836782-2af71500-bc67-11e9-8da2-35b21ce75aca.png)

Version lastest from Manjaro repos.  0.9.0-14 (git-31060a) - Qt 5.13.0
```
alpm-octopi-utils 1.0.0-3
octopi 0.9.0-14
octopi-notifier-frameworks 0.9.0-14
```

Regards

**Comment by aarnt** [comment]
Hi, because I did not update the transifex site yet.

**Comment by FadeMind** [comment]
@aarnt I see :upside_down_face:
