### ISSUE TITLE
[Suggestion] Ability to mark package as installed "as dependency"/"explicitly"

### ISSUE THREAD

**Issue by axredneck** [aarnt/octopi#388]
Currently the only GUI for pacman that has such feature is PacmanXG but it is not available anymore.

**Comment by shaneramone** [comment]
It would also be nice if optional dependencies selected during the installation of a package were installed with "--asdeps"

**Comment by aarnt** [comment]
@axredneck 
Added option to change install reason of selected packages.

@shaneramone 
I'm sorry but that change may be hard to implement.

**Comment by axredneck** [comment]
@aarnt , it does nothing for me, package(s) are still "explicitly installed".

**Comment by axredneck** [comment]
Can't confirm it works because Octopi doesn't display properly whether package is installed "as a dependency" or "explicitly".
octopi-git from AUR, commit a34ba69c24cc7c1304685c49f3306bb6db1426e4

**Comment by aarnt** [comment]
@axredneck 
What "pacman -Qi <PKG_NAME>" says about the package?

**Comment by axredneck** [comment]
I try to change install reason of `stmm-games` package (installed from AUR). Both Octopi and `pacman -Qi` say it's installed explicitly, and after changing install reason using Octopi they both still say the same.

**Comment by aarnt** [comment]
Ok, thanks for testing.

**Comment by axredneck** [comment]
@aarnt, i mean, it doesn't work.

**Comment by aarnt** [comment]
What does not work?

**Comment by axredneck** [comment]
Oh my poor English...
I try to change install reason of the package (in my case it's `stmm-games`) using Octopi but it doesn't change, the package remains explicitly installed.

**Comment by aarnt** [comment]
@axredneck 
Ok.
Octopi uses "pacman -D --asdeps stmm-games" command to change from explicitly to as depency  installed.
Maybe this command do not work for Aur pkgs. I'll test.

**Comment by axredneck** [comment]
I tested, `pacman -D --asdeps stmm-games` works while octopi does nothing.

**Comment by aarnt** [comment]
I think you were doing that using AUR mode. Latest code only permits changing install reason on the main pkg list.
