### ISSUE TITLE
[BUG] UI stays locked after installing software with build in terminal

### ISSUE THREAD

**Issue by zocker-160** [aarnt/octopi#389]
Octopi version: 0.9.0-14 (git-31060a) - Qt 5.13.0
OS: Manjaro Linux 

when I install a software from AUR the command runs in the build in terminal with no problem, but after success the UI stays locked as if the command was still running.

When trying to close octopi I get the error `Canceling the running transaction may damage your system!` - but the command in the background did finish.

I didn't have this issue with older version of octopi, which did use an external terminal

![Screenshot_20190822_162447](https://user-images.githubusercontent.com/36563538/63522874-6b715100-c4f9-11e9-83d4-8063dccb1700.png)

![Screenshot_20190822_162552](https://user-images.githubusercontent.com/36563538/63522953-8cd23d00-c4f9-11e9-8613-b72f26a7a7aa.png)

**Comment by aarnt** [comment]
Hi @zocker-160,
Could you test upstream code? I disabled the translation for "Press any key...".
Worked here.

**Comment by zocker-160** [comment]
@aarnt yes problem is fixed
it says now `Press any key to continue...` but it finishes even without pressing anything and unlocks the UI

![Screenshot_20190920_164222](https://user-images.githubusercontent.com/36563538/65336055-e8a9e780-dbc5-11e9-8f58-39957c829899.png)

**Comment by aarnt** [comment]
Perfect. This is the expected behaviour. Thank u!
