### ISSUE TITLE
Error: Check updates

### ISSUE THREAD

**Issue by mefsaal** [aarnt/octopi#393]
Octopi version: 0.10.0 (dev) - Qt 5.13.1
OS: ArchLinux
DE: KDE 5.16.5
When i press check update on octopi this happens "command finished with errors!" . and octopi-notifier doesn't look for updates. 

![Screenshot_20191014_211343](https://user-images.githubusercontent.com/56521591/66790759-90fe5380-eec7-11e9-90e9-ae3b202b5dba.png)

**Comment by demmm** [comment]
Same issue on KaOS, opening with `octopi --debug` does not show any error when clicking the check update.
This also effects octopi-notifier, it will always show as never ending checking for updates on system (re)boot.
Issue noticed for builds from commit 0f432227953160ad897369b39c478f72f802c19a.
Qt 5.13.1, Plasma 5.16.5 & 5.17.0

Issue does NOT show if there are actual updates available, so it seems to hang when not finding updates.  As soon as you do the updates, then check again, issue shows itself.

**Comment by aarnt** [comment]
What is the result of checkupdates in a terminal ?

**Comment by demmm** [comment]
Issue is in new pacman-contrib, installing previous version 1.1.0, issue is gone.
But running checkupdates in terminal with new version, finishes with no error or hang.

**Comment by demmm** [comment]
To be clear, issue started with pacman-contrib 1.2.0

**Comment by demmm** [comment]
One more note, this is now the output of checkupdates -h
```
checkupdates -h
checkupdates v1.2.0

Safely print a list of pending updates

Usage: checkupdates [options]

  Options:
    -d, --download        download pending updates to the pacman cache.
    -h, --help            display this help message and exit.

Note: Export the "CHECKUPDATES_DB" variable to change the path of the temporary database.
```
Seems something changed for the DB?

**Comment by Morganamilo** [comment]
checkupgrades now returns 1 when there are no updates.

**Comment by aarnt** [comment]
Ok, I was suspecting It. I'll take a look asap. Thank you.

**Comment by demmm** [comment]
@aarnt this comit? https://git.archlinux.org/pacman-contrib.git/commit/?id=ab696663975c433c451d9927f907a67a14441263

**Comment by aarnt** [comment]
You're right. Currently checkupdates is returning value "1" to the terminal.
CLI apps which return different from "0" means error. That's why Octopi prints the error msg.

**Comment by demmm** [comment]
checkupdates with no updates available returns nothing here, not `1`

**Comment by aarnt** [comment]
Do a "echo $?" after a "checkupdates".

**Comment by demmm** [comment]
OK, that returns 1

**Comment by aarnt** [comment]
Patterns matter:
http://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

**Comment by demmm** [comment]
So, want me to patch line 100 https://git.archlinux.org/pacman-contrib.git/tree/src/checkupdates.sh.in and set to 0?  Tested that locally, fixes the issue.

**Comment by Morganamilo** [comment]
>Programs that perform comparison use a different convention: they use status 1 to indicate a mismatch, and status 2 to indicate an inability to compare. Your program should follow an existing convention if an existing convention makes sense for it.

**Comment by aarnt** [comment]
@demmm No, thanks.
I'll update Octopi asap.

**Comment by aarnt** [comment]
@demmm , Maybe it's better for Kaosx to patch "pacman-contrib" if you already updated to 1.2.0. Because I'll not be able to fix it in time.

**Comment by demmm** [comment]
@aarnt It is still in the build repo, core still has working pacman-contirb 1.1.0, I won't move until you get time to fix.

**Comment by aarnt** [comment]
Can you test new commit?

**Comment by demmm** [comment]
Commit 7c5e3f9f27529f8a372b17611eeec18cf788c8d7 fixed the issue here.

**Comment by mefsaal** [comment]
I can confirm whit the last commit update https://github.com/aarnt/octopi/commit/7c5e3f9f27529f8a372b17611eeec18cf788c8d7. Fixes the update problem in octopi 10.

**Comment by demmm** [comment]
Pacman-contrib 1.3 changed behavior again, thus breaking octopi-notifier, see for what I think is the breaking commit:
https://git.archlinux.org/pacman-contrib.git/commit/?id=3da550ef93ae0b999836181044d33a8147a00088

**Comment by jangotek** [comment]
just for reference:
i install octopi from chaotic-aur i got error on checking update installing base-devel fixed the error.
