### ISSUE TITLE
Octopi can't run ,show error message:"'expac' binary could not be found! " after update system.

### ISSUE THREAD

**Issue by kpwd** [aarnt/octopi#396]
When I updated my system(Manjaro OS),I can't open Octopi,it shows message "'expac' binary could not be found! " when I run it in shell 

but I have solved this problem ,I found you have no description about expac in the latest update

![DeepinScreenshot_select-area_20191106225728](https://user-images.githubusercontent.com/20472792/68309399-5748f300-00e9-11ea-9640-4d03b7a25ee3.png)

**Comment by aarnt** [comment]
Hi @kpwd , you have to submit this issue to the octopi packager at Manjaro.

**Comment by Morganamilo** [comment]
Why does an alpm user need expac anyway?

**Comment by aarnt** [comment]
Hi @Morganamilo , 
I saw your name in the top commiters of pacman.
I'd like to chat with you about pacman. How could it be possible?

**Comment by Morganamilo** [comment]
Well pacman has its own IRC channel, or you can just ask here. Don't forget I asked a question though. I don't really see why octopi needs expac when it uses alpm.

**Comment by aarnt** [comment]
Thanks.
I didn't forget. That's (also) why I'd like to chat.

**Comment by kpwd** [comment]
> Hi @kpwd , you have to submit this issue to the octopi packager at Manjaro.
@aarnt 
well,could you tell me where I can submit that? thanks.

**Comment by marco-parillo** [comment]
I think it has been raised with the Manjaro Devs. The normal way is to start with the forum, e.g.
https://forum.manjaro.org/t/octopi-dependency-issue/110159/1

but some more experienced users open issues on GitLab: 
https://gitlab.manjaro.org/packages/community/octopi/issues/2

**Comment by Morganamilo** [comment]
I still think there's no need for a depend on expac and would like to see it removed, or at least justified.

**Comment by aarnt** [comment]
Found a better way to deal with it using AlpmBackend.
Upstream code no longer needs "expac".
