### ISSUE TITLE
Previous Commit Option missing in octopi

### ISSUE THREAD

**Issue by rupakbajgain** [aarnt/octopi#397]
How to commit the trasaction, there is no menu for it. AUR pakages can be installed, but i am using command line for normal packages. After some update it was missing, i even compiled from git source it was missing too.
![Screenshot_20191110_073510](https://user-images.githubusercontent.com/37989022/68537583-99469300-038e-11ea-8844-c42767ea22a5.png)

**Comment by aarnt** [comment]
Menu ia now hidden. You can use that check icon at toolbar to commit actions.
