### ISSUE TITLE
[Feature Request] KDE preferred system date format

### ISSUE THREAD

**Issue by tiemay** [aarnt/octopi#40]
On KDE, in "System Settings > Local > Country/Region & Language > Date & Time" you can set your preferred format e.g. YY/MM/DD, DD/MM/YY, MM/DD/YYYY .etc. Programs with kde integration will often reference and use the preferred format; It would be nice if the pacman log viewer did to. Right now the date collumn can only be WEEKDAY, MONTH DD, YYYY and the filter range MM/DD/YY. In in the system settings, I presume the date collumn would reference the long date format, and the filter range would reference the short.

**Comment by manjaro** [comment]
**pacman log viewer** is not part of Octopi. Please ask your request within the [right project](https://gitorious.org/gcala/pacmanlogviewer).
