### ISSUE TITLE
Octopi-terminal symbols are shown as squares or not shown at all

### ISSUE THREAD

**Issue by kinoegit** [aarnt/octopi#401]
Terminal looks like this: https://imgur.com/vn9OROj 
I have installed octopi-dev from the AUR on Arch linux. It seems octopi is using xterm (export TERM=xterm)? In bash i'm using powerline as a statusline plugin thats seen in the xterminal.
Xterm itself looks fine after adding `XTerm*faceName: DejaVu Sans Mono for Powerline` into ~/.Xresources and running `xrdb ~/.Xresources`

**Comment by aarnt** [comment]
I have no idea why it is happing.
Can you test with qterminal? Because it uses qtermwidget.

**Comment by kinoegit** [comment]
Thank you for answering. How to test it with qterminal? I tried it by changing `Term=xterm-256color` to `Term=qterminal` in: ~/.config/qterminal.org/qterminal.ini  and by changing `fontFamily=Oxygen Mono` to `fontFamily=DejaVu Sans Mono for Powerline` to no avail. Same with `export TERM=qterminal`.
Maybe it's related to powerline as a statusline plugin, maybe its a font problem?

**Comment by aarnt** [comment]
Try to execute a pacman command in your qterminal to ser if It outputs ok.

**Comment by kinoegit** [comment]
Qterminal's output is fine.

**Comment by kinoegit** [comment]
Highlighting, copying and pasting colored squares results in ordinary text. Output to be seen in https://imgur.com/vn9OROj copied and paste to Kwrite results: 
```
kinoe  /  bash -c "yay -S ksmoothdock ;echo 'Press any key to continue...'":: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  ksmoothdock-6.0-1
  1 ksmoothdock                      (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
```
It seems as though the squares "cover" the "layer" of the actual font !???

**Comment by aarnt** [comment]
And if you just start octopi and type a command in its terminal? Does It print ok?

**Comment by kinoegit** [comment]
Unfortunately it doesn't. The output is only squares, while the command `pacman -Syu` is running well in the background, readable only by copy and paste the squares into a text file. Apparently its a matter of displaying/rendering the font/letters.

**Comment by kinoegit** [comment]
Unfortunately it doesn't. The output is only squares, while a manually command like `pacman -Syu` is running well in the background, readable only by copy and paste the squares into a text file. Apparently its a matter of displaying/rendering the font/letters.

**Comment by MatMoul** [comment]
@kinoegit I suggest you to create a new user, then test octopi...
If working, try to install your powerline, then test octopi...
If this work, the issue is in your profile.
If this doesn't work, the issue seem in your locale or fonts or other...

**Comment by kinoegit** [comment]
@MatMoul thanks for bothering. Same issue when using octopi terminal in a new user account, either with or without powerline. So at least the issue has nothing to do with my profile....
```
locale:
LC_CTYPE="de_DE.UTF-8"
```
on Arch Linux Plasma 5.15.3

**Comment by aarnt** [comment]
@kinoegit 
Do this test: Open a terminal and type:

`export LC_CTYPE=C`
`/usr/bin/octopi`

And test embedded terminal.
If nothing changes, close Octopi and type:

`export LANG=en.US.UTF-8`
`/usr/bin/octopi`

And test if it outputs ok.

**Comment by kinoegit** [comment]
@aarnt 
testing those locales makes no difference to the output unfortunately. 

Some letters are rendered normally others are completely 'hidden behind' those squares... if it would be a matter of locale, shouldn't it concern ALL letters and ciphers?

**Comment by aarnt** [comment]
Well... Tough one.

**Comment by kinoegit** [comment]
Yes!
Is there an option to configure the embedded qtermwidget/ qterminal? Or even to choose which emulated terminal to use??

**Comment by aarnt** [comment]
@kinoegit 
I had to ditch that option because It involved too much work to maintain.
I think you should ask lxqt team about this issue. They are the authors of qterminal and qtermwidget. Maybe they can shed a light on this puzzle.

**Comment by kinoegit** [comment]
Obrigado Alexandre. I will look for help by the LXQT team.

**Comment by aarnt** [comment]
Don't forget to tell us the news :-)

**Comment by kinoegit** [comment]
I will :-)

**Comment by kinoegit** [comment]
Every time octopi is opened the terminal has changed directory to root instead of home, as far as i can recognize in spite of the squares. 
I have to run cd~ manually!!
Although I'm not sure whether its related to octopi but maybe its worth to mention that since octopi-git is installed there are two commands running continuously in **konsole** `clear` and `export TERM=xterm`. To be seen only in bash_history.

**Comment by aarnt** [comment]
Well, clear and export TERM are two commands I execute in embedded term constructor code.
But changing Dir to root is weird.

**Comment by kinoegit** [comment]
I found the problem... it is sitting 2ft in front of the monitor ;-) 
Once I installed manually a font called 'Monospace.ttf' which perhaps was in conflict with 
`font.setFamily("Monospace")` in qtermwidget.h or with other fonts of the monospace family because itself isn't a monospace font!
Anyway, uninstalling it solved the problem!
Really sorry for bothering you!
So now I can see what is going on in the embedded terminal of octopi I have two questions
- what is the purpose of (default) `cd /` ? 
- is there a way to change the quite big font size in the embedded terminal? changes in .Xresources or in the settings of Qterminal are without effect

**Comment by aarnt** [comment]
Great news!
I changed to "cd ~"
Ctrl + - didn't work? Terminal has context menu support for that to: zoom in and out.

**Comment by kinoegit** [comment]
Ctrl + - did work. 
Now Octopi is an awsome experience!! Il also love the integration of yay and it's running smoothly in general now, although closing update terminal demands root credentials to remove /var/lib/pacman/db.lck
Anyway-- thank you very much for your hard and great work!
