### ISSUE TITLE
System Upgrade has stopped working

### ISSUE THREAD

**Issue by MatMoul** [aarnt/octopi#402]
Hi,

On Arch Linux, with the master branch (octopi-dev on AUR), when I would to do a System Upgrade with octopi or octopi-notifier (With app or console), I receive this message :
`octopi-helper[aborted]: Suspicious execution method`
No update are made but the notifier change to the green ghost and If I check update, the notifier comme back to the red ghost.

commit 245db0572a97497d93b3864638458c4bcc0fa126 seem good (nor sure, perhaps a previous commit)
commit ed0a6c8b822dcc546c56c3f5afe5de3e8b357471 is breacked

Thanks for your work

**Comment by aarnt** [comment]
Hi @MatMoul ,
Are you executing from "/usr/bin/octopi" ? Otherwise it will not run.

**Comment by MatMoul** [comment]
@aarnt You're right, if I execute octopi from a console with "/usr/bin/octopi" it's work, with my octopi.desktop not...
I'll investigate...

**Comment by aarnt** [comment]
Thanks. 
@MatMoul You can remove "expac" dependency for your packages. It's no longer needed.

**Comment by MatMoul** [comment]
> You can remove "expac" dependency for your packages. It's no longer needed.

Thanks for the tips
