### ISSUE TITLE
[Suggestion] Setting to disable integrated terminal

### ISSUE THREAD

**Issue by BioLinkJ** [aarnt/octopi#406]
I would very much appreciate to have a setting to disable the use of the integrated terminal and get the external terminal window back as it it was in older versions of Octopi.

This is because the new integrated terminal has a few disadvantages:
 - The window size is not recognized properly which makes the 'progress bars' of pacman break to the next line when the Octopi window is too small. This does not happen when manually using pacman in a terminal window.
 - When installing updates by selecting 'System upgrade' from the tray icon, the new integrated terminal does not stay open after the update and does not allow to check the outputs of the update afterwards. This used to be the main advantage of executing the update in terminal widow in my opinion. The terminal window of the older versions used to stay open until manually closed.

Many thanks for your consideration.

**Comment by aarnt** [comment]
@BioLinkJ 
I cannot return to using external terminals
BUT
now integrated terminal will stay opened after executing actions on Notifier.
