### ISSUE TITLE
lxqt-sudo doesn't accept password neither root (su) nor user (sudo)

### ISSUE THREAD

**Issue by bits-fritz** [aarnt/octopi#410]
Su Tool -> lxqt-sudowhile issueing "refresh", the password dialog opens.
`Command: 'pacman -Syy; pkgfile -u'`
Entering the user password I get alerted:
---------- 
Child 'su' process failed!
su: Authentication failure
----------
Output section tells:
"su: Authentication failure"

Entering the root password I get no alert:

Output section tells:
bash: line 0: exec: pacman -Syy; pkgfile -u: not found

Doing a package reinstall:

Command: 'pacman -S --noconfirm extra/a2ps'

Output section tells:
bash: /home/me/pacman -S --noconfirm extra/a2ps: No such file or directory

System archlinux xfce4 4.14

*No english GUI at hand so translations from german may be confusing
*No glue what happened with first lines having that huge letters

**Comment by aarnt** [comment]
@bits-fritz 
What version of Octopi are you using?
Octopi now only supports embedded sudo tool called octopi-sudo.

**Comment by bits-fritz** [comment]
> @bits-fritz
> What version of Octopi are you using?
Version: 0.9.0 - Qt 5.13.1
> Octopi now only supports embedded sudo tool called octopi-sudo.
cannot find octopi-sudo

**Comment by aarnt** [comment]
@bits-fritz 
Which Linux distro are you using?

**Comment by bits-fritz** [comment]
recent archlinux with xfce4 4.14
as hidden in original bugreport ;-)

**Comment by aarnt** [comment]
@bits-fritz 
Ok. Try to remove your installed pkg and download Pkgbuild and octopi.install from upstream. Then compile latest code to test.

**Comment by bits-fritz** [comment]
@aarnt 
> Ok. Try to remove your installed pkg and download Pkgbuild and octopi.install from upstream. Then compile latest code to test.

This one worked **from the main window** - thank You :-)
Not working for me:
Authenticating while the **Upgrade Window** pops up.
Error out of memory:
`suspicious execution mode`

**Comment by aarnt** [comment]
@bits-fritz 
You have to run octopi as "/usr/bin/octopi".
Try and see if that way it works.

**Comment by bits-fritz** [comment]
In fact it was octopi notifier refusing upgrades.
After explicitly starting it with
`/usr/bin/octopi-notifier`
all works fine. :-)
Any reason no 0.10 Release beeing in place?

**Comment by aarnt** [comment]
@bits-fritz 
Believe me: we are almost there!
