### ISSUE TITLE
[Bug] octphelper exits with code 8: octopi-helper[aborted]: Couldn't attach to memory

### ISSUE THREAD

**Issue by NonLogicalDev** [aarnt/octopi#411]
I have been banging my head against this one, since some time ago my `octopi` stopped working entirely. Whenever I am trying to apply actions, I am getting the following after pressing trying `run in terminal`:

```
sudo /usr/lib/octopi/octphelper -ts

octopi-helper[aborted]: Couldn't attach to memory
```

Edit: sounds like it has something to do with `QTSharedMemory` not working properly:
https://github.com/aarnt/octopi/blob/master/helper/octopihelper.cpp#L220

Potentially useful info:
```
uname -a
Linux Nonlogical-MX 5.4.12-1-MANJARO #1 SMP PREEMPT Wed Jan 15 08:05:08 UTC 2020 x86_64 GNU/Linux
```

**Comment by aarnt** [comment]
Hi,
Can you use upstream code to test?

**Comment by NonLogicalDev** [comment]
I updated to the latest version, but the bug still persists. `Version: 0.9.0-22 (git-fd5dcc) - Qt 5.14.0`

**Comment by NonLogicalDev** [comment]
I did more testing and it seems if when I switch to stock `bash` for my shell, it seems to start working again.
But it for some reason does not like to work under `zsh`.

**Comment by NonLogicalDev** [comment]
I did more testing and it seems if when I switch to `bash` for my shell, it seems to start working again.
But it for some reason does not work at all under `zsh`.

**Comment by aarnt** [comment]
Humm. Thanks for the New indo.

**Comment by aarnt** [comment]
Tell me @NonLogicalDev 
And if you try to run actions without embedded terminal. Do they work?

**Comment by aarnt** [comment]
@NonLogicalDev 
Created a new user here with exact same permissions as mine and default shell to zsh.
No problem at all when running actions on octopi.

**Comment by NonLogicalDev** [comment]
Have you tried logging out / logging in after switching shell?

**Comment by NonLogicalDev** [comment]
After switching shells back and forth, it is now catching a segmentation fault when I am using ZSH, but works fine with BASH.

**Comment by NonLogicalDev** [comment]
Furthermore, it seems if I am launching octopi from terminal, as opposed to throug system launcher I am getting the `suspicious execution method` error.

**Comment by aarnt** [comment]
From terminal you have to run: /usr/bin/octopi 

About zsh: try to create another user. Make zsh its Shell and see what happens. I did not have any issues here.

**Comment by NonLogicalDev** [comment]
Hey @aarnt, sorry to keep bugging you but I finally had time in isolation =], to isolate the underlying issue. 

After about a bazillion logouts and logins, binary searching my ZSH configuration I have landed on something utmostly peculiar.

The offending configuration that I had that was causing this was actually this:
```
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi
```

**Comment by NonLogicalDev** [comment]
If I add this to bash config, the issue also starts happening if I switch to bash for my default shell (had to check just in case).

**Comment by NonLogicalDev** [comment]
I will make an educated guess. Likely it is indeed something with `QSharedMemory`, most likely the  `QSharedMemory` invocation, running as a part of `mainwindow` ends up with a different TMPDIR set as opposed to the `octopi-helper`...

Relevant code bits which open SharedMemory:
- [octopihelper](https://github.com/aarnt/octopi/blob/70b36e25dfedb9aa9db1c50d633841cce2fc0f35/helper/octopihelper.cpp?ts=4#L216)
- [mainwindow](https://github.com/aarnt/octopi/blob/cd2cc7045e8664200666770906fb3d5d40a91e26/src/mainwindow.cpp?ts=4#L90)

Not entirely sure if `prezto` zsh framework is doing something stupid by changing `TMPDIR` in `~/.zprofile`, or `QSharedMemory` has a bug. (I have a hunch it is the former)

In either case, it is probably worthwhile to make a note somewhere in the README about this, as [prezto](https://github.com/sorin-ionescu/prezto) is a rather popular framework.

Will for sure save some hair pulling for the next guy trying to figure out WTF is octopi is not working, without realizing it is a problem of their own making.
