### ISSUE TITLE
Info tab is can't be scrolled all the way down

### ISSUE THREAD

**Issue by Kzer-Za** [aarnt/octopi#414]
See the screenshot. That is as far down as it can be scrolled. The last line's bottom  is cut out.

![2020-02-02_14-44-18](https://user-images.githubusercontent.com/26425206/73613018-66fda800-4602-11ea-8fdd-5f0989ec2305.png)

**Comment by aarnt** [comment]
No idea why you are having this. If you click  anywhere inside info data and press the end Key does It get you to the end?

**Comment by Kzer-Za** [comment]
No, it gets the same result as scrolling.

But I found that if I resize the window to be larger than its default size (the one it has after the installation), then this problem goes away and I can scroll all the way down. But if I downsize the window below a certain limit, the problem appears again.

So, of course, one can simply increase the window size, but it still seems like an issue to me: people may want to make the window reasonably small for whatever reason, and also it seems that Octopi has this window size by default.

**Comment by aarnt** [comment]
Which theme are you using?

**Comment by Kzer-Za** [comment]
Vertex-Maia-Dark, but I tried switching to Adwaita, and the effect is still observable. Though with Maia it is more noticeable.

**Comment by aarnt** [comment]
I added a "<br>" at the end. Can you test if it is enough? You'll have to use PKGBUILD and octopi.install from github.

**Comment by Kzer-Za** [comment]
I've just tried installing it, but when I run `makepkg -f`, I get 

```
==> Missing dependencies:
  -> alpm_octopi_utils
```
I suppose it's because the package that I have in my system is called "alpm-octopi-utils" with dashes, not underscores.

**Comment by aarnt** [comment]
Probably.
Build this: https://github.com/aarnt/alpm_octopi_utils

**Comment by Kzer-Za** [comment]
I got alpm_octopi_utils, but now when I try to makepkg Octopi, I get:

```
Project ERROR: Unknown module(s) in QT: KNotifications
```

**Comment by aarnt** [comment]
Ok. Comment line 19 of PKGBUILD and you are ready to go.

**Comment by Kzer-Za** [comment]
Yes, it seems to be fixed.

**Comment by aarnt** [comment]
Great. Thanks for the bug report!
