### ISSUE TITLE
Can not check for updates since version 0.9.0-22

### ISSUE THREAD

**Issue by kai1703** [aarnt/octopi#415]
I get following message, when I check for updates in octopi since version 0.9.0-22:

![grafik](https://user-images.githubusercontent.com/36511186/73637077-bf1ac580-4667-11ea-8b54-112539f8a8a4.png)

And when I launch octopi from the command line, I get the warning `Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.` a few times.

The previous version and pacman work without problems.

I use manjaro linux.

**Comment by aarnt** [comment]
Upstream code is already fixed.
