### ISSUE TITLE
Error message when running update in terminal...

### ISSUE THREAD

**Issue by quietpinguin** [aarnt/octopi#416]
Hello

I receive the following error message when running update in terminal:

[simon@Simon-Laptop ~]$                                                                                                                           
[simon@Simon-Laptop ~]$ clear
**TERM environment variable not set.**
[simon@Simon-Laptop ~]$ sudo /usr/lib/octopi/octphelper -ts
[sudo] password for simon: 
resolving dependencies...
looking for conflicting packages...

Packages (3) f2fs-tools-1.13.0-1  fatresize-1.0.4-3  udftools-2.2-1

Total Download Size:   0.30 MiB
Total Installed Size:  0.92 MiB

:: Proceed with installation? [Y/n]

Any ideas?

**Comment by aarnt** [comment]
@quietpinguin 
Your TERM variable is not set.
Nothing to do with Octopi.

https://wiki.archlinux.org/index.php/Environment_variables
