### ISSUE TITLE
Can't login to aur.archlinux.org

### ISSUE THREAD

**Issue by SalvatorePerri** [aarnt/octopi#418]
When logging in to enable AUR voting I receive a wrong credentials error, but username and password are correct.

**Comment by aarnt** [comment]
@SalvatorePerri 
Hmm, hard to debug as I do not receive this error.
Are you able to login on AUR site using a browser?

**Comment by SalvatorePerri** [comment]
> @SalvatorePerri
> Hmm, hard to debug as I do not receive this error.
> Are you able to login on AUR site using a browser?

Yes I'm able to login through the browser.
Btw I'm using a 4.19.108-1-MANJARO kernel. 
I'm going to give a try using 4.14 and tell you.

**Comment by aarnt** [comment]
Are you behind a proxy?

**Comment by SalvatorePerri** [comment]
> Are you behind a proxy?

I'm not.
I tried 4.14 kernel, but still not working.

**Comment by lestermfp** [comment]
same problem here
![Screenshot_2020-05-02_01-15-56](https://user-images.githubusercontent.com/3236336/80845689-b019c400-8c12-11ea-9bbc-cd5e7e59dcc4.png)
installed from aur https://aur.archlinux.org/packages/octopi-git/
build log https://pastebin.com/UUzwys12
see some warnings here at line 40 for example

**Comment by aarnt** [comment]
@lestermfp 
I'm unable to debug this error without knowing the response you are getting from the web server. I'll have to enable some kind of debug info to circumvent that. If you are willing to colaborate, I'd appreciate.

**Comment by aarnt** [comment]
@lestermfp 
Can you please test again using latest git code?
You need to start octopi with a terminal by issuing this command:

`/usr/bin/octopi -d`

Pay attention to the "AurVote::login()" messages, if any.

**Comment by lestermfp** [comment]
@aarnt here the output
https://pastebin.com/0mh5P7Rc
i think web app get language settings by my ip address, so response send in russian

**Comment by lestermfp** [comment]
wrong assumption about ip, i've had language set to russian in account settings
So change it to english and now auth work just fine
![Screenshot_2020-05-02_18-12-08](https://user-images.githubusercontent.com/3236336/80868139-44cb0300-8ca1-11ea-91df-c5902086c54c.png)

**Comment by aarnt** [comment]
@lestermfp 
Can you revert to your russian language and test latest code?

**Comment by lestermfp** [comment]
@aarnt Yes, now works correctly with other than english languages

**Comment by aarnt** [comment]
@lestermfp Thanks!
Can you vote/unvote on packages as well?
"Ctrl+Shift+A" shows all your voted packages too.

**Comment by lestermfp** [comment]
@aarnt 
vote/unvote from context menu is working fine.
Generation of voted package list takes some time (~1 min) for the first time after press "Ctrl+Shift+A", then lag is disappeared. By the way output tab is blank until press "Ctrl+Shift+A"

**Comment by aarnt** [comment]
@lestermfp 
Ok, lag is normal. How many voted packages you have?

**Comment by lestermfp** [comment]
not many  ~25 pkgs
Lag is no longer happening, although the number of voted pkgs has increased to 45
Anyway, Thanks for this fix
