### ISSUE TITLE
Move to CMake build system 

### ISSUE THREAD

**Issue by luis-pereira** [aarnt/octopi#431]
Qbs has ben deprecated. Qt itself is preparing to use CMake. See https://wiki.qt.io/CMake_Port.

**Comment by aarnt** [comment]
Hi,
I'd read about It.
Sad thing as I liked qmake's simplicity.
Probably a thing for the next dev cycle and I'll need help.

**Comment by luis-pereira** [comment]
It's a laborious task. But no big deal ;)
