### ISSUE TITLE
I can't write "^" char in AUR search

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#432]
```
Arch Linux
Octopi Versión: 0.10.0 (dev) 
Qt 5.14.1
```
I want to search packages with starts with a word (using `^` character)
I want to search for packages in AUR that begin with a word but Octopi doesn't let me enter the character `^` after I click on the AUR button.

**Comment by aarnt** [comment]
@simonbcn 

It's a little bit more complicated than it looks. If I'm not wrong yay does not support that kind of search for AUR packages. Pacman neither, but I use a filter model to implement such feature on the main pkg list.

**Comment by aarnt** [comment]
Added support for '^' and '$' chars in upstream code.

**Comment by Morganamilo** [comment]
Why not have actual regex support instead of just cherry picking two parts of regex?
