### ISSUE TITLE
Project URL in Help tab is outdated

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#433]
```
Arch Linux
octopi-git (installed from AUR)
```
![captura_20200329_102354](https://user-images.githubusercontent.com/428231/77844461-6bc87d80-71a7-11ea-878f-20c6c706f04b.png)

**Comment by aarnt** [comment]
I do not maintain octopi AUR pkgs.

**Comment by simonbcn** [comment]
It isn't a problem of AUR pkg, it's a problem of your code:
```
./PKGBUILD:url="https://octopiproject.wordpress.com/"
./src/mainwindow_help.cpp:      QStringLiteral("<a href=\"http://octopiproject.wordpress.com\">http://octopiproject.wordpress.com</a>.</p></h4><br>");
```

**Comment by aarnt** [comment]
https://github.com/aarnt/octopi/commit/e2c87e2c50c178db4739b2b213f275d17948c07a

Thank you very much!

**Comment by simonbcn** [comment]
It fails too in the PKGBUILD provided in this repository: https://github.com/aarnt/octopi/blob/master/PKGBUILD#L5
