### ISSUE TITLE
Tray icon almost invisible

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#434]
```
Operating System: Arch Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.1
Octopi Versión: 0.10.0 (dev) 
```
When there are upgrades the icon turns almost invisible instead red.
![captura_20200330_144144](https://user-images.githubusercontent.com/428231/77913708-0652ba80-7295-11ea-84be-cedd03f2ff10.png)

**Comment by aarnt** [comment]
This is weird. 
This icon is designed to represent the checking for updates action.

**Comment by simonbcn** [comment]
If I click on it, it refreshes and shows the right color (red).

**Comment by simonbcn** [comment]
On the other hand, when I click on the notification, it does nothing.  It should open the update window directly.

**Comment by simonbcn** [comment]
Today it works well. Perhaps a recent KDE update has corrected this.

**Comment by simonbcn** [comment]
It happens again.

**Comment by simonbcn** [comment]
It's very difficult to find out where the problem is.
I have configured the system tray so that the Octopi icon only it's showed when it's important.
Lately the icon appears in green but it should be red because there are pending updates. It changes to red when I click on it.
![Peek 12-04-2020 10-35](https://user-images.githubusercontent.com/428231/79064638-dbac2d00-7caa-11ea-9b96-0b0fa8a31824.gif)

**Comment by simonbcn** [comment]
Another example:
![Peek 13-04-2020 10-37](https://user-images.githubusercontent.com/428231/79106715-52146200-7d73-11ea-8ae7-a9faf52933e6.gif)

**Comment by aarnt** [comment]
Ok. Can you do a test?
Just go to a terminal and type:

`/usr/bin/octopi-notifier -d`

Then watch the outputs there when you walk with your cursor and the icon changes its color.

**Comment by simonbcn** [comment]
```
$ /usr/bin/octopi-notifier -d
"Octopi Notifier - 0.10.0 (dev) (Qt 5.14.2)"
At refreshAppIcon()...
Got a GREEN icon!
10:36 : At checkUpdates()...
At afterCheckUpdates()...
At refreshAppIcon()...
Got a RED icon!
```

But the icon:
![captura_20200421_103711](https://user-images.githubusercontent.com/428231/79844611-2f5dfb00-83bc-11ea-9583-8fd03a03d807.png)

**Comment by DobromirM** [comment]
I have the same issue and was able to reproduce the last test from @simonbcn. 

When I start the notifier the icon is green, then if it checks for updates and finds something it becomes grayed out until clicked with the left button. This can be repeated by restarting the notifier.

```
OS: Manjaro 20.0 Lysia
KDE 5.69.0 / Plasma 5.18.4
Qt version 5.14.2
octopi-notifier: 0.9.0-23
```

**Comment by aarnt** [comment]
Could any of you install LXQt to test this issue? I'm suspecting of plasma panel.

**Comment by simonbcn** [comment]
I have indicated the icons manually to test if this works correctly. But there is one icon I can't find in the Octopi package: the busy icon. I have put, for the moment, the yellow icon.
![captura_20200428_133014](https://user-images.githubusercontent.com/428231/80482415-79af2100-8954-11ea-89b5-95b14bfa1fa9.png)

**Comment by shaneramone** [comment]
I think this will be fixed in plasma 5.18.5

https://pointieststick.com/2020/05/08/this-week-in-kde-get-new-clipped-subsurface-dolphin-folder-sizes/

**Comment by MatMoul** [comment]
I encountered the same problem and not only with octopi...
Latest Plasma updates have resolved it ;)

**Comment by simonbcn** [comment]
Yes, it works well for me too.
I close the issue.
