### ISSUE TITLE
[Feature Request] qtermwidget basic settings

### ISSUE THREAD

**Issue by shaneramone** [aarnt/octopi#435]
Hello, thank you for this amazing project, it is my favourite package management GUI. I notice that qtermwidget ships with colour schema. Would it be possible for octopi to set some basic preferences in relation to the integrated terminal?

I was thinking something along the lines of:

Colour Scheme
Font
Font size

I did ask over at the qtermwidget github if it was possible to set these preferences through a config file of some description but was told that qtermwidget is unable to do this on it's own and would need to be handled by the application that it is embedded in.

https://github.com/lxqt/qtermwidget/issues/332#issuecomment-605781762

Many thanks for your consideration

**Comment by aarnt** [comment]
@shaneramone 
Thanks for the compliments.

Regarding terminal, currently Octopi supports changing font size. Just right click terminal and select "zoom in" or "zoom out".

Color options would have to be programed (if possible).

**Comment by aarnt** [comment]
Using upstream code you can now add 3 more terminal related settings in "~/.config/octopi/octopi.conf". For instance:

- Terminal_Font_Color_Scheme=BlackOnWhite
- Terminal_Font_Family=Hack Nerd Font
- Terminal_Font_Point_Size=10.0

For a list of available color schemes see: https://github.com/lxqt/qtermwidget/tree/master/lib/color-schemes

**Comment by fn-ix** [comment]
The `Terminal_Font_Color_Scheme` setting has no effect for me. 
Octopi 0.11.0
Qt 5.15.2

**Comment by Ved-un** [comment]
> The `Terminal_Font_Color_Scheme` setting has no effect for me. Octopi 0.11.0 Qt 5.15.2

Even though it's been a year, I'll answer anyway. Maybe someone will come in handy.
**Terminal_Font_Color_Scheme** is a typo and should be
**Terminal_Color_Scheme**

This works for me:
```
Terminal_Color_Scheme=Tango
Terminal_Font_Family=Iosevka SS18
Terminal_Font_Point_Size=9.0
```
