### ISSUE TITLE
Octopi thinks AUR upgrade is still running when completed through octopi-notifier

### ISSUE THREAD

**Issue by mputterf** [aarnt/octopi#436]
When you upgrade an AUR package by clicking on the system tray icon, it upgrades. However, after it completes the upgrade, octopi still thinks the the command is running and presents you with an error when you try to close the window. Luckily nothing breaks as the upgrade has already finished. Upgrading through the main octopi window's embedded console works fine.
![octopi-notifier-aur-upgrade-still-running](https://user-images.githubusercontent.com/46777241/78083255-c7426900-7369-11ea-85eb-0f2a741c6efc.png)

**Comment by aarnt** [comment]
@mputterf 

Could you test latest commit ?
There was a problem with AUR upgrades not setting an executing flag.
Maybe it also fixes your issue.

**Comment by mputterf** [comment]
@aarnt Yes, that fixed the issue. Thank you!

**Comment by simonbcn** [comment]
```
Arch Linux
Octopi Versión: 0.10.0 (dev) 
Qt 5.14.1
zsh 5.8
yay v9.4.6.r4.g6bd9202 - libalpm v12.0.1
```
When I click to upgrade an AUR package this is the command Octopi uses: `zsh -c "yay --noconfirm  -S <package/s> ;echo 'Press any key to continue...'"`

1. `yay` doesn't have a `noconfirm` option. This option should be changed depending on the AUR helper used.
2. A `read` is missing to wait for a keystroke and an `exit` to close the update window.
3. In the case of the AUR upgrade window it should not use the user's default shell but a generic one: `bash`.

As it is now, the window does not close when I press a key and the shell remains open. If I close the window manually, a message appears warning "_Canceling the execution of the transaction may damage your system!_"
![captura_20200402_105848](https://user-images.githubusercontent.com/428231/78230083-25d62700-74d1-11ea-8b3b-05151db99bfd.png)

I think the right command would be: `sh -c "yay -S <package/s>;  read -p 'Press any key to continue...' -n 1 -s; exit;"`
