### ISSUE TITLE
TERM variable not set in Octopi terminal

### ISSUE THREAD

**Issue by RichardNutt** [aarnt/octopi#437]
I am currently using the fish shell and am trying to get it to work with Octopi. Unfortunately it seems as if the Octopi terminal does not set the `TERM` variable, which results in the following message from fish:
```
<W> fish: Could not set up terminal.
<W> fish: TERM environment variable not set.
Welcome to fish, the friendly interactive shell    
richardrichard-pc@~ >
```
To my understanding it is used to let the shell/other programs know the graphical output options of the given terminal. Is there some sort of config file to set such variables for the Octopi terminal?

When creating a new user the problem persists. Note that qterminal itself sets 
```
COLORTERM truecolor
TERM xterm-256color
```

I am running:
```
richard@richard-pc ~> inxi -S
System:    Host: richard-pc Kernel: 5.4.28-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.18.3 Distro: Manjaro Linux
```

**Comment by aarnt** [comment]
@RichardNutt 
Can you test latest git code? I added the two variables on main.cpp.

**Comment by mputterf** [comment]
@aarnt I don't think xterm needs to be set as a dependency. When I set `export TERM=xterm-256color` in my .zshrc before this commit,  the `TERM environment variable not set` error went away and enabled color in the terminal.

**Comment by aarnt** [comment]
@mputterf 
Hmm... and you do not have xterm installed?

**Comment by shaneramone** [comment]
Xterm is not required to set xterm-256color as an environment variable. You can set that as an environment variable in any terminal emulator without xterm installed.

**Comment by aarnt** [comment]
Ok.

**Comment by RichardNutt** [comment]
I built Octopi from source and the variables are set now. Thank you :)
