### ISSUE TITLE
Misleading german translation

### ISSUE THREAD

**Issue by Erim24** [aarnt/octopi#440]
Hello all,

In the options dialog under the tab for AUR there is an option that says: "Nach veralteten AUR Paketen suchen" ("Search for outdated AUR packages").
That's the correct translation of the english phrase, however in my opinion it is not clear what it means (which is to search for updates for AUR packages)
I would therefore suggest to change the translation to something like: "Nach Updates für AUR Pakete suchen"

Thanks, Erim

**Comment by aarnt** [comment]
Hi @Erim24 ,
Thanks for your feedback. Would you like to participate in the Octopi's translation effort?
If you would, please take a look at:
https://www.transifex.com/arnt/octopi/

**Comment by aarnt** [comment]
I'm closing this as my suggestion was already made.
