### ISSUE TITLE
It doesn't detect updates in AUR git packages

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#442]
```
Arch Linux
Octopi 0.10.0 (dev) 
Qt 5.14.2
Pacman 5.2.1
pacaur 4.8.6
```

I have enabled "_Search updates in AUR_" in Octopi but it doesn't detect updates in AUR git packages.

**Comment by aarnt** [comment]
Hi,
I use same OS and package versions and Octopi gives me this output with pacaur:

```
Name  Outdated version  Available version
vivaldi  2.11.1811.52-1     3.0.1874.32-1
```

**Comment by simonbcn** [comment]
I explained it wrong. I mean that octopi only detects updates in _normal_ AUR packages, but it doesn't detect them in `...-git` packages installed from AUR. 

```
$ pacaur -Qqu -a --devel --needed
auracle-git
octopi-git
thermald-git
```
Those packages need upgrade but Octopi doesn't detect it.
I think it should update them too or add an option on the `AUR Options` tab to decide whether it checks the dev packages or not.

**Comment by aarnt** [comment]
Updated Options dialog on upstream.

**Comment by simonbcn** [comment]
Thanks, I've compiled and tested and it needs `--needed` option too. Otherwise `pacaur`, `yay`, etc... will warn that all `...-git` AUR packages need to be compiled again and again as it is happening to me now.

**Comment by simonbcn** [comment]
I have forked the git repository and changed the relevant part: https://github.com/simonbcn/octopi/commit/e7c6f2b1c8fdf31b53c8cadb3b5b4e1937303014 and it works well with `pacaur` and `yay`.
