### ISSUE TITLE
It alerts always the devel AUR updates

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#444]
After the change https://github.com/aarnt/octopi/issues/442 now it alerts always the devel AUR updates even the package is updated to the last devel version. 
It needs `--needed` option too. Otherwise `pacaur`, `yay`, etc... will warn that all devel AUR packages need to be compiled again and again.
I have forked the git repository and changed the relevant part: https://github.com/simonbcn/octopi/commit/e7c6f2b1c8fdf31b53c8cadb3b5b4e1937303014 and it works well with `pacaur` and `yay`.

**Comment by aarnt** [comment]
As I said:
"Here in my OS "pacaur -Qua --devel --needed" is not an option as it takes minutes to return and leads to no git packages needing upgrade."

**Comment by simonbcn** [comment]
`pacaur` (_`yay` and others_) with these options (`-Qua --devel --needed`) alerts if updates are needed in both devel and standard AUR packages. That's the way it works. The `--needed` option makes no difference when upgrading standard AUR packages.
The time it takes to check for updates depends on the number of AUR devel packages you have installed on your system. But Octopi doesn't do it well, since it doesn't allow to close the update window (_of non-AUR packages_) while checking for updates in AUR packages. The check should always be done in the background.

**Comment by aarnt** [comment]
> But Octopi doesn't do it well, since it doesn't allow to close the update window (of non-AUR packages) while checking for updates in AUR packages. The check should always be done in the background.

Could you explain your point? First, are we talking about octopi notifier or plain octopi?

**Comment by simonbcn** [comment]
`octopi-notifier` continually notifies of updates for packages in development of AUR if `--devel` is indicated but not `--needed`.

Now you see this screen capture:
![Peek 03-05-2020 15-04](https://user-images.githubusercontent.com/428231/80915087-15bf9a80-8d50-11ea-8be7-e32faf607144.gif)

This is the update window that `octopi-notifier` opens when there are updates in the official Arch repositories. But after the update is completed, I click on the close window button but it doesn't close immediately. Why? Because I think it's checking for updates on AUR.  This check should be made in background and regardless of whether that window is open or closed.

**Comment by aarnt** [comment]
@simonbcn 
Can you test latest dev code?

**Comment by simonbcn** [comment]
Yes, it works well now. Thanks.
