### ISSUE TITLE
Enable more flexibility in columns

### ISSUE THREAD

**Issue by mardab** [aarnt/octopi#447]
Speaking of columns (#445 ), why not just add more columns (such as "installed size", "license", "install reason", etc.) and a menu to toggle visibility of columns? Not only it would "fix" #445 before cause of it is known , but in my honest opinion it would be a much needed boost to productivity.

**Comment by azizLIGHT** [comment]
Another use case for columns: "build date" so that you can sort and find the older packages on the system from the AUR

**Comment by aarnt** [comment]
@mardab @azizLIGHT 
Columns added and available at an options dialog (Package List tab) click.

Time to star the project!

**Comment by azizLIGHT** [comment]
Thanks! I can now easily find AUR packages sorted by build date like this:
![image](https://user-images.githubusercontent.com/8013867/95663612-afb11d80-0b0e-11eb-8b39-4b96813a0520.png)

**Comment by aarnt** [comment]
Great!
