### ISSUE TITLE
Crashes with "stack smashing detected"

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [aarnt/octopi#448]
When I attempt to open up Octopi, it immidently crashes with the message

> *** stack smashing detected ***: terminated
> [1]    25504 abort (core dumped)  octopi

The issue exists with octopi, octopi-dev, and octopi-git on Manjaro

**Comment by barfin** [comment]
same problem here

**Comment by aarnt** [comment]
I cannot replicate this issue.
I'd need more data.

**Comment by mefsaal** [comment]
Hi, same issue 
![Screenshot_20200521_225202](https://user-images.githubusercontent.com/56521591/82623112-c84b8600-9bb5-11ea-82a5-b3362cdc1493.png)

**Comment by aarnt** [comment]
And??
All of you use Manjaro? 
All on zsh Shell?
All compiled octopi from sources?

**Comment by mefsaal** [comment]
> Archtecture? Cpu?
> All of you use Manjaro?
> Do Octopi-Notifier and Octopi-CacheCleaner crash too?
> All on zsh Shell?
> All compiled octopi from sources?
> 
> Could any of you make this test:
> 
> - git clone Octopi
> - Modify octopi.pro to comment lines 12 to 16
> - qmake
> - make
> - Run bin/octopi and test if it crashes
>   
> 

Hi, sorry. My mistake jajaj 


Os: Archlinux x64
Only crashes octopi. Octopi-notifier works 100% for me.
Bash o zsh same results.
Compiled by makepkg in the source files.

**Comment by aarnt** [comment]
@mefsaal 
Could you make this test:
 - git clone Octopi
 - Modify octopi.pro to comment lines 12 to 16
 - qmake
 - make
 - Run bin/octopi and test if it crashes

**Comment by Itamiko** [comment]
CPU: AMD Ryzen 5 2600 Six-Core
ARCH: x86_64
Shell: Bash & Zsh
Distro: Manjaro kde 20

I have commented out lines 12-16 and built the application but still getting a crash. upon opening the application

**octopi output**
```bash
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 553, resource id: 0, major code: 18 (ChangeProperty), minor code: 0
*** stack smashing detected ***: terminated
zsh: abort (core dumped)  ./bin/octopi
```

seems to be the cause when setting a breakpoint on L657 & L659
https://github.com/aarnt/octopi/blob/28e4c0f9897832ece12a60e9282d935ba20ae1ee/src/package.cpp#L658

**Comment by aarnt** [comment]
@Itamiko 
See if you have a "~/.config/octopi/octopi.conf" created. 
If so, change the line which says "Backend=" to "Backend=pacman".
Then start octopi again.

**Comment by Itamiko** [comment]
Changing the backend solves this. It works on either building source or manjaro packaged

**Comment by aarnt** [comment]
@Itamiko 
Ok.
Grab https://github.com/aarnt/alpm_octopi_utils and make/make install it (you'll need vala compiler).
Then remove that "pacman" string from octopi.conf to test again.

**Comment by Itamiko** [comment]
removing pacman to nothing works, but changing the backend to alpm crashes with the repo built alpm_octopi_utils

**Comment by aarnt** [comment]
@Itamiko 
You are right I meant "alpm". 
But this crash is very weird. Why does it happen for ones and not for others?

**Comment by aarnt** [comment]
What is your vala compiler version?

**Comment by Itamiko** [comment]
Vala 0.48.5

**Comment by aarnt** [comment]
Do you remember when you start getting this error?

**Comment by Itamiko** [comment]
I remember it was after some package installation like for aur backend

**Comment by aarnt** [comment]
What aur backend are you using?

**Comment by Itamiko** [comment]
trizen and pacaur

I know it was when I removed pacaur then installed trizen it worked but after some aur package installations with octopi it started, once I closed and opened it again it just crashed

**Comment by aarnt** [comment]
Maybe you had some upgrades on other packages in the meantime?

**Comment by aarnt** [comment]
@Itamiko 
Could you test latest commit https://github.com/aarnt/octopi/commit/1c578367b7f25afe1bf4e97fa77173f18389ef28  ?
Then use "alpm" in octopi.conf...

**Comment by mefsaal** [comment]
> @Itamiko
> Could you test latest commit [1c57836](https://github.com/aarnt/octopi/commit/1c578367b7f25afe1bf4e97fa77173f18389ef28) ?
> Then use "alpm" in octopi.conf...

with the last commit, and change octopi.conf "backend=alpm" still crashes.

**Comment by aarnt** [comment]
@mefsaal @Itamiko 
Could you make this test:

- Goto "src/alpmbackend.cpp"
- Change line 96 from "char size[10];" to "char size[20];"
- Compile and see if it helps.

**Comment by mefsaal** [comment]
> @mefsaal @Itamiko
> Could you make this test:
> 
>     * Goto "src/alpmbackend.cpp"
> 
>     * Change line 96 from "char size[10];" to "char size[20];"
> 
>     * Compile and see if it helps.

whit this, octopi dont crash. and work fully with alpm backend

**Comment by aarnt** [comment]
\o/
I'll revert some changes and add that update.

**Comment by aarnt** [comment]
@mefsaal  @Itamiko 
Can you test https://github.com/aarnt/octopi/commit/f3a14edab0160e0bdadf2542c8fb52cacd134df6 ?

**Comment by mefsaal** [comment]
> @mefsaal @Itamiko
> Can you test [f3a14ed](https://github.com/aarnt/octopi/commit/f3a14edab0160e0bdadf2542c8fb52cacd134df6) ?

Yes, fully work for me.

**Comment by aarnt** [comment]
@CommunistWitchDoctor 
Can you test latest code so this ticket can be closed?
