### ISSUE TITLE
PKGBUILD : optdepends missing

### ISSUE THREAD

**Issue by MatMoul** [aarnt/octopi#449]
Looking to update the arch package but I'm not sure what I need to do with optdepends...
Arch current PKGBUILD :
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=octopi-dev
Octopi PKGBUILD :
https://github.com/aarnt/octopi/blob/master/PKGBUILD

**Comment by aarnt** [comment]
Hi @MatMoul 
For version 0.10.0 those optdepends still make sense:

'pacaur: for AUR support'
'pikaur: for AUR support'
'trizen: for AUR support'
'yay: for AUR support'
'pacmanlogviewer: to view pacman log files'

**Comment by MatMoul** [comment]
Thanks. closing issue and new release for ArchLinux is online ;)

**Comment by aarnt** [comment]
@MatMoul 
Thanks. Could you also update url to https://tintaescura.com/projects/octopi ?

**Comment by MatMoul** [comment]
@aarnt No problem, I'll update it on the next update...
I've opened a thread on archfi forum :
https://bbs.archlinux.org/viewtopic.php?id=257534
The 0 release is an error and I will update soon to release 1 with your request.
