### ISSUE TITLE
Why doesn't it sometimes give me the "Yes" option in the update window?

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#450]
Sometimes when I click on the update tray icon (_packages from repositories, not AUR_) it opens a dialog in which it only gives me the option to update from terminal. Why?

![captura_20200524_095047](https://user-images.githubusercontent.com/428231/82749138-72d6cb00-9da7-11ea-814a-202bc143de6c.png)

**Comment by aarnt** [comment]
This is by design.
Whenever pacman is one of the updates, octopi forces user to execute in a terminal.
I once had a bricked system using automatic upgrades with a pacman new version that needed user interaction.
Believe me, it's much safer now.

**Comment by simonbcn** [comment]
Thanks.
