### ISSUE TITLE
URL font in package info too small

### ISSUE THREAD

**Issue by syntaxman** [aarnt/octopi#451]
When listing the information of a package in the lower window,  all the fonts are uniform and readable except the actual URL value.  The URL label is fine.  This caused a problem for me (presumably because my display is HiDPI), and the URL text was too small to read.

Octopi
Version: 0.9.0 - Qt 5.15.0
Pacman
Version: 5.2.1
![image](https://user-images.githubusercontent.com/7008765/86523139-c283ca00-be1c-11ea-9a7f-6dfe7091f2e6.png)

**Comment by aarnt** [comment]
@syntaxman 

Upstream version 0.10.0 fixed that issue.
