### ISSUE TITLE
"trizen" and "pikaur" doesn't work well with "--devel" packages

### ISSUE THREAD

**Issue by simonbcn** [aarnt/octopi#453]
Due to a serious [`yay` error when showing the differences between versions](https://github.com/Jguer/yay/issues/1109) of the PKGBUILD, I had to go to other options but I found that they give problems with `octopi` and devel packages:

### `trizen` 
`octopi` says there is an upgrade but the command executed says nothing to upgrade:
![captura_20200728_105323](https://user-images.githubusercontent.com/428231/88642279-9298b100-d0c0-11ea-89ea-3fcc03fc52ea.png)

In console `trizen` says there is no update:
```
$ trizen -S --aur --devel --needed
$ echo $?
0
```

### `pikaur` 
In this case `octopi` says there are 2 upgrades **always**:
![captura_20200728_110135](https://user-images.githubusercontent.com/428231/88643234-bc060c80-d0c1-11ea-95c1-b88c8a3f0623.png)

But in console `pikaur` says there is no update:
```
$ pikaur -S --aur --devel --needed
Reading the local package database...
Reading package databases...
:: there's nothing to do.
```

### `pacaur` 
It's an abandoned project. :disappointed:

**Comment by aarnt** [comment]
@simonbcn 

Least Common Multiple solution that comes to my mind: remove "--devel" option.
