### ISSUE TITLE
Sysinfo buggy output (adds <HOSTNAME> to each character)

### ISSUE THREAD

**Issue by petsam** [aarnt/octopi#454]
The GUI Sysinfo command produced a huge (>10MB) file.
It seemed the command had added `<HOSTNAME>` text to **each** character in the output.
I was able to get a _cleaned_ output file (as the intended one) with
```
cat octopi-sysinfo-2889952610.log | sed 's/<HOSTNAME>//g' | sed 's/<HOSTNAME>//g' | sed 's/<HOSTNAME>//g' | sed 's/<HOSTNAME>//g'  > octopi-sysinfo.log
```
(not an expert in bash, sorry...)

In Archlinux, I installed octopi from AUR.
```
octopi 0.10.0-1
systemd 246.1-1
qt5-base 5.15.0-4

Operating System: Arch Linux (stable)
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.7.12-arch1-1
OS Type: 64-bit
```

**Comment by aarnt** [comment]
You mean it changed your hostname to the <HOSTNAME> string, don't you?
This is by design in case you need to publish this file in a pastebin service for help.

**Comment by petsam** [comment]
> it changed your hostname to the string, don't you?

No. I mean it **added** the text `<HOSTNAME>` to each individual character.
For example, this is the output of `vendor: Lenovo`:
```
 <HOSTNAME>v<HOSTNAME>e<HOSTNAME>n<HOSTNAME>d<HOSTNAME>o<HOSTNAME>r<HOSTNAME>:<HOSTNAME> <HOSTNAME>L<HOSTNAME>e<HOSTNAME>n<HOSTNAME>o<HOSTNAME>v<HOSTNAME>o<HOSTNAME>
```

**Comment by aarnt** [comment]
Hum, ok. 
It'll need some testing then.

**Comment by demmm** [comment]
In case helpful, no such issues on KaOS, only place were <HOSTNAME> is added (as should) is in the journalctl -b -p err section.

**Comment by aarnt** [comment]
@demmm 
Thanks for the Info.

**Comment by aarnt** [comment]
String replace code was removed from upstream.
reason1: the file is locally generated
reason2: obfuscation method was poor
reason3: users should be responsible for what they upload to the cloud
