### ISSUE TITLE
PKGBUILD idea

### ISSUE THREAD

**Issue by MatMoul** [aarnt/octopi#455]
Thanks for the new release...

Looking on the PKGBUILD, and the ArchLinux PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=octopi
The for do done seem a very good solution...
The code isn't from me and I've lost the owner of this code but it is more readable as the current PKGBUILD.

What do you think?

**Comment by aarnt** [comment]
Hi @MatMoul 
Yes, it's nice. We can implement of course. Thanks.

**Comment by aarnt** [comment]
@MatMoul 
Upstream code is updated!
