### ISSUE TITLE
Calamares dropped user's setting the updates interval

### ISSUE THREAD

**Issue by linuxergr** [aarnt/octopi#456]
I have noticed that the setting the updates interval feature, by the user, has been recently removed from octopi, and that is really a missing one.

Please consider to add it back.

Regards

**Comment by aarnt** [comment]
Hi @linuxergr 

The Updates tab is not visible from Octopi. You have to open "Options" from Octopi Notifier instead.
This option was always a notifier only one.

**Comment by linuxergr** [comment]
Thank you very much for your feedback
