### ISSUE TITLE
Enable-Downgrade Option

### ISSUE THREAD

**Issue by UltraBlackLinux** [aarnt/octopi#458]
Hey there, 
I have made the discovery in the past, that if I didn't enable downgrade of packages while updating (pacman -Syyuu) my system broke and would not boot up anymore, so please add an option for it, so I can use octopi while not risking my system stability.
Thanks!

**Comment by aarnt** [comment]
@UltraBlackLinux 

If you are prone to have such issues while upgrading it's better to do a manual upgrade inside a terminal.
Pacman distros are meant to be rolling and "pacman -Syu" is the documented way to go.

In other words: "this is not a use case for a normal user. Downgrading while upgrading should NEVER be needed".
