### ISSUE TITLE
AUR voting does not work

### ISSUE THREAD

**Issue by linuxergr** [aarnt/octopi#459]
Hi

Latest Octopi release 0.10.0, does not login to AUR for voting, although the credentials are correct.

**Comment by aarnt** [comment]
@linuxergr 
It works for me.
Which language are you using in you AUR account?
Did you try using "/usr/bin/octopi -d" to see what is being output?

**Comment by linuxergr** [comment]
Hi @aarnt 

I use English on my account.

![Screenshot](https://i.imgur.com/QhJSoud.png)

and the ouput of /usr/bin/octopi -d when the above occurs, is pasted at [https://paste.artixlinux.org/view/a8ea7048](url)

**Comment by aarnt** [comment]
Hi @linuxergr 
Thanks for the feedback.

What is your password length?

**Comment by linuxergr** [comment]
This cannot be revealed, sorry, but is a security matter

**Comment by aarnt** [comment]
Ok.
I Just asked to try to solve your issue.
Besides you can always change passwords.

**Comment by linuxergr** [comment]
Is there any maximum length on AUR for passwords?
If so, the same should be used in this case.

Regards

**Comment by aarnt** [comment]
@linuxergr 
I'll check that.
But you can login in their site, can't you?

**Comment by linuxergr** [comment]
@aarnt of course I login.

btw, let me tell you also that aurvote works ootb, but aur-vote does not, if this can assist you further

**Comment by aarnt** [comment]
@linuxergr,
Tested with a 80-length here and passed.
I really do not know how to troubleshoot... any idea?

**Comment by linuxergr** [comment]
@aarnt Good
Happy to assist further, but perhaps this should be better addressed through IRC Freenode with PMs.
Can we meet at #artix, or any other channel? (my nick is linuxer, or linuxer_ or linuxer__)

Regards

**Comment by aarnt** [comment]
@linuxergr 
Great Idea. I'll meet you there asap.

**Comment by linuxergr** [comment]
@aarnt thanks for your patience and assistance!

Regards
