### ISSUE TITLE
[Feature request] Open PKGBUILD in text editor

### ISSUE THREAD

**Issue by axzxc1236** [aarnt/octopi#460]
Right now what I do is click on the link in information tab -> wait for browser to load page -> click on "View PKGBUILD"

Maybe I am just too lazy but I think have a "Open PKGBUILD in text editor" option in right click menu is a good idea.

(maybe view diff in text editor too?)

**Comment by aarnt** [comment]
@axzxc1236 
Implemented "Open PKGBUILD" in upstream code.

Is there a way to access "view diff" in plain text? Because I've only found this info in html.

**Comment by axzxc1236** [comment]
I guess there is no way..... there is no documentation of web API of cgit that I can find.

The best I could do involves git commands.... something like

```
git clone https://aur.archlinux.org/octopi.git --depth=2 --bare /tmp/_tmp_show_diff
cd /tmp/_tmp_show_diff
git show > /tmp/_diff
xdg-open /tmp/_diff    only works if user have xdg-utils installed
rm -rf /tmp/_tmp_show_diff
```

I guess I can make above commands a .sh file on my system instead.

**Comment by axzxc1236** [comment]
I think I've found a better way to do this.

In "log" page there are urls of commits that you can click into

for example https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=octopi&id=c1e29a54680cb71236d677103eaf2a3e7499140c

now change /commit/ to /plain/, like https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=octopi&id=c1e29a54680cb71236d677103eaf2a3e7499140c

you will see the PKGBUILD file of that commit, change the id to get previous PKGBUILD file and then you can diff them yourself.

**Comment by aarnt** [comment]
Hi @axzxc1236 

Added "Show PKGBUILD diff" option in upstream code.
Can you test to see if that's what you were thinking?

**Comment by axzxc1236** [comment]
Hmm...... no

sometimes I get a file with html webpage source code and it includes something like `Invalid branch: linux-mainline-headers` (both view PKGBUILD and view PKGBUILD diff has this problem)  
sometimes view diff doesn't work at all (for example `linux-ck-headers`, 100% doesn't work on view diff), no error messages in terminal, no file in /tmp folder

I briefly looked into linux-ck-headers, change /commit/ to [/plain/](https://aur.archlinux.org/cgit/aur.git/plain/?h=linux-ck&id=2b8fdabeb4599f0970a492ce16e9ec5aca7c8ec4) doesn't work like it does with octopi, it fails when there are multiple changes in commit.  
Also its PKGBUILD url is https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=**linux-ck**, not https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=**linux-ck-headers**

**Comment by aarnt** [comment]
Give all examples from all error types.
I mean all pkg names you testes.

**Comment by axzxc1236** [comment]
No problem detected:
```
jdk
jdk8
jdk7
jdk6
jdk-docs
top 5 [most voted AUR packages](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=&outdated=&SB=v&SO=d&PP=50&do_Search=Go)
plymouth
linux-ck
linux-mainline
```

PKGBUILD with invalid branch error, also the same list that diff isn't working:
```
jre8-adoptopenjdk-headless (Package Base: java8-adoptopenjdk)
openj9-src (Package Base: java-openj9)
openjdk8-shenandoah-src (Package Base: java8-openjdk-shenandoah)
jre-openj9 (Package Base: java-openj9)
jre-openj9-headless (Package Base: java-openj9)
linux-ck-headers (Package Base: linux-ck)
linux-mainline-headers (Package Base: linux-mainline)
linux-mainline-docs (Package Base: linux-mainline)
```

At this point I am very confident about it has to do with Package Base.... I don't want to do more testing at this moment

**Comment by aarnt** [comment]
Ok.
I'm working on a patch.

**Comment by aarnt** [comment]
Implemented Package Base retrieval.

**Comment by axzxc1236** [comment]
I've reinstalled octopi-git and can confirm the features works correctly now. (other than the diff shows timestamp of when commits are downloaded, instead of when commits happened. But I don't think that's important)

Thank you aarnt.
