### ISSUE TITLE
Small bug on qterminal, if any package does not build from AUR, it does not exit normally

### ISSUE THREAD

**Issue by linuxergr** [aarnt/octopi#461]
How to reproduce:

When using octopi to build any package from AUR, if it fails, the terminal and Octopi stucks on a non finished process stage, i.e. tabs Info, Files and so on, are on disabled stage, so the user has to press ctrl+x or 'exit' in order to return to normal stage and have all tabs back.

**Comment by aarnt** [comment]
@linuxergr 
Indeed there are such situations.
Do you recall the package you were trying to compile?

**Comment by linuxergr** [comment]
Ki @aarnt 

iirc one is the hw-probe from AUR, that can be tested (yesterday was failing to build)

**Comment by aarnt** [comment]
Hi @linuxergr 
I was able to install both hw-probe and the git version. Maybe it was another?

**Comment by linuxergr** [comment]
I cannot recall this very moment, but we can make a quick test, while we can arrange that on IRC, with one of my packages on AUR, for testing purposes.

Just ping me @aarnt, by tomorrow

**Comment by linuxergr** [comment]
@aarnt ping me, when you have the time to do so, on IRC

**Comment by linuxergr** [comment]
https://github.com/aarnt/octopi/commit/34d38280ff9c3e7d80439c87c46674f957566b06
