### ISSUE TITLE
Segmentation fault, latest commit a7cf805cda77347f080db2de400da547dd1a1da5, Artix Linux

### ISSUE THREAD

**Issue by linuxergr** [aarnt/octopi#462]
@aarnt 

Unfortunately lately (right after my previous issue) segmantation fault occurs on my octopi build.

I dedugged octopi for the problem with GDB, and the error seems to occur due to QStandardItem::rowCount() const ().

Check my attached debug:

[octopi-debug-20201120.txt](https://github.com/aarnt/octopi/files/5575578/octopi-debug-20201120.txt)

I hope it helps

Regards

**Comment by aarnt** [comment]
@linuxergr 
Ok.
Did you recognize some action that always trigger the fault?

**Comment by linuxergr** [comment]
@aarnt  Yes, forgot to tell

Right click-->Install, cause ir

Easy to reproduce

**Comment by aarnt** [comment]
@linuxergr 
Fixed upstream, thanks.
