### ISSUE TITLE
Octopi checks twice for updates

### ISSUE THREAD

**Issue by bcoolumbo1** [aarnt/octopi#463]
Open Octopi
Press button "Check updates"
Press "Install" or "System upgrade"
Instead of upgrading it checks again for updates...
Then it updates.

This is unneeded traffic for all and everything. My opinion.

**Comment by aarnt** [comment]
@bcoolumbo1 
When you press check for updates, octopi issues a checkupdates command which downloads a temp database and checks if there are packages with a different version. 
This process is needed to ensure we did not enter a partial upgrade state.

So when you press the upgrade button, octopi issues a pacman -Syu command to synchronize and upgrade the actual package database.

At the end: two different commands despite reaching the same goals.
