### ISSUE TITLE
make error: ‘AlpmBackend’ has not been declared

### ISSUE THREAD

**Issue by bcoolumbo1** [aarnt/octopi#475]
[ 52%] Building CXX object cachecleaner/CMakeFiles/octopi-cachecleaner.dir/__/src/package.cpp.o
/usr/src/git-repositories/octopi/src/package.cpp: In static member function ‘static QList<PackageListData>* Package::getAURPackageList(const QString&)’:
/usr/src/git-repositories/octopi/src/package.cpp:1072:24: error: ‘AlpmBackend’ has not been declared
 1072 |     installedVersion = AlpmBackend::getPackageVersion(pkgName);
      |                        ^~~~~~~~~~~
make[2]: *** [cachecleaner/CMakeFiles/octopi-cachecleaner.dir/build.make:501: cachecleaner/CMakeFiles/octopi-cachecleaner.dir/__/src/package.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:449: cachecleaner/CMakeFiles/octopi-cachecleaner.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

Normal make and install after deleting the line
installedVersion = AlpmBackend::getPackageVersion(pkgName);
from package.cpp

alpm_octopi_utils is installed from AUR

**Comment by aarnt** [comment]
Hi @bcoolumbo1 

Try to use upstream code. It's compiling here.
