### ISSUE TITLE
[Suggestion] Pamac-cli support?

### ISSUE THREAD

**Issue by rain1598** [aarnt/octopi#476]
Because unlike some other AUR helpers, Pamac comes with the ability to install new software without reinstalling its dependencies. Also because pamac-gtk is incredibly buggy and pamac-qt requires an outdated version of pamac-common which does not exist in Arch repos.

**Comment by aarnt** [comment]
Octopi is a pacman frontend and I like it that way, but you can always fork the project and rename it.
