### ISSUE TITLE
notifier and octopi problem in communication

### ISSUE THREAD

**Issue by linuxergr** [aarnt/octopi#478]
Hi @aarnt 

Just check the steps below:

When the notifier icon is red and octopi is opened, the "check updates" must be pressed so to show them.

Even more, after the updates are done with octopi, you must "check updates" from the notifiers menu, so the notifier icon, to be changed back to green.

**Comment by aarnt** [comment]
Hi @linuxergr 

Indeed, the first issue is real as the program used is "checkupdates" and it's independent from notifier / octopi.

I'll take a look into the second.

**Comment by linuxergr** [comment]
Well, the second is real too :D :D :D

It occurred just before publishing this very issue.

Rather strange though, because it occurred kind of randomly, meaning that is not the expected behavior.

**Comment by aarnt** [comment]
Made some tests, but I don't think I can implement the desired sync behavior with current code.
Sorry.
