### ISSUE TITLE
Random AUR packages installation selection bugged

### ISSUE THREAD

**Issue by hockeymikey** [aarnt/octopi#479]
![Screenshot_20210317_124142](https://user-images.githubusercontent.com/1435185/111512886-39988e80-871e-11eb-91d1-94cda95bd52f.png)
When I attempt to install some AUR packages like in the picture attached, instead it returns "Display All Groups" for the package and will fail to install since that's not a package. Only effects certain random packages, I can do any other one after this one and it will work fine. Manual installation with yay works fine.

**Comment by aarnt** [comment]
@hockeymikey 

Are you using version 0.12 (dev) or 0.11 ?

I think it's fixed upstream as : 

0.12 (dev)

  Added support for Paru AUR tool.
  Added support for opendoas tool (default)
  BugFix: If there was only 1 result in AUR search, the pkg could not enter 
    the transaction with the right name.
  BugFix: If user went from AUR to normal search with a not found pkg the statusbar
    counters would become invisible.

**Comment by hockeymikey** [comment]
@aarnt 0.11. I'll report back when I can test the new version.

**Comment by aarnt** [comment]
Closing as no feedback was given.
