### ISSUE TITLE
Octopi hangs after update, notifier exists

### ISSUE THREAD

**Issue by miku84** [aarnt/octopi#480]
Hi,
On Manjaro Linux I noticed it many times that when I open octopi, it hangs, not responsible at all. All I could is just to kill it. I also noticed that octopi-notifier also exists. After I kill Octopi, I can run it next time without issue. I think it may had some trouble between notifier and Octopi because notifier is exited now. I need to start it again.

This issue happened now after system update, maybe caused by it.

**Comment by miku84** [comment]
After all update the issue persists.

**Comment by SummerBulb** [comment]
I have the same issue on Manajro

**Comment by aarnt** [comment]
@miku84 @SummerBulb 

Did you test if version 0.12.0 fixes this issue?

**Comment by miku84** [comment]
The issue seems not happening anymore, just tested it!
:)
