### ISSUE TITLE
Options menu for Octopi-notifier does not show correct if Octopi is open

### ISSUE THREAD

**Issue by demmm** [aarnt/octopi#481]
Issue is longstanding, just now figured the cause (can be reproduced with any version from the last year, still present in build from commit bfc98aebdb50b7e2b3ef57e55f571c8901ab0994)

Right click octopi-notifier in the panel, when octopi itself is not opened > options menu shows 3 tabs `General`, `Icon` & `Updates`, doing the same after main octopi window runs, the regular 4 tabs are shown, `Updates` no longer an option.
This has been reported quite a few times for KaOS:

>no way to adjust the updates intervals in KaOS

Which is a correct response for many, since they probably have octopi open.  Issue is gone once the main window is closed again.

**Comment by aarnt** [comment]
Hi @demmm 
Latest commit tries to fix the issue.

**Comment by aarnt** [comment]
Yes, thanks!
