### ISSUE TITLE
In the info tab: also list the package maintainer

### ISSUE THREAD

**Issue by xyproto** [aarnt/octopi#482]
Arch Linux packages have both "last packager" and "package maintainer".

In the "Info" tab, only the "last packager" is listed, as just "Packager".

This could easily make users contact the last packager instead of the package maintainer (which is the one that should ideally receive bug reports and questions about the package).

This is a feature request for using the package maintainer instead, or adding both "last packager" and "package maintainer".

Thanks for creating Octopi, I especially like that the website news are included in the GUI application!

**Comment by demmm** [comment]
Isn't that a website specific feature instead of pacman/libalpm output?  Is there a pacman command that list anything but just the packager (pacman -Sii) ?

**Comment by xyproto** [comment]
That's a good point! Neither `pacman -Sii` or `pacman -Qi` lists the package maintainer.

I guess it would have to be fetched from the web page if you should want to add this feature.

**Comment by aarnt** [comment]
If it's not available in pacman... I'm sorry.

**Comment by xyproto** [comment]
Thanks for considering the issue.
