### ISSUE TITLE
Tray shows ignored update when ALPM is used

### ISSUE THREAD

**Issue by DonaldSch** [aarnt/octopi#483]
I presume the following quote was correct 
> It doesn't show ignored updates in tray already. If it does for for you then you have to provide more info as it isn't reproducible.
> 
> _Originally posted by @Vincent43 in https://github.com/aarnt/octopi/issues/309#issuecomment-366440214_

but I'm getting a red tray icon and the only update shown in Octopi is for package 'proj' but I have 
`IgnorePkg   = proj`
in pacman.conf and it is the only IgnorePkg  line.
Octopi version 0.10.0 and Qt 5.15.1 pacman 5.2.2

**Comment by DonaldSch** [comment]
Just experimented with a few things and found that if I set options->Backend to pacman this problem goes away i.e. checking for updates shows a green icon and Octopi doesn't show any packages need updating!

Changing this setting back to ALMP + pacman immediately shows an up date so I guess it is to do with the way ALPM is used.
Shouldn't it operate the same way irrespective of this setting and be considered a bug?

Not sure how to change/fix this myself.

**Comment by aarnt** [comment]
Hi @DonaldSch 

Thanks for pointing out this bug.
I think it's fixed in upstream.
