### ISSUE TITLE
[enhancement] sudo replacement for polkit ?

### ISSUE THREAD

**Issue by class101** [aarnt/octopi#484]
Hey @aarnt and all the contibutors

Don't you think that getting ride of `sudo` in favor of `polkit` and `pkexec` would be a good "modern" move and makes less code to manage ? `rm -fr octopi-sudo` :zany_face:
I see more and more applications leaving the dependency to sudo in favor of `polkit` I find it cool because you just need to run 'pkexec _command_' and you get a gui prompt for the password.

![Screenshot from 2021-06-05 19-36-11](https://user-images.githubusercontent.com/1810484/120900560-9d539900-c635-11eb-814e-cfe36ee81b7c.png)

**Comment by aarnt** [comment]
@class101 

I've already tested this before and could not get pacman's output for commands.

Besides, all octo tools use lxqt-sudo code. So, it's not a burden to maintain.
