### ISSUE TITLE
AUR package "+update" option missing in some contexts

### ISSUE THREAD

**Issue by afarley** [aarnt/octopi#485]
In 11.0.X and 12.0.X, the option to "+update" AUR packages is missing when attempting to update the package from the list of installed AUR packages. That is going to View -> Installed and Repository -> AUR shows the list of installed AUR packages. However, there is no longer an (obvious) option with right clicking on the package to upgrade the package. Only the option to remove the installed AUR package. ...However, searching for the same upgradeable package in the AUR repository does provide the option to "+upgrade" with a right click.

If the preference is to upgrade all of the AUR packages from the AUR button/dialog at the bottom of the program window, that is fine. Though some AUR packages sometimes need some extra massaging to install and will block other packages from updating.

**Comment by aarnt** [comment]
@afarley 
This is now by design.
Starting from 0.11.x, we now have the option to stage more than 1 AUR pkg on the "Actions" tab. And if a user staged a mix of pacman/aur pkgs together, it could be hard to deal with.
