### ISSUE TITLE
Cannot launch "octopi" from terminal

### ISSUE THREAD

**Issue by SameExpert** [aarnt/octopi#487]
If tried launching `octopi` from terminal, it says:
> You must use "/usr/bin/octopi" to run Octopi

***

**Package:** octopi-dev (AUR)
**Version:** 0.12.0-3

**Comment by aarnt** [comment]
So?
You just follow the recomendation and launch it.
What is the problem?

**Comment by stevleibelt** [comment]
2024 and a freshly installed system from `cachyos-kde-linux-240609.iso` and still the same error when launching Octopi from start menu or via terminal `/usr/bin/octopi`.

Any more cool hints @aarnt?

Nevertheless, thanks for your work.

**Comment by lufusol** [comment]
6.20.2025 freshly installed system, same problem.  Come on, an out-of-the-box issue launching your basic package manager for over a year?  This should be a very high priority
