### ISSUE TITLE
[BUG] Octopi system tray custom icon don't work

### ISSUE THREAD

**Issue by DenysMb** [aarnt/octopi#489]
When we try to use custom icon in Octopi and change for any other icon, the icon don't show. We get only a "blank space", without any icon.
I tried to change to Papirus Octopi panel icons, to some generic breeze icon and nothing work.

**Comment by aarnt** [comment]
Which desktop environment are you using?

**Comment by DenysMb** [comment]
Sorry. I forgot about this opened issue. The problem is: Octopi doesn't allow SVG images as custom tray icon, only PNG images. When I selected a PNG image it worked.

**Comment by aarnt** [comment]
This is a qt issue. I cannot do anything.
