### ISSUE TITLE
Automatic switching to Actions view when a package is selected for installation is annoying

### ISSUE THREAD

**Issue by tntodorov** [aarnt/octopi#491]
When a package from the list has been selected for installation by the user, the application automatically switches from any of the `Info`, `Files`, `Output`, `News`, etc. views to `Actions`. This is superfluous and diminishes productivity when the user needs to select multiple packages. When a different package is selected, the user must select the `Info` or whatever view themselves. This is a very repetitive action when the user is browsing for software through a whole package group.

Why does the application even need to switch to the `Actions` view? I literally just selected a package for installation - I already know that it is going to be added to the list of other packages to be installed.

We either:
- need a setting to disable the automatic switch of views, or
- the actions information should be shown as a summary when the user hits `Apply`, or
- the view should automatically switch back to the original view, when a different package is selected, if the `Actions` view was switched to automatically

I am using Octopi 0.11.0 on Garuda Linux Dragonized KDE edition

**Comment by aarnt** [comment]
Updated behavior upstream.
