### ISSUE TITLE
[Request] Pushing a new stable release

### ISSUE THREAD

**Issue by dr460nf1r3** [aarnt/octopi#493]
A lot of time passed since the last stable release of Octopi. During that time, some much needed enhancements for Pacman 6 got added to the application. For distributions shipping Octopi as default GUI package manager, this is quite substantial. 
Therefore I'm kindly asking to push a new tag which features the fixes.
Thanks for your work! :)

**Comment by aarnt** [comment]
Hi @dr460nf1r3 

Can you test upstream version to see if it supports Garuda out of the box?

**Comment by spacecowgirl314** [comment]
I'm currently testing upstream on Garuda and I'm having trouble getting paru (which is built-in) to see any updates for my git AUR packages. In the settings I've got --devel checked (as well as --noconfirm and search for outdated packages) so I'm not sure why it's not updating my git AUR packages. Granted I also haven't seen any other AUR packages yet so I'm not sure if it even works. Also nothing shows in news (instead of saying unsupported) but I'm not sure if that's normal.

**Comment by Morganamilo** [comment]
Devel checks are done by seeing if there's any new commits since paru installed the package. So if paru did not originally install the package or if there have not been any new commits since it was installed then there won't be updates.

**Comment by spacecowgirl314** [comment]
Oh, so if it was installed with Pamac then it won't see any updates? Is there a way to fix this aside from reinstalling?

**Comment by Morganamilo** [comment]
`paru --gendb`

**Comment by spacecowgirl314** [comment]
@Morganamilo 

Thank you! I will see if this fixes my git issues. Regular AUR (non-git) packages should just work right?

**Comment by Morganamilo** [comment]
Yeah that's only for git devel checks.

**Comment by spacecowgirl314** [comment]
I can now say it doesn't show paru git updates. It did have other regular package updates though. At least as of 05eda769631ed0568d2c0ad3643e2a797b7aa411. I had to run paru manually to get your latest upstream. Does there have to be a build directory specified? Won't know for a while if your latest commits fixed it. I can tell you though that it said press Ctrl-G for updates in the News tab. After that it's empty though. 

Here is /etc/os-release:
`File: /etc/os-release
NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
LOGO=garudalinux`

**Comment by aarnt** [comment]
Did you test commit a8628f05d816fe892ebce40059bf8d21195d7013 ?
I made a small change in the LinuxDistro method.

**Comment by spacecowgirl314** [comment]
Yes, it said to press Ctrl-G for updates and then I got nothing. Does it only show something if there's been news since it's checked?

**Comment by dr460nf1r3** [comment]
I can confirm both of those issues. Anything special thing to do which can help you debugging @aarnt ?

**Comment by spacecowgirl314** [comment]
I've tried using Ctrl+Shift+O and it doesn't do anything, either in the regular view or the AUR view. I also tried setting a build directory. That didn't fix it either. However, the news now works as of the latest commit!

**Comment by aarnt** [comment]
@spacecowgirl314 
What is the paru command you use to get it?

**Comment by spacecowgirl314** [comment]
Is there supposed to be a button or something somewhere because there is absolutely no indication that Ctrl-Shift-O does anything. Perhaps it's disabled? If I want to just check for AUR updates I run paru -Su otherwise it'll check for regular packages. Looking at your code, using -S with the list of foreign packages will forcibly reinstall every AUR package even if there are no updates. That doesn't look like the right approach unless I'm mistaken here somehow.

**Comment by aarnt** [comment]
@spacecowgirl314 
There is no AUR check for updates button in the UI. And if you go the the "Help" tab you'll see a Ctrl+Shift+O section there.

Regarding PacmanExec::doAURUpgrade, it receives a listOfPackages param, which contains the list of outdated-only AUR packages.

The paru command line which is used to obtain the list of outdated packages is: "paru -Qua". I think it does not show git updates.

What is the output of "paru -Qua" in a terminal of yours?

**Comment by spacecowgirl314** [comment]
@aarnt I had to turn off "Search for outdated AUR packages" before the hotkey turned up in the Help tab. That doesn't seem really intuitive. I was under the impression that it was turning on checking for updates for AUR packages. However, even with that off pressing Ctrl+Shift+O doesn't do anything. 

For me `paru -Qua` returns
`apple-music-electron-git 2.5.1.702.d364f00-1 -> latest-commit
plasma5-wallpapers-wallpaper-engine-git r312.d1a634d-1 -> latest-commit`
for which if I run paru normally it updates those two packages.

**Comment by aarnt** [comment]
v0.12.0 is out.
