### ISSUE TITLE
[BUG] Installing Octopi with Paru Causes Octopi Not to Detect Paru

### ISSUE THREAD

**Issue by ThisNekoGuy** [aarnt/octopi#494]
I'm not sure why, but I installed [Octopi 0.11.0-2](https://aur.archlinux.org/packages/octopi/) with [Paru-bin](https://aur.archlinux.org/packages/paru-bin/) and it's not detected by Octopi; as a result, clicking the alien button causes Octopi to attempt to install yay

**Comment by aarnt** [comment]
@ThisNekoGuy 
Of course. Version 0.11 is not compatible with paru.
Use upstream code.
