### ISSUE TITLE
[Feature Request] View option: Outdated

### ISSUE THREAD

**Issue by underscoren** [aarnt/octopi#498]
Currently, you can view all, installed, or not installed packages.
I am aware that you can click the button on the bottom status bar to see a list of all packages that require an update, however if you want to check each package for details you need to constantly switch between the Info and Output tab. This is not very intuitive, and as a new user it took me a while to figure this out.

It would be a good idea to have a view option to list all packages that are outdated, as this would allow greater flexibility with other options, e.g. viewing packages from a certain repository or from the AUR.

**Comment by aarnt** [comment]
Hi @underscoren,

You can also sort packages by the icon column (the very first one), so you can view all outdated packages grouped.

**Comment by underscoren** [comment]
That sounds quite useful, though again not too intuitive. I wouldn't have figured that out, especially given that the icon column doesn't have a name. Maybe it should be called "Status" or "State"?

Using this method would mean you have to give up other sorting options, though that seems like a less common use case. It looks like a decent workaround for now.

**Comment by aarnt** [comment]
Hi @underscoren 

View/Outdated implemented upstream (0.13 dev).
