### ISSUE TITLE
getTreeViewCSS is unreadable on dark themes

### ISSUE THREAD

**Issue by buckmelanoma** [aarnt/octopi#500]
getTreeViewCSS is used for the Files and Actions tabs and sets custom icons for the tree view elements.  Since these are static images they remain black even when using a dark window color, making them nearly invisible.  

![b4](https://user-images.githubusercontent.com/43704682/143143612-45566bcd-e846-4705-a8d2-b40108e76302.png)

Removing 
`m_tvTransaction->setStyleSheet(StrConstants::getTreeViewCSS());`
and
`m_tvPkgFileList->setStyleSheet(StrConstants::getTreeViewCSS());`
from `propertiestabwidget.cpp` yields tree view elements that have proper contrast in dark themes:

![af](https://user-images.githubusercontent.com/43704682/143143699-5cb52773-caa0-481d-b45d-b332caa43f5a.png)

**Comment by aarnt** [comment]
Fixed in upstream.
