### ISSUE TITLE
News on Arch is broken

### ISSUE THREAD

**Issue by tausciam** [aarnt/octopi#501]
If you try to download the news and you're running Arch, it used to work. Now, you get a "301 Moved Permanently" nginx error.

The correct website it should be pointing to is https://archlinux.org/news/

**Comment by aarnt** [comment]
@tausciam 

Are you using Octopi version 0.12.0 ? If so, do the following:

1. Close Octopi.
2. Edit your `~/.config/octopi/octopi.conf`
3. Remove the line that starts with the "Distro_RSS_Url=" string.
4. Start Octopi and press "Ctrl+G".

Now, you should see latest Arch Linux news.

**Comment by tausciam** [comment]
Thank you! That solved it. Really appreciated
