### ISSUE TITLE
octopi crashes when click PKGBUILD options

### ISSUE THREAD

**Issue by fcolecumberri** [aarnt/octopi#502]
OS: Garuda Mate
Version: 0.12.0 - Qt 5.15.2

After clicking on the "Paru" button and then right-click on a package and click on any PKGBUILD option, octopi crash.

On the terminal prompts:
```
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 571
```

**Comment by aarnt** [comment]
Hi @fcolecumberri 

You mean the options "Open PKGBUILD" and "Show PKGBUILD diff" are crashing for you, right?

I could not reproduce it. Which packages were you looking for with Paru?

Does it also occur when you click over the AUR installed packages?

**Comment by fcolecumberri** [comment]
This happens with any package and this happens if the package is or is not installed.

**Comment by aarnt** [comment]
Hmm, weird.
I'll install Garuda Mate in a VM to test.

**Comment by aarnt** [comment]
@fcolecumberri 
Upstream code (0.13 dev) has the needed fixes.

**Comment by drujd** [comment]
I have exactly the same issue in Arch. Upgrading to git master version makes Octopi not crash, but it still doesn't work (neither Open nor Show).

**Comment by aarnt** [comment]
@drujd 
Ok. Which desktop are you using?

**Comment by drujd** [comment]
KDE Plasma 5.23.4

**Comment by drujd** [comment]
I didn't - that was it! Thanks!

Any chance Octopi could be made to respect XDG associations?

**Comment by aarnt** [comment]
@drujd 
Hi, I've just added it. Can you remove kate and test?

**Comment by drujd** [comment]
Yup, confirmed working. Now it opens both the PKGBUILD and the diff in VSCodium. Thanks a lot!

**Comment by fcolecumberri** [comment]
confirmed
