### ISSUE TITLE
Suggestion: add flatpak support, if the host machine has it installed

### ISSUE THREAD

**Issue by orowith2os** [aarnt/octopi#503]
I've tried out flatpaks, like the one with obs studio, and it works incredibly well, better than the community one. To me, it seems like a good idea to implement the support for flatpaks as well, similar to how you click the button to look at AUR packages with octopi. If it can't be officially supported, does anybody have a guide or similar on how I'd be able to build it into myself? I have minimal experience with coding projects like this. I'm not saying to force flatpaks onto the machine, but rather to have a toggleable option to enable flatpak support on octopi, being disabled by default.

**Comment by aarnt** [comment]
Hi @orowith2os 

I understand your desire to have more alternatives to install programs and I really appreciate you're using Octopi and trying to improve its code.

But I'd rather not support any third party installers and stick only with pacman and AUR helpers. The main reason is that maintaining the current code is already a challenge, thanks to its (aprox) 30k lines size.

If you'd like to implement this feature yourself, you'd need to study the code structure, particularly the interactions between model, view and package classes. A good starting point is to trace the entire chain of calls involved in the "Package::getParuPackageList()" call, a "package.cpp" method.

Sorry if this wasn't the answer you wanted, but thanks for your preference anyway.
