### ISSUE TITLE
Octopi on Wayland (Plasma) support

### ISSUE THREAD

**Issue by demmm** [aarnt/octopi#506]
Plasma 5 is just about ready to default to running on Wayland instead of X.  Octopi however is having issues running on Wayland, causing very high CPU, and eventually hanging/segfaulting with error:
```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Terminated
```

There are many bug reports dealing with this issue, seems https://github.com/aarnt/octopi/search?q=activateWindow is not supported in Wayland.  Examples of some reports with maybe some useful patches:
https://github.com/flameshot-org/flameshot/issues/619
https://bugzilla.redhat.com/show_bug.cgi?id=1820923
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/288

**Comment by aarnt** [comment]
Hi @demmm 

You can make this test to see if it works:

- Comment all "actWin->activateWindow()" statements on "src/QtSolutions/qtsingleapplication.cpp"
- Comment all "->activateWindow()" statements on "notifier/mainwindow.cpp"

Do the messages/high cpu usage go away after that?

**Comment by demmm** [comment]
Patching did not make a difference.

**Comment by aarnt** [comment]
Hi @demmm 

I've just updated my KaOS virtualbox vm here to make some tests in a wayland session (with an unpatched Octopi 0.13 dev version).
Unfortunately I was not able to reproduce the high cpu/termination error.

Can you elaborate on the use cases this bug occurs?

**Comment by aarnt** [comment]
@demmm 
Any update on this issue?

**Comment by demmm** [comment]
It is gone, all my systems run Wayland exclusively now, no issue whatsoever with Octopi.
