### ISSUE TITLE
Error while entering login and password

### ISSUE THREAD

**Issue by robson-66** [aarnt/octopi#508]
When I enter my username and password to enable voting in AUR it keeps popping up info that these are invalid data.

**Comment by aarnt** [comment]
Hi @robson-66 

aur-web was changed to version 6.0.15. This probably broke some tests in octopi code.

**Comment by aarnt** [comment]
@robson-66 
Can you try latest dev code?

**Comment by robson-66** [comment]
After rebuilding, voting in the AUR works. Thank you very much.
