### ISSUE TITLE
[Feature request] Check updates via command

### ISSUE THREAD

**Issue by dataprolet** [aarnt/octopi#511]
Is it maybe already possible or if not possible to implement, that octopi checks for updates via a simple command? In the case you'd use pacman to update manually, octopi-notifier will only notice when checking the next time and displaying available updates, that have been already installed until then. I simple command like octopi --update which can be used as a pacman hook would be very useful.

**Comment by aarnt** [comment]
Hi @Arjab.
I don't think I got your point.
Currently Octopi supports "-checkupdates" and "-sysupgrade" parameters, but only if it is already running.

**Comment by aarnt** [comment]
@Arjab 
Ah, ok.
I think I've just implemented it for you then. 
Try latest code with: 

`/usr/bin/octopi-notifier -checkupdates`

**Comment by Arjab** [comment]
Thank you. I just cloned the repo and installed octopi using makepkg -f but the command still returns "Aborting notifier as another instance is already running!".

**Comment by aarnt** [comment]
Somehow you are running the old version.
Latest notifier code has this msg commented.

**Comment by dataprolet** [comment]
I don't want to bother you with my inability to install the latest code. But `makepkg -f` builds version 0.12.0-1 for me, not 0.12.0-2.

**Comment by aarnt** [comment]
But 0.12.0-1 is the version of the git code. You only have to install it with "pacman -U". You can also drag the generated pkg to octopi's ui, so it will install for you.

**Comment by dataprolet** [comment]
That's weird, the version in the AUR is 0.12.0-2. I'll contact the maintainer of the package.

**Comment by aarnt** [comment]
> That's weird, the version in the AUR is 0.12.0-2. I'll contact the maintainer of the package.

That's not a problem. He can bump the last number if he changes something.

**Comment by dataprolet** [comment]
Thanks again and I'm also sorry again, but now the installation fails, because the following files from octopi-notifier-framework already exist in the filesystem. I can also just wait for a regular release of octopi, if you don't want to bother with this.

```
/etc/xdg/autostart/octopi-notifier.desktop
/usr/bin/octopi-notifier
/usr/share/applications/octopi-notifier.desktop
```

**Comment by aarnt** [comment]
That's ok. You need to use pacman's parameter "--overwrite" on each of the files that already exists. You can google "pacman -U --overwrite" to find examples.

**Comment by dataprolet** [comment]
Thanks a lot, now `/usr/bin/octopi-notifier -checkupdates` wasn't returning a message, so I assume it works as expected. I really appreciate it.
