### ISSUE TITLE
Feature Request: Display icons/images like pamac.

### ISSUE THREAD

**Issue by Bitwolfies** [aarnt/octopi#514]
Hi, apologies if this was requested before (I searched around for icons and images) but it would be nice to be able to see any images or icons associated with apps, much the same way pamac does. Thanks for all you do!

**Comment by aarnt** [comment]
Hi @Bitwolfies!

Octopi is more like a Debian's Synaptic like project.
If you're comfortable using Pamac, then please keep using it.
