### ISSUE TITLE
[feature request] add filter options

### ISSUE THREAD

**Issue by fischer-felix** [aarnt/octopi#520]
When looking thought the packages on the main page, all the available ones are shown, however I'd like to be able to only go through packages that are, for example, installed.
It would be nice if you could either add a generic filter or a specific one to only show installed packages.

**Comment by demmm** [comment]
You mean the currently available option under `View`?  See:
![Screenshot_20221122_180547](https://user-images.githubusercontent.com/5360485/203377165-fe726a98-500c-4ce7-88bb-ccb8092c769b.png)

**Comment by fischer-felix** [comment]
Whoops, completely overlooked that, thank you for mentioning it!
