### ISSUE TITLE
octopi updates

### ISSUE THREAD

**Issue by xaoret** [aarnt/octopi#527]
hello, i recently installed octopi (version 0.14.) and there is no way to update as often as i want, in my case every 6 hours. When I set it to update every 360 minutes and click OK, I go back in and it defaults to Daily. Is there any way to fix it?. Thank you

**Comment by aarnt** [comment]
Hi. I cannot reproduce this error here. Maybe your "octopi.conf" file is ready only for your user?

Try this:
- Close octopi and notifier
- Rename your "~/.config/octopi/octopi.conf" to "~/.config/octopi/BKP_octopi.conf"
- Start notifier with your user and try to change update interval again to 360

Did it solve the issue?

**Comment by urbenlegend** [comment]
I am seeing this issue as well. It seems like the setting refuses to change when the main Octopi window is open. If I close Octopi and then open the options page via the Octopi Notifier, it works.

**Comment by aarnt** [comment]
Ok, I think now it's fixed upstream.

**Comment by urbenlegend** [comment]
I just tested with `octopi-dev` and `octopi-notifier-frameworks-dev` and the issue has only been partially fixed. If I navigate to the options via the notifier tray icon, I can now correctly change the update interval regardless of whether the main Octopi window is open or not. However, I am still not able to change the update interval when I go to the options via Tools -> Options -> Update in the main window.

**Comment by aarnt** [comment]
@urbenlegend 
Ok, can you test it again? New code upstream.

**Comment by urbenlegend** [comment]
Works perfectly now! Thanks so much for the quick fix!

**Comment by aarnt** [comment]
Thank you very much!
