### ISSUE TITLE
Support displaying list of uninstalled files of any official package

### ISSUE THREAD

**Issue by Zesko** [aarnt/octopi#528]
The current version 0.14.0  of octopi does not have a feature to display list of **non-installed** files of any official package.

I know pacman supports that for online searching package with its uninstalled files.
```
$ pacman -Fl <non-installed official package>
```
For offline searching installed package in local:
```
$ pacman -Ql <installed official package>
```

**Comment by aarnt** [comment]
@Zesko 
Thanks for the suggestion!
Upstream is using that one.
