### ISSUE TITLE
octopi-helper[aborted]: Suspicious transaction detected -> "echo "Press"

### ISSUE THREAD

**Issue by dasbaum-ch** [aarnt/octopi#530]
Hello
I have a wierd problem with octopi. Since last system upgrade, I’m not able to install anything with octopi. My error is only octopi-helper[aborted]: Suspicious transaction detected -> "echo "Press".
I’ve tried to remove octopi with all folders but no change.
What have I tried:
```
sudo find / -name "*octopi*" -exec rm -rf {} \;
sudo rm -rf /var/lib/pacman/sync/*
sudo rm -rf /etc/pacman.d/gnupg
sudo pacman -Scc init key database
sudo pacman-key --init populate database
sudo pacman-key --populate manjaro archlinux
```
With pacman I can install everything as usual. It fails only with octopi.

Error message:
```
sudo /usr/lib/octopi/octphelper -ts

octopi-helper[aborted]: Suspicious transaction detected -> "echo "Press"
```
Is it possible to see more logs, if so how do I do that? Or do you guys know this problem?
My sytem:
Manjaro 22.1.2
Octopi: 0.14.0 Qt 5.15
XFCE: 4.18
GTK: 3.24.37
Kernel: 6.3.3-1-MANJARO
Best regards

**Comment by mai0li** [comment]
+1

**Comment by aarnt** [comment]
Right, can you test latest development code?
