### ISSUE TITLE
[Feature Request] Add option to ignore updates

### ISSUE THREAD

**Issue by Toastcreator** [aarnt/octopi#533]
Not all updates are positive where in this case my current kernel update on Garuda is causing a KP or in the case of googlefonts which doesn't need to be updated every time someone edits a readme.txt and so everything needs to be redownloaded and installed because reasons.

I'm new to the Linux scene but I'm guessing such a feature hasn't ever been thought of since package managers came to be because it's so useful? Or is it that hard to implement? I.e checkboxes or whatever that requires the least amount of code.

**Comment by redzrush101** [comment]
Nah you can already so that in /etc/pacman.conf with IgnorePkg so its possible to implement ig

**Comment by Toastcreator** [comment]
Thank you! You've saved me hours worth of headaches.
