### ISSUE TITLE
Pacman backend doesn't show all packages

### ISSUE THREAD

**Issue by urbenlegend** [aarnt/octopi#534]
I have `octopi`, `alpm_octopi_utils`, and `octopi-notifier-frameworks` installed on my system. If I switch to the pacman backend, I only see `octopi` in both the package search and the `All` list

It seems like there's a bug with the pacman backend in this case.

**Comment by aarnt** [comment]
Hi, mate. Indeed! I was using "pacman -Qem" to get the list, so it did not show foreign dependencies.
Now it's fixed upstream. Thanks!

**Comment by urbenlegend** [comment]
Thanks for the quick fix! I can confirm this works using the `octopi-dev` AUR package.
