### ISSUE TITLE
[Feature request] Allow to set terminal window size and font size permanently.

### ISSUE THREAD

**Issue by fiechr** [aarnt/octopi#536]
To clarify: I'm talking about the window that opens when the user clicks on the symbol in the task area (if new updates are available).

At the moment, it's already possible to change the font size bei holding Ctrl and scroll the mouse wheel. The application even remembers this setting, which is nice!

Unfortunately the size of the terminal window (usually measured in row and cols) can be changed but is not remembered permanently.

Ideal would be, if these two things could be set inside the settings dialog window.

**Comment by aarnt** [comment]
Fixed upstream.
