### ISSUE TITLE
No longer able to toggle install reason

### ISSUE THREAD

**Issue by urbenlegend** [aarnt/octopi#537]
With the last few git versions, I have been unable to toggle the install reason between "explicit" and "installed as dependency". If I use the libalpm backend, it will say transaction failed. If I use the pacman backend, it doesn't even show an error message. In either case, install reason is not changed.

**Comment by aarnt** [comment]
This feature is executed by a pacman -D command, so it's probably a pacman issue in your system. Try running a "pacman -D --asdeps <NAME_OF_A_PACKAGE>" or "pacman -D --asexplicit <NAME_OF_A_PACKAGE>" in your terminal to see if it works.

**Comment by urbenlegend** [comment]
Those work just fine. Its only in Octopi.

**Comment by urbenlegend** [comment]
What's weird is that after I attempt to toggle install reason, if I try to install another package, I get a very weird error: `octopi-helper[aborted]: Suspicious transaction detected -> "p"

This doesn't go away until I restart Octopi

**Comment by aarnt** [comment]
Ok.
Can you install latest code, execute your tests and see the contents of the "/usr/lib/octopi/octphelper.log" file?

**Comment by urbenlegend** [comment]
If I use the pacman backend, all I see is:
```
25 Aug 2023 20:19:13: Exec as root:
```

That's the only log that gets printed out.

Now if I switch to alpm + pacman and then try to toggle install reason I get:

```
25 Aug 2023 20:24:32: octopi-helper[aborted]: Suspicious transaction detected -> "p"
```

If I relaunch Octopi, then it works fine with alpm + pacman backend:
```
25 Aug 2023 20:26:06: Exec as root: /usr/bin/pacman -D --asexplicit kcalc
25 Aug 2023 20:26:13: Exec as root: /usr/bin/pacman -D --asdeps kcalc
```

If I switch back to the pacman backend, it breaks again. So it seems like pacman backend is broken, and switching from pacman to alpm + pacman is also broken until restart.

**Comment by aarnt** [comment]
Hi @urbenlegend , indeed pacman backend did not work with change install reason.

Can you test latest code again?

**Comment by urbenlegend** [comment]
It's fixed! Thank you!
