### ISSUE TITLE
initial impressions

### ISSUE THREAD

**Issue by atomGit** [aarnt/octopi#538]
octopi 0.14.0 on manjaro

* slow start-up - it seems the package list is rebuilt each time
* settings not remembered across sessions - for example, all settings in the Search and View menus
* Tools > Options > Updates : setting is ignored both during the current session and across sessions
* needs better integration with the AUR - ideally the helper (Yay in my case) button next to the search input shouldn't be needed
* column widths not remembered across sessions

overall i think the UI could be more intuitive

**Comment by caseyjp11** [comment]
I'll 2nd the OP on every single point. I've been testing GUI package managers for a less command-line savvy friend (who I support) and Octopi is a bleeding eyesore that even has me scratching my head, let alone someone who isn't a 'computer-person'.

**Comment by MatMoul** [comment]
This project is great...
If you are not competent enough, use alternatives...

**Comment by atomGit** [comment]
competence and pointing out software bugs are two very different things - get it?
