### ISSUE TITLE
Cache Cleaner does not listen to setting

### ISSUE THREAD

**Issue by ShalokShalom** [aarnt/octopi#539]
Hi

I do know about this behavior for years, but I always thought it will be fixed soon anyway, and it didn't bother me too much: 

![Screenshot_20230914_180744](https://github.com/aarnt/octopi/assets/6344099/66968d63-05f5-4e81-a5a8-c2f0ebb4f5ad)

So, when I set this to 0, it still caches packages. I expect it to not do that, and it seems like, it stores 2 generations even. 

Garuda, but also happened so on KaOS

**Comment by aarnt** [comment]
There is nothing wrong there. It just sets the "-k" option of paccache, as the manual states:

      -k, --keep <num>
           Specify how many versions of each package are kept in the cache directory, default is 3.

Try to run a "paccache -d -k 0" in your command line to see what happens.

**Comment by ShalokShalom** [comment]
So there is no way to clear all packages?
