### ISSUE TITLE
Will only run on qtermwidget 1.3 otherwise 1.4 qtermwidget/octopi crash on startup

### ISSUE THREAD

**Issue by ixnewton** [aarnt/octopi#543]
To use Octopi I have to downgrade qtermwidget to v1.3 otherwise octopi core dumps.

qtermwidget to v1.4.0.1 fails as in trace
[systemd-coredump.log](https://github.com/aarnt/octopi/files/13463578/systemd-coredump.log)

DOWNGRADE_FROM_ALA=1 downgrade qtermwidget 

warning: downgrading package qtermwidget (1.4.0-1 => 1.3.0-2)

Then all is well

Version: 0.15.0 - Qt 5.15.10

**Comment by aarnt** [comment]
Compile octopi again with upgraded libs.
