### ISSUE TITLE
Clicking on notifier system tray icon raises an error message

### ISSUE THREAD

**Issue by SemnoSao** [aarnt/octopi#547]
When trying to use the octopi-notifier-framework, when clicking on the icon on system tray or when clicking with the right button and selecting the "Octopi..." option I am given the following error "You Must Use "/usr/bin/octopi" to run octopi":
![screen print of an error windows with: You Must Use "/usr/bin/octopi" to run octopi](https://github.com/aarnt/octopi/assets/16153554/be9c6a1c-d356-4f50-9cdb-fed70f2196cf)

If an octopi window is already open it functions as normal raising the window but it's not capable of opening the application for starts.

I tried starting octopi-notifier via terminal but it doesn't give any debug information. If I can give any more meaningful information please instruct me and I will do.

I'm on a Manjaro based distribution running KDE.

**Comment by aarnt** [comment]
It was fixed upstream.

**Comment by only-su** [comment]
sorry, when will it be avaliable on pacman? I tried building from source but I'm not smart enough ;-;
