### ISSUE TITLE
Command line command to force update of octopi-notifier status

### ISSUE THREAD

**Issue by Xwang1976** [aarnt/octopi#551]
Hi to all,
my use case for octopi is to use the octopi-notifier to check if some update are available.
When they are I run one script of mine that uses trizen to update.
After that the octopi icon remains red until I click on "check for update".
I would like to have a way to do that from my script so that to reset the icon status after the update has been made.
Is it possible to do that?
If not could it be added as a feature or the same can be achieved with some workaround?

**Comment by aarnt** [comment]
Try 

/usr/bin/octopi-notifier -checkupdates
