### ISSUE TITLE
octopi fails to start after upgrading from qtermwidget  1.4 to 2.0 

### ISSUE THREAD

**Issue by Zesko** [aarnt/octopi#552]
Just info, Arch repos change the dependency `qtermwidget` version 1.4 to 2.0.

Octopi can not start because:
```
octopi: error while loading shared libraries: libqtermwidget5.so.1: cannot open shared object file: No such file or directory
``` 

https://aur.archlinux.org/packages/octopi#comment-973456

**Comment by sibwaze** [comment]
I've got the same issue. Probably you need to downgrade qtermwidget package to 1.4 to run Octopi or build it with qt6 to use the new qtermwidget. I opened an issue here: https://github.com/aarnt/octopi/issues/553

**Comment by sibwaze** [comment]
> > Probably you need to downgrade qtermwidget package to 1.4 to run Octopi
> 
> I think `qtermwidget` is for LXQT. I've already downgraded to the previous version of `qtermwidget` because I do not use LXQT.
> 
> If you use some LXQT packages that require this dependency, you need to manually adapt Octopi's source code, then build it.

I didn't quite understand what you mean

**Comment by aarnt** [comment]
Can you try to manually build latest source code?

**Comment by yochananmarqos** [comment]
@aarnt I'm attempting to build with Qt6 using Cmake, however Frameworks can't find `kstatusnotifieritem.h`. It's located in `/usr/include/KF6/KStatusNotifierItem/`

```
[ 83%] Building CXX object CMakeFiles/octopi-notifier.dir/build/octopi/src/octopi-0.15.0/src/aurvote.cpp.o
/build/octopi/src/octopi-0.15.0/notifier-frameworks/mainwindow.cpp:43:12: fatal error: kstatusnotifieritem.h: No such file or directory
   43 |   #include <kstatusnotifieritem.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/octopi-notifier.dir/build.make:224: CMakeFiles/octopi-notifier.dir/mainwindow.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by sibwaze** [comment]
> Can you try to manually build latest source code?

i also tried today but was not able to do it

**Comment by sibwaze** [comment]
> Can you try to manually build latest source code?

yeah, it works, thanks!
![изображение](https://github.com/aarnt/octopi/assets/98026017/d710ce78-7bd3-475b-9c0c-822b5e3c66ee)

**Comment by yochananmarqos** [comment]
@sibwaze It works how? I tried with both Qmake and Cmake, both failed.

**Comment by aarnt** [comment]
@yochananmarqos  Don't enable KSTATUS switch. Don't use KStatusNotification.

**Comment by yochananmarqos** [comment]
@aarnt Alright, I'll try that.

So there's no more Frameworks notifier?

**Comment by aarnt** [comment]
@yochananmarqos I'm afraid it doesn't work the way KF5 did. So I had to disabled it.

**Comment by yochananmarqos** [comment]
@aarnt It builds now, however what about sudo? The folder is gone now, but it's still looking for it:

```
❯ octopi
Aborting octopi as 'octopi-sudo' binary could not be found! [ "/usr/local/bin/qt-sudo" ]
```

**Comment by aarnt** [comment]
@yochananmarqos I see it's not a good practice, but the problem is that qt-sudo is used by my BSD projects too.

**Comment by yochananmarqos** [comment]
@aarnt qt-sudo fails to build: https://github.com/aarnt/qt-sudo/issues/1

**Comment by yochananmarqos** [comment]
@aarnt The Manjaro and AUR packages are now updated. This can be closed.
