### ISSUE TITLE
Installing octopi throws a fatal error about qtermwidget5/qtermwidget.h

### ISSUE THREAD

**Issue by KarkanAlzwayed** [aarnt/octopi#554]
I have been using Octopi for years now and I have installed numorous times. I had to reinstall my system yesterday and, as usual, I'm installing my packages. Octopi installed at first and worked for a whole day, then today it just stopped launching. I messed with it for a while then figured I'd just removed then reinstall it, but now it refuses to install, and it gives this error 
```
In file included from src/propertiestabwidget.cpp:25:
src/termwidget.h:27:10: fatal error: qtermwidget5/qtermwidget.h: No such file or directory
   27 | #include "qtermwidget5/qtermwidget.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:990: build/propertiestabwidget.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```
Looked for these two packages `qtermwidget5/qtermwidget.h` and neither of them exists in the AUR nor in the Arch/Endeavour OS repos. I have tried installing with `paru -S octopi`, `yay -S octopi` and `pacman -S octopi` (this one returns that the package doesn't exist). I tried to install the git version of it and still no luck. Tried to build it from source following instructions on here by cloning and all that, and I'm still having no luck. 

Operating System: EndeavourOS 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: A520I AC
System Version: -CF

**Comment by aarnt** [comment]
@KarkanAlzwayed  Thanks, it's being worked on another issue.
