### ISSUE TITLE
Cmake: Octopi notifier after update in etc/xdg/autostart

### ISSUE THREAD

**Issue by ptr1337** [aarnt/octopi#556]
The notifier should not set itself to the autostart. Since cmake wasnt used before, no one did notice.

**Comment by aarnt** [comment]
Fixed upstream.

**Comment by wolfseifert** [comment]
> The notifier should not set itself to the autostart. Since cmake wasnt used before, no one did notice.

Why not? If you install octopi-notifier you probably want it to be auto-started! Now you have to copy octopi-notifier.desktop to /etc/xdg/autostart or ~/.config/autostart yourself.

**Comment by Spixmaster** [comment]
> > The notifier should not set itself to the autostart. Since cmake wasnt used before, no one did notice.
> 
> Why not? If you install octopi-notifier you probably want it to be auto-started! Now you have to copy octopi-notifier.desktop to /etc/xdg/autostart or ~/.config/autostart yourself.

I do not know from which repositories you install but from Arch Linux the binary `octopi-notifier` comes with the package "octopi". So you do not explicitly install "octopi-notifier".

I do not want software running in the background checking for updates. I have a script for that that uses way less memory.

**Comment by wolfseifert** [comment]
Ok, I understand both sides now.

Maybe we should leave it as it is now and just add something like this to the README:
### To start Octopi Notifier automatically for all users
```
$ sudo cp /usr/share/applications/octopi-notifier.desktop /etc/xdg/autostart
```
### To start Octopi Notifier automatically for an indivdual user
```
$ cp /usr/share/applications/octopi-notifier.desktop ~/.config/autostart
```

**Comment by Spixmaster** [comment]
And additional argument is that when packages install into `/etc/xdg/autostart/` you cannot disable the auto start without corrupting the package.

**Comment by Spixmaster** [comment]
> Ok, I understand both sides now.
> 
> Maybe we should leave it as it is now and just add something like this to the README:
> 
> ### To start Octopi Notifier automatically for all users
> ```
> $ sudo cp /usr/share/applications/octopi-notifier.desktop /etc/xdg/autostart
> ```
> 
> ### To start Octopi Notifier automatically for an indivdual user
> ```
> $ cp /usr/share/applications/octopi-notifier.desktop ~/.config/autostart
> ```

I do not agree. Starting software with booting is a common task that is handled individually. Personally, I want non-GUI processes to be started with a SystemD service whereas I start GUI software via my window manager configuration.
