### ISSUE TITLE
Cannot uninstall when offline - Needs Internet Connection to uninstall

### ISSUE THREAD

**Issue by Theluga** [aarnt/octopi#559]
Steps to reproduce:

Disable internet connection (wifi, ethernet etc) 

Open Octopi, search package, click in uninstall

It says: Internet seems unavailable

![Screenshot from 2024-06-08 12-46-17](https://github.com/aarnt/octopi/assets/96307393/7ae0b7f1-7810-49fe-871f-a1e246c2c290)
 

it works even with packages not in the aur:

![Screenshot from 2024-06-08 12-49-54](https://github.com/aarnt/octopi/assets/96307393/d9b7f27e-e033-4a7a-8f1c-2d0d004c801b)
```


System:
  Kernel: 6.9.3-arch1-1 arch: x86_64 bits: 64
  Desktop: GNOME v: 46.2 Distro: Arch Linux

Octopi: 
Version 0.16.0-1


```

**Comment by aarnt** [comment]
@Theluga 
It's fixed upstream.
Thx for reporting.
