### ISSUE TITLE
The app does not show columns selected in an options.

### ISSUE THREAD

**Issue by Giger22** [aarnt/octopi#560]
In "Package List"  I selected following columns to appear:

1. Licences
2. Installed Size
3. Build Date
4. Install Date
5. Install Reason

But only "Licences" appear on app's main screen.

**Comment by aarnt** [comment]
@Giger22 
It works here on my system.
I presumed you scrolled the package list to the right to see if the columns are not hidden, didn't you?
If so, can you also check your "~/.config/octopi/octopi.conf" writing permissions?

**Comment by Giger22** [comment]
Darn, I did not scroll...
