### ISSUE TITLE
Octopi complete bropke after one reboot after installing

### ISSUE THREAD

**Issue by cammelspit** [aarnt/octopi#561]
![image](https://github.com/aarnt/octopi/assets/9344114/0eb7a676-7357-4b44-b7af-a039e948b76b)
I installed octopi and it was working fine, the second I rebooted once, boom this is happening and the app itself is completely frozen. I changed my font, doesn't help. I uninstalled and reinstalled fresh, nothing. I deleted the octopi configs, still happening.

Any ideas?

**Comment by aarnt** [comment]
Open a terminal and type 

pacman  -Syy

**Comment by cammelspit** [comment]
That didn't seem to work but somehow it fixed itself? No clue but it didn't work for a few days and then started without explanation. Also, I did indeed update and at the time it didn't help. It's been working solidly for a while now so im happy. Thanks
