### ISSUE TITLE
EndeavourOS news is blank

### ISSUE THREAD

**Issue by LegitGreenBoi** [aarnt/octopi#563]
Whenever I Ctrl+G in Octopi on EndeavourOS, it seems to update the news, but the news tab remains blank every time. Octopi has done this for me for quite some time, even after new posts have gone up on the EndeavourOS RSS feed.

In the Octopi config the URL is listed as:
Distro_RSS_Url=https://endeavouros.com/feed/

I verified in my browser and found that the URL is still correct, but for some reason the output remains blank in Octopi. I even tried deleting the line and letting Octopi regenerate it, but that didn't solve the issue.

This is how the news tab looks on my EndeavourOS system after updating the distro news:
![image](https://github.com/user-attachments/assets/0bbfadde-7467-4ebe-bae1-f5b13de696c9)

**Comment by aarnt** [comment]
Thanks for the info.
It was fixed upstream!
