### ISSUE TITLE
[Feature Request] Search package description

### ISSUE THREAD

**Issue by new-penguin** [aarnt/octopi#564]
When I first installed it on EndeavorOS, being new to Arch-based distros, I just assumed Arch didn't have as many packages as Mint. Of course I quickly realized the problem when using pacman via terminal. Octopi by default doesn't search in the package descriptions and I've not read anywhere if there's an option to enable it. Please delete if I missed it somewhere but I've not found the option nor read it's possible using octopi.

**Comment by aarnt** [comment]
Yes, there is. Select by description on the Search menu.

**Comment by new-penguin** [comment]
Oh geez. Please delete. I'm such an idiot.
