### ISSUE TITLE
Support `--editmenu` when using yay as an AUR helper

### ISSUE THREAD

**Issue by mdedetrich** [aarnt/octopi#570]
Sometimes packages in AUR can be broken, due to this many AUR options have a flag that allows you to edit the pkgbuild after reviewing it. For yay the flag is `--editmenu` (see https://github.com/Jguer/yay/issues/750#issuecomment-427042210).

Would it be possible to add this option to octopi, this existing section seems to be the best candidate
![image](https://github.com/user-attachments/assets/113628c0-a8fe-4b8b-bff6-a435c412c120)

**Comment by aarnt** [comment]
Feature was added upstream.
