### ISSUE TITLE
label:question How to change the link color in the Info panel?

### ISSUE THREAD

**Issue by k4100x** [aarnt/octopi#571]
The links in the Info tab are blue, which is difficult to read against a dark background. 

How can I change them to green, to match the image in the README.md?  

Does Octopi obtain that link color from some system-wide config file?

(I use EndeavourOS and have tried downloading octopi from Chaotic-AUR as well as compiling from AUR/octopi.)

Thanks!

**Comment by aarnt** [comment]
Hi @k4100x 

Yes, Octopi uses the system-wide configuration for qt5ct/qt6ct.
Here in my system I use LXQt DE and have "Widget Style/Qt Style set to "qt6ct-style".

So, in my qt6ct/qt5ct app, I create a copy of the "darker color scheme" and change "Link" and "Visited Link" colors to "#55ff7f".

Simple as that.
