### ISSUE TITLE
Octopi is trying to contact to Baidu .com

### ISSUE THREAD

**Issue by KarkanAlzwayed** [aarnt/octopi#572]
I have OpenSnitch installed on my system. It shows that
Octopi tries to connect to the chinese search engine Baidu. com. And that site collects personal data and all that. Why is it trying to connect to this site? I blocked it from doing that and then it just kept crashing for a while, then it worked, but it was still iffy. Thanks

**Comment by aarnt** [comment]
Hi @KarkanAlzwayed 

Because our Chinese Octopi users cannot contact google.com for "online/offline" tests. I'll have to create an option for this one.

**Comment by KarkanAlzwayed** [comment]
Thank you so much for clarifying. I wasn't aware that Google/Baidu was needed for something on an app like Octopi. But an option makes sense. Thank you.

**Comment by aarnt** [comment]
Fixed upstream.
