### ISSUE TITLE
Broken with pacman 7.0.0

### ISSUE THREAD

**Issue by ronillon** [aarnt/octopi#574]
Since pacman 7.0.0 octopi will not start and throws an error:
"octopi: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory"

pacman 7.0.0 updates libalpm.so.14 to libalpm.so.15
https://gitlab.archlinux.org/pacman/pacman/-/releases/v7.0.0

**Comment by aarnt** [comment]
This is normal. You'll need to recompile alpm_octopi_utils and octopi.

**Comment by fischer-felix** [comment]
Since this is something that seems to occur quite regularly, I propose adding a log output so that when people try to start octopi, and it does not work, they know to recompile and don't get sent googling around.
