### ISSUE TITLE
Plural problems

### ISSUE THREAD

**Issue by SafaAlfulaij** [aarnt/octopi#60]
There are some strings that are not marked as plural. In English, Adding "s" is the way to pluralize the noun. This method does not apply to other language.
For example:
```
    QString message;

    if (count == 1) {

        message = tr("%1 item replaced").arg(count);

    } else {

        message = tr("%1 items replaced").arg(count);
    }
```
This will work perfectly for English and French, But not for Polish.
A webpage describes the Plural forms: http://doc.qt.digia.com/qq/qq19-plurals.html

**Comment by manjaro** [comment]
We will take another look at your fix. At first I didn't get the code and assumed it was nonsense ...

**Comment by aarnt** [comment]
Thanks you for the tip, pal! It was merged!
