### ISSUE TITLE
Repoeditor slovak translation

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#62]
I have created slovak translation of octopi repoeditor.
i cant create a pull request with binary (qm) file, so i have uploaded translation (ts with qm) on my dropbox with public access.
Here is link, please commit it:

https://www.dropbox.com/s/x3h56n8ww6qozk1/repoeditor_slovak_translation.tar.gz?dl=0

Thanks.

**Comment by aarnt** [comment]
Done. Translation Project is in transifex too.
