### ISSUE TITLE
Sync repos after boot on Gnome 3.14

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#63]
I am using Antergos 64bit with Gnome 3.14 and octopi dont sync repos after system start-up.
My internet connection is via WiFi, maybe octopi should wait for connection get established, or problem is in something else.
How to debug this situation?

**Comment by aarnt** [comment]
Hi, do you mean octopi-notifier do not sync? Or are you saying octopi do not sync when you click "sync db" ?

**Comment by prescott66** [comment]
I ment Octopi-notifier....manual sync works in octopi or via octopi-notifier.

**Comment by aarnt** [comment]
I think it's ok now.
BTW, if you like Octopi, consider staring this Github repository :-)

**Comment by prescott66** [comment]
already starred ;-)
thanks for fix.when do you plan release next version?
