### ISSUE TITLE
Cant build octopi master

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#64]
After running command "makepkg -f " i get this error at the end:

==> Building octopi-repoeditor...
Cannot find file: repoeditor.pro.

**Comment by manjaro** [comment]
Edit your PKGBUILD. pro filename changed to **octopi-repoeditor.pro**

**Comment by prescott66** [comment]
thx that helps...should be created a patch for this issue?

**Comment by manjaro** [comment]
Latest PKGBUILD you can find [here](https://github.com/manjaro/packages-community/tree/master/octopi).
