### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#68]
After building octopi master, notifier icon dissappeared from my panel.
Octopi-notifier is running, but icon is missing (as you can see on screenshot).
Second thing is that app icons for Octopi-notifier and Octopi-repoeditor is missing too (as you can see on second screenshot).
After reinstalling Octopi-0.5.0 from AUR, icons are back.
![octopi-notifier](https://cloud.githubusercontent.com/assets/735265/5853506/a9e01d74-a224-11e4-90b9-12d13bba014b.png)
![octopi-apps](https://cloud.githubusercontent.com/assets/735265/5853532/cbbcea3a-a224-11e4-9740-d0704f7d8c26.png)

**Comment by aarnt** [comment]
GTK window managers have a known issue of being "confused" while displaying Qt5 icons. Maybe compiling notifier with Qt4 libs will suffice.
