### ISSUE TITLE
Translateable app names

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#71]
Just wondering, if can be app names (Octopi repoeditor and Octopi notifier) translate-able, so in menu with apps, i.e. in Gnome Shell, should be Octopi more integrated and user friendly.

**Comment by aarnt** [comment]
It could be done, prescott66.
But I'd rather not do that. Because it reminds people of the tool's binary files and english language has way shorter names for them. For instance, in pt_BR (my language) repoeditor would become "Editor de repositórios do Octopi".
