### ISSUE TITLE
Suitable terminal

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#73]
I get this error when trying to install something from AUR:

ERROR: Octopi found no suitable terminal!

Which terminal should i have to install?
It would be nice, if that suitable terminal will be in PKGBUILD dependencies.

**Comment by prescott66** [comment]
i see xterm in optional dependencies. but i think that it should be needed dependencie, for full function of octopi

**Comment by aarnt** [comment]
This is our PKGBUILD file contente:
"depends=('qt5-base' 'qt5-declarative' 'xterm')"
