### ISSUE TITLE
No interpunction in xterm window

### ISSUE THREAD

**Issue by prescott66** [aarnt/octopi#78]
While installing package from AUR, there is no interpunction in yaourt strings in xterm window. instead of interpunction chars i see unrecognizeable chars

**Comment by aarnt** [comment]
Prescott, could you test using yaourt outside octopi in the xterm, to see if it happens?
I think it's not an octopi issue.

**Comment by aarnt** [comment]
Closing as out of reports.

**Comment by prescott66** [comment]
in Xterm is working diacritics and interpunctions for me...so i will reopen this issue
