### ISSUE TITLE
octopi not showing groups entries after select other group name

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#79]
After select few random group from list the package list window is not refreshing.
![zaznaczenie_154](https://cloud.githubusercontent.com/assets/9846948/6225047/8037211e-b685-11e4-93ce-159dc546d811.png)
![zaznaczenie_155](https://cloud.githubusercontent.com/assets/9846948/6225048/803c9b8a-b685-11e4-9113-774566d9e541.png)
![zaznaczenie_156](https://cloud.githubusercontent.com/assets/9846948/6225049/803f4362-b685-11e4-9ff1-b1019c8c6648.png)

Package was build based on lastest git commit: 6197e3faecf22e848c4eb113bcdaecb763ecaed4

**Comment by aarnt** [comment]
Thanks, pal. It's fixed now.
