### ISSUE TITLE
No Icon in Gnome-Shell Tray with v0.6.0-1

### ISSUE THREAD

**Issue by foer** [aarnt/octopi#81]
After upgrading Octopi to Version 0.6.0-1 the trayicon on gnome-shell is gone; its really only the icon as you can see in the Picture:
![o](https://cloud.githubusercontent.com/assets/3774978/6435912/8eff864c-c0a7-11e4-9761-707f527582bf.png)

I can't find anything to solve this problem...reinstalling or manually refreshing the icon cache doesn't do the trick.

$ octopi-notifier --version
"Octopi Notifier - 0.6.0 (Qt 5.4.1)"

$ lsb_release -a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling

$uname -a
Linux foer-archlinux 3.19.0-1-ck #1 SMP PREEMPT Fri Feb 27 20:13:37 EST 2015 x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 3.14.3

**Comment by ugopozo** [comment]
I have exactly the same issue.

**Comment by mumbly58** [comment]
Same on XFCE 4.11

**Comment by aarnt** [comment]
Hi guys,
Can you try to build octopi-notifier with Qt4 instead of Qt5?
It should help in those cases.

**Comment by foer** [comment]
Hi,
i've now builded octopi with qt4 as you suggested...now everything is fine!
Thanks!

**Comment by aarnt** [comment]
Perfect foer,
It's a pitty there's a Qt5 bug in GTK WMs!
But... we must move on.

**Comment by mumbly58** [comment]
The question is : how to compile with qt4 ;) ?

2015-03-02 23:23 GMT+01:00 Alexandre Arnt <notifications@github.com>:

**Comment by foer** [comment]
Hi,
for Archlinux build it from the AUR:
Replace qmake-gt5 with qmake-qt4 in build() for the octopi-notifier:
...
--> msg "Building octopi-notifier..."
--> qmake-qt4 octopi-notifier.pro the build()-section
...
Thats it. Otherwise for an other Distribution compile it with qmake-qt4.

**Comment by prescott66** [comment]
so any fix to make tray icon visible out of the box? after installing from AUR
