### ISSUE TITLE
IgnoreGroup is not used

### ISSUE THREAD

**Issue by Kirek** [aarnt/octopi#83]
Just downgraded qt5 in Manjaro because in has some issues with plasma5 in a vmware guest.
I have this in pacman.conf
IgnoreGroup = qt5

But Octopi show that I need to upgrade every package in qt5 group.

**Comment by demmm** [comment]
Is this working correctly if you try to update in pacman directly?
Looking at the Arch PKGBUILD for Qt5 (I presume that is what Manjaro uses), the groups are not set for each split package.
Line 42:
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5

**Comment by Kirek** [comment]
Yes, it works correctly with pacman.
If each split package in the PKGBUILD doesn't override the groups variable it uses the value defined by default (groups=('qt' 'qt5') in this case).

**Comment by aarnt** [comment]
Kirek,
That feature has just been implemented.
Enjoy!
