### ISSUE TITLE
Suggested GUI Improvement

### ISSUE THREAD

**Issue by mshelby** [aarnt/octopi#84]
A GUI suggestion regarding the pop-up window which displays before switching the user to a terminal window:

Remove the three button option and replace it with an "Cancel" & "OK" button. Also, change the wording on the confirmation window to show something to the effect: "The following six targets need to be retrieved. Total download size 6693.40 KB. Press "OK" to launch a terminal window to continue upgrade." Doing so would add needed polish and clarity to the process.

**Comment by aarnt** [comment]
Hi mshelby,
This window does not call only a terminal, it can also execute transactions inside Octopi.
Plus, more text would require more translations. And people are very lazy to update the translations.
