### ISSUE TITLE
octopi missing other repos in list - see only core and testing

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#85]
Issue: select kde group - duplicate entries:
![zaznaczenie_003](https://cloud.githubusercontent.com/assets/9846948/6562956/8b1c4618-c69d-11e4-9137-1deb63fc154f.png)
![zaznaczenie_004](https://cloud.githubusercontent.com/assets/9846948/6562957/8b21923a-c69d-11e4-98b0-dadadd28d0c2.png)
After select all group is ok:
![zaznaczenie_005](https://cloud.githubusercontent.com/assets/9846948/6562958/8b222330-c69d-11e4-9db9-e00731b5845c.png)

**Comment by aarnt** [comment]
Stable or Testing?

**Comment by FadeMind** [comment]
Look at screen:
![zaznaczenie_006](https://cloud.githubusercontent.com/assets/9846948/6569728/b00b0ce6-c6ef-11e4-86c2-1dbbe23d0a87.png)
logrotate versions is the same in core and testing repos (formally it is double of core repo value).
![zaznaczenie_007](https://cloud.githubusercontent.com/assets/9846948/6569762/3e13dc66-c6f0-11e4-924c-10870a19d8fc.png)
KDE in extra is 14.12.2-1
KDE in testing is 14.12.3-1
Octopi don't see testing repo and other version from testing repo but all packages identyfy as from core/community/extra instead testing/community-testing versions. This is main issue of this. 
Reference:
https://www.archlinux.org/packages/?sort=-last_update&q=kdeartwork&maintainer=&flagged=
https://www.archlinux.org/packages/?sort=-last_update&q=logrotate&maintainer=&flagged=

**Comment by FadeMind** [comment]
Fixed. I installed update based on commit 14d9f45dff52756a904a0b67ed9242bcbdc4e344.

![zaznaczenie_008](https://cloud.githubusercontent.com/assets/9846948/6605449/63042e68-c830-11e4-93f9-56f32a3135c3.png)

**Comment by aarnt** [comment]
Weird.
Do you think I can close then?
Anyway I couldn't reproduce here.

**Comment by FadeMind** [comment]
Well... issue was not present in commit 5421bf328c787b2a7e5cb58a785bcd1caca24d08
issue still present in lastest 2f0db012663521a3360d23bef61af585957d7740

yaourt output about installed packages from testing repos:

yaourt -Q|grep testin
testing/btrfs-progs 3.19-1
testing/cmake 3.2.1-1
testing/curl 7.41.0-1
community-testing/kadu 2.0-1
testing/kmod 20-1
multilib-testing/lib32-libssh2 1.5.0-1
multilib-testing/lib32-libx11 1.6.3-1
multilib-testing/lib32-util-linux 2.26-1
testing/libssh2 1.5.0-1
testing/libtasn1 4.3-1
testing/libutil-linux 2.26-3
testing/logrotate 3.8.9-1 (base)
testing/patch 2.7.5-1 (base-devel)
testing/util-linux 2.26-3 (base base-devel)

but Octopi see only:
![zaznaczenie_020](https://cloud.githubusercontent.com/assets/9846948/6634162/4a2f0e1a-c954-11e4-827b-6b9ad92fb6d6.png)
patch package is installed from testing repos but octopi don't see these package anywhere:
![zaznaczenie_022](https://cloud.githubusercontent.com/assets/9846948/6634167/5a7829f0-c954-11e4-8779-634f095a343b.png)
pacman -Ss patch
testing/patch 2.7.5-1 (base-devel) [zainstalowano]

Logrotate
![zaznaczenie_023](https://cloud.githubusercontent.com/assets/9846948/6634179/9f4862ca-c954-11e4-9d55-ae2778a5c1f0.png)

pacman -Ss logrotate
testing/logrotate 3.8.9-1 (base) [zainstalowano]
    Rotates system logs automatically
core/logrotate 3.8.8-2 (base) [zainstalowano: 3.8.9-1]
    Rotates system logs automatically

**Comment by FadeMind** [comment]
Commit 5421bf328c787b2a7e5cb58a785bcd1caca24d08 good working proof:
http://i.imgur.com/Gzs5VXW.png

**Comment by FadeMind** [comment]
Lastest 9fee78dcc242259167507a412978afb07ae983e4 commit working like a charm. 
Fixed issue.

![zaznaczenie_025](https://cloud.githubusercontent.com/assets/9846948/6644555/499461f6-c9b5-11e4-8556-aa59c0c965da.png)

**Comment by ZeroBit** [comment]
Now it works fine. Thanks for fixing.

![octopi2](https://cloud.githubusercontent.com/assets/6258813/6769602/60b9cf44-d0ac-11e4-9957-f66a183cb034.png)

**Comment by aarnt** [comment]
Do you think this issue can be closed?

**Comment by FadeMind** [comment]
Yes.

**Comment by aarnt** [comment]
Ok, thanks.

**Comment by ZeroBit** [comment]
Yes, I think it can. But not this one
octopi missing other repos in list - see only core and testing
Because I mistakenly put my comment in there, but then I deleted it and
wrote it again in the relevant one.

**Comment by aarnt** [comment]
ZeroBit, I did not understand... are you having this issue?

**Comment by ZeroBit** [comment]
About this issue *octopi missing other repos in list - see only core and
testing #85 *I can't say anything. I don't have this problem.
this Issue *IgnorePkg ignored (#57)* is resolved

On Sun, Mar 22, 2015 at 10:45 PM, Alexandre Arnt <notifications@github.com>
wrote:

> ZeroBit, I did not understand... are you having this issue?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/aarnt/octopi/issues/85#issuecomment-84700856>.
>



-- 
C Õ×ÁÖÅÎÉÅÍ, áÌÅËÓÁÎÄÒ ìÙÛÅÎËÏ.

**Comment by aarnt** [comment]
Ah ok... I misunderstood your post :-) Thanks.
