### ISSUE TITLE
Compilation of octopi-notifier fails: ‘getOutdatedAURPackageList’ is not a member of ‘Package’

### ISSUE THREAD

**Issue by UndeadKernel** [aarnt/octopi#87]
The notifier cannot be built as a function not implemented in class 'Package' is called.
This is the error message as printed by g++:
```
mainwindow.cpp: In member function ‘void MainWindow::refreshAppIcon()’:
mainwindow.cpp:492:27: error: ‘getOutdatedPackageList’ is not a member of ‘Package’
   m_outdatedPackageList = Package::getOutdatedPackageList();

mainwindow.cpp:497:32: error: ‘getOutdatedAURPackageList’ is not a member of ‘Package’
     m_outdatedAURPackageList = Package::getOutdatedAURPackageList();
```

**Comment by FadeMind** [comment]
I confirm this.

mainwindow.cpp:497:32: error: ‘getOutdatedAURPackageList’ is not a member of ‘Package’
     m_outdatedAURPackageList = Package::getOutdatedAURPackageList();
                                ^
Makefile:864: polecenia dla obiektu '../build-octopi-notifier/mainwindow.o' nie powiodły się
make: *** [../build-octopi-notifier/mainwindow.o] Błąd 1
make: *** Oczekiwanie na niezakończone zadania....

**Comment by aarnt** [comment]
Thanks guys,
It's fixed now!
