### ISSUE TITLE
Monochrome icon for notifier

### ISSUE THREAD

**Issue by stovocor** [aarnt/octopi#89]
In Cinammon I have only monochrome icons in the tray... and the green one from Octopi.

It would be nice to have an option for a monochrome icon when there are no updates available.

**Comment by demmm** [comment]
For KaOS, this one is in use :

![octopi_green](https://cloud.githubusercontent.com/assets/5360485/6804821/237b7c48-d216-11e4-8afa-381f16379145.png)
