### ISSUE TITLE
Root Pass Prompt using only ENG lang in SOME situation

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#91]
**BAD** prompt in english language WHEN:
- I want clean cache
- I want install/remove any package
- I want refresh database

screenshot:
![zaznaczenie_035](https://cloud.githubusercontent.com/assets/9846948/6846038/195639dc-d3bb-11e4-8848-3591bbff884d.png)

**GOOD** prompt in my native lang (polish) WHEN:
- I want open Command Prompt
- I want open Repo Editor

screenshot:
![zaznaczenie_036](https://cloud.githubusercontent.com/assets/9846948/6846039/1959aacc-d3bb-11e4-9afb-f965a08166fe.png)

OFC I using lastest git snapshot always. Current is: 8829e2c

**Comment by aarnt** [comment]
Clean cache should be fixed. The other two cannot be done because I need english output to be parsed.

**Comment by FadeMind** [comment]
without changes:
![zaznaczenie_014](https://cloud.githubusercontent.com/assets/9846948/7081775/27b96e66-df48-11e4-9eb8-7abbeb9e2914.png)

Note I migrated to Plasma 5 now.

**Comment by aarnt** [comment]
Hmm... I thought you here talking about ctrl+shift+c.
