### ISSUE TITLE
Prompt with additional depends without details

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#95]
You wan't remove kernel. In default octopi will show prompt with list of depends packages.  In this prompt  You should saw names, description. But lastest dev version showing names only. Description is blank.
![zaznaczenie_001](https://cloud.githubusercontent.com/assets/9846948/6936978/1f6772a4-d858-11e4-9475-8e2dba24f3ee.png)

**Comment by aarnt** [comment]
Fixed.
Thanks!
