### ISSUE TITLE
Octopi Notifier Autostart / Tray Icon

### ISSUE THREAD

**Issue by famo** [aarnt/octopi#96]
The autostart mechanism of octopi isn't clear or configurable as expected. There are no files located in the usual places (~/.kde4/Autostart, ~/.config/autostart, ~/.kde4/share/autostart).

**Use case**
There are several user accounts on one PC, however only one of them does the administration (has sudo rights). Currently it is not possible to deactivate the Octopi Notifier for the non admin accounts.

**Comment by FadeMind** [comment]
Simply add new one:
         nano .config/autostart/octopi-notifier.desktop
with code
        [Desktop Entry]
	Hidden=true
        
And save file.

Octopi using global /etc/xdg/autostart directory for store autostart desktop file AND octopi systemd service OFC.

**Comment by famo** [comment]
Aha, so that means I have to create the octopi-notifier.desktop (hidden-) entry for each non-admin user?

But the systemd service I can leave it as it is? Ii.e. non-sudoers will not be able to update the system or install packages?

**Comment by FadeMind** [comment]
You don't have installed octopi-notifier then.

**Comment by famo** [comment]
But I have:
http://wstaw.org/m/2015/04/04/plasma-desktopJyB476.png

Can you double-check it on your side?

**Comment by FadeMind** [comment]
[tomasz@arch ~]$ la /etc/xdg/autostart/
         razem 44K
         drwxr-xr-x 2 root root 4,0K 28.03.2015 15:14 ./
         drwxr-xr-x 8 root root 4,0K 13.03.2015 19:17 ../
         -rw-r--r-- 1 root root  305 25.03.2015 10:18 at-spi-dbus-bus.desktop
         -rw-r--r-- 1 root root 1,7K 19.03.2015 13:34 baloo_file.desktop
         -rw-r--r-- 1 root root 7,6K 03.10.2013 21:05 gsettings-data-convert.desktop
         -rw-r--r-- 1 root root  182 28.03.2015 15:14 octopi-notifier.desktop
         -rw-r--r-- 1 root root 7,8K 17.03.2015 20:52 print-applet.desktop
         -rw-r--r-- 1 root root 4,3K 13.02.2015 01:53 pulseaudio.desktop

**Comment by famo** [comment]
Ok, did you delete it and see if octopi-notifier does not come up?

**Comment by famo** [comment]
any updates on this?
