### ISSUE TITLE
 Unable to load library icui18n after update icu 55.1-1

### ISSUE THREAD

**Issue by FadeMind** [aarnt/octopi#99]
Arch pushed icu 55.1-1 in testing now during perform any action I see warning;

          Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"

I rebuilt octopi against new icu version but I see the same error.

    [tomasz@arch ~]$ locate icui18n
    /usr/lib/libicui18n.so
    /usr/lib/libicui18n.so.55
    /usr/lib/libicui18n.so.55.1
    /usr/lib32/libicui18n.so
    /usr/lib32/libicui18n.so.54
    /usr/lib32/libicui18n.so.54.1

**Comment by aarnt** [comment]
Could you test with latest commit?

**Comment by FadeMind** [comment]
Commit 4ce02a273a6b6908b2e6060d770702ed9975e003  fixed issue.
